- bin/fish
According to the Getopt::Std manpage, it is strongly recommended to
set this variable.
Without this option, calling "fish --version" does not do the right
thing --- a user expects either that the version is printed, or that
the option is unknown and the call fails.
See also https://github.com/plicease/Shell-Config-Generate/issues/10
where this showed up as a problem.
> fish: set $Getopt::Std::STANDARD_HELP_VERSION to true

- bin/touch
They were there probably because of quick copy-paste-edit Pod writing.
/cc @Abigail
> Fix typos in Pod for touch utility

- bin/rm
The listed address `@tardis` hasn't been in use for the past ten years.  The new one .. has.
Minor change, the code itself could probably use some love, but this is a drive-by update :)
> Update email address from the ancient one.

- Makefile.PL
Use of uninitialized value $ENV{"PERL_MM_OPT"} in pattern match (m//) at Makefile.PL line 50.
Unparsable version 'v.0.3.2' for prerequisite Test::Trap treated as 0 at C:/Strawberry/perl/lib/CPAN/Meta/Requirements.pm line 140.
> Solve warnings in Makefile.pl

- bin/addbib
... by adding a DESCRIPTION, FILES and COPYRIGHT sections.  Some text has
been copied from the FreeBSD manual for the utility of the same name.  Where
this has been done has been mentioned in the text.
In adding the COPYRIGHT section, I made the assumption that the code was released under the same terms as the `factor` utility within this repository.  By checking old versions of PPT I was only able to come up with a copyright date of 2004, this seemed to be the most appropriate date, however it could actually be earlier than this; I hope this is ok.
I tried to be consistent with the docs in `factor` so that the documentation for all programs is more consistent as requested in #3.  If you want anything changed, please simply let me know and I'll update appropriately and resubmit the PR.
> Document `addbib` more fully

- bin/units
Addresses #44 
Can someone try this on a Windows machine? Please feel free to reject this PR if this doesn't satisfy anything.
> Make units platform agnostic about path separators

- lib/PerlPowerTools.pm
I was just reading the POD and saw "cal" described simply as "member of the Perl Power Tools" which gives little away. This is just a documentation fix to change it to "display a calendar" (which is what my binary cal gives with apropos).
HTH.
> Doc: more specific description of "cal"

- Makefile.PL
`find` command needs `find2perl` which was removed from the perl core in 5.20.
> declare dependency on App::find2perl

- Makefile.PL
- t/echo.t
Recreated the needed functionality of Test::Trap inside t/echo.t
Existing t/echo.t mixed tabs and spaces. Standardized to tabs
Addresses #49 
Criticisms more than welcome, I'm not as experienced with tests as I'd like to be.
> Removed Test::Trap dependency

- bin/clear
For #46.
Using Term::Cap may not work on Windows (at least with Strawberry Perl), in which case, use the use the system "cls" command.
> Fallback to system("cls") on Windows

- bin/patch
Can't read a patch in from STDIN and prompt user input from STDIN at the same time.  Unlike Term::UI, Term::ReadLine is a core module.
Also, long lines in docs (pretty much copied directly from manpages) annoyed me, so snipped them.
> Use Term::ReadLine instead of STDIN to prompt user input

- bin/find
- t/find.t
For #12.  Modify output of find2perl to support -amin, -cmin and -mmin.
> Add -amin, -cmin and -mmin to `find` command

- bin/robots
The block checking for the Curses module was always calling exit, so bin/robots never ran;  correcting that, bin/robots was not importing Curses constants, instead using package globals created with use vars which were unset.
> Fixes for bin/robots

- bin/addbib
Change bareword filehandles and use three-argument open in addbib.
> addbib update

- bin/patch
*Rebased from #84*
Currently patch saves an reference to a localized NULL filehandle in the
object hash in its bless() method. But when the bless() method returns
the original value of *NULL is restored (which is empty). Meaning that
when patch later calls apply() and tries to print to the  NULL handle,
we get a warning about trying to print to a closed filehandle.
The correct behavior should be to store a copy of *NULL (not a
reference *NULL)  or to not localize *NULL in the first place..
> Fix issue with NULL filehandle in patch.

- bin/nl
- t/data/nl/nl.txt
- t/nl.t
Hello Brian,
as discussed by email, here's a clone of the 'nl' utility (line numbering filter).
- Unfortunately, I've not been able to test it with perl 5.8 (I couldn't install it).
- I've added a non-standard option "-b eEXPR", similar to "-b pEXPR", but to exclude lines matching EXPR pattern from numbering.
- The usage/pod is my own words, and has a much lower quality than the BSD/GNU nl manuals. I didn't dare copy those, since I'm not sure about license/copyright matters.
> 'nl' v1.00

- bin/pwd
Hello,
I've added these two standard options (with/without symlinks).
I haven't changed the default behaviour since it's not standardized anyway : POSIX (-L), Darwin (-L), OpenBSD (-P), GNU (-P).
> added 'pwd' options -L -P

- bin/bc
GNU, FreeBSD, and OpenBSD act like this, so this 
brings this version into line with those.
Co-authored-by: Michael Mikonos <Michael.Mikonos@tpgtelecom.com.au>
> bc exits immediately after reading "quit"

- bin/od
* match GNU od: exit with error code and do not continue if bad options are detected
* no need for -h (help) flag; usage already printed
* remove unsupported -a flag mentioned in usage string and POD
> od: exit(1) for bad options. garbage collect -a and -h

- bin/bc
$ bc -v
bc 1.07.1
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006, 2008, 2012-2017 Free Software Foundation, Inc. $ bc -q
x
0
y++
0
y
1
Same behavour is seen for -s (standard posix) flag; variables can be operated on before being assigned. Also for the Gavin Howard version of bc (below).
$ bc.gavin -v
bc.gavin 6.2.4
Copyright (c) 2018-2023 Gavin D. Howard and contributors ...
$ bc.gavin -s
>>> x
0
>>> y += 2
>>> y
2
>>> z++
0
>>> z
1
>>> quit
This version of bc raises an error for regular variables but not for arrays.
$ perl bc 
ary[0] = 123
123
ary[1]
0
var0
var0: undefined variable
Also see:
https://pubs.opengroup.org/onlinepubs/009696799/utilities/bc.html
"Simple identifiers and array elements are named expressions; they have an initial value of zero and an initial scale of zero."
> bc: auto init of simple variables

- TODO
- bin/dc
As done in OpenBSD version of dc. This commit will print identical warning message as OpenBSD dc.
Sync TODO file.
> dc: remove ! command for shell

- bin/od
* Existing -s option skips bytes at beginning of input
* NetBSD, OpenBSD and GNU versions of od(1) call this option -j because -s indicates something else according to the standard
* We can rename the option for better compatibility with shell scripts (-j is currently free)
* While here, avoid seek() if -j isn't set
* Remove unused variables $retval and $skip
Also see:
https://pubs.opengroup.org/onlinepubs/009696899/utilities/od.html
> od: rename option -s to -j

- bin/xargs
When GNU xargs is given an invalid command to run it prints the command and the error.
$ ls -1 a* | xargs 'cat;ls' 
xargs: cat;ls: No such file or directory
With the above input, this version of xargs fails silently (but correctly). Internally it calls system(LIST) rather than system(STRING), so the intent of the code is to bypass the shell. I think making the error string visible would avoid confusion.
> xargs: report system() failure

- bin/head
This version of head treats "head -" the same as "head"; neither option seems to work. 
$ perl head < longfile
head: head: -: No such file or directory
GNU head accepts "head -n 1 - foo -" which will read stdin twice.
Support stdin by conditionally opening a file, being careful not to close stdin in case it appears repeatedly.
Also print usage string (taken from SYNOPSIS) if invalid options are provided.
> head: support for reading stdin

- bin/od
When reading from urandom device, od appears to extend the 16-bit numbers it formats.
$ od -x /dev/urandom | head -n 1    # GNU od for reference
0000000 cdb9 326b daef 219e 3d2b e438 2d33 a52e
$ perl od -x /dev/urandom | head -n 1 
00000000 ffffffffffffeb2c fffffffffffff038 71e6 ffffffffffff9244 fffffffffffffde4 fffffffffffff8e9 18d0 ffffffffffffab76 
hex() is called for each line of output (name overlaps with built-in hex() function). When I debug this I note that @arr is a list of signed 16 bit numbers. The format $strfmt passed to printf() looks like '%.4x %.4x %.4x %.4x %.4x %.4x %.4x %.4x '. printf() is happy printing negative hex numbers but @arr should be unsigned. Switching unpack's format argument from signed to unsigned fixes the problem on my system.
> od -x: incorrect hex output

- bin/bc
The bc language has the operator '&&' but not '&'. This version of bc has a grammar extension &"STRING" which calls eval().
$ perl bc 
":)"
:)
& "syscall 23,45"
Segmentation fault (core dumped)
bc can be run under "perl -d" for debugging so the extension seems undesirable.
> bc: remove support for evaluating perl expressions

- bin/grep
$ perl grep yo < longfile
grep: -: No such file or directory
* path '-' is passed to open() which is causing the error---possibly this worked in older perls
* Fix this by conditionally calling open()
> grep: support stdin

- bin/od
* This version of od reads only one file, but silently ignores extra file arguments
* Read from stdin if no file argument is set, or if file is '-'
* Support -j on stdin & unseekable files by checking if seek() fails (GNU od supports -j on stdin)
* Print error string if read() fails, e.g. when reading from a directory
> od: support reading from stdin

- bin/ed
* edPrint() is written as a loop from $adrs[0] to $adrs[1]
* When running the command "1p", edPrint() sometimes infers "current line" for $adrs[1]
* When user enters one line address we need to print only that one line
* The correct behaviour for 1p (single addr) is the same as 1,1p (addr range)
* Apply the same fix as done in edDelete; commit 6e411ed92a44ae174ea8e4a92906634d8ccd1ee2
* Example of the incorrect behaviour of 1p after running 1,2p (including trace statements)...
$ perl ed
ME: a
ED: edParse() returns adr( )
ME: aa
ME: bb
ME: cc
ME: dd
ME: .
ME: 1
ED: edParse() returns adr(1 )
ED: aa
ME: 1p
ED: edParse() returns adr(1 )
ED: edPrint() interprets adrs(1 1)
ED: aa
ME: 1,2p
ED: edParse() returns adr(1 2)
ED: edPrint() interprets adrs(1 2)
ED: aa
ED: bb
ME: 1p
ED: edParse() returns …
> ed: looping in edPrint()

- bin/expr
* Patch previously submitted via email
* When arg1 is 0 or null, operator '|' is expected to return arg2
* Reference behaviour from expr on my Ubuntu system...
$ /usr/bin/expr '' '|' 22
22
$ /usr/bin/expr 0 '|' 3
3
$ /usr/bin/expr -1 '|' 0
-1
> expr: logical-or operator is backwards

- bin/install
* The default behaviour of this version of install moves files out of the source directory
* Other versions of install don't even support an option for moving files (default is to copy)
* GNU manual says: "This install program copies files"
* OpenBSD manual says: "-c  Copy the file. This is actually the default."
* Solaris manual says: "Each file is installed by copying it into the appropriate directory."
* Option -c is supported in the GNU and OpenBSD versions for backward compatibility
* Keep -c in this version and make it the default
* Example: do "make install" twice (where Makefile runs install) but in 2nd invocation the install directory is overridden (this won't work if the file was moved to 1st install destination)
> install: copy by default

- MANIFEST
- bin/base64
Justification:
* MIME::Base64 is included as part of perl
* NetBSD now has a base64 command, with arguments similar to GNU version
Notes:
* Output file option (-o) is what I'm used to doing when running b64decode on OpenBSD so it's supported in this version
* NetBSD version supports multiple input files but this version follows GNU behaviour and raises an error
> New base64 command

- bin/echo
* Portability text[1]: "If there are no arguments, only the newline is written"
* The code avoids doing join() on empty list so print the newline in the existing empty-args check
* Tested against echo on Ubuntu and OpenBSD
1. https://pubs.opengroup.org/onlinepubs/009604599/utilities/echo.html
> echo: emit newline by default

- bin/sum
* Implicit stdin when no arguments are provided
* Explicit stdin as '-', on its own or part of file list
* Print error and progress to next file if open() fails (matches GNU sum)
> sum: read stdin

- bin/bc
* This bc implementation previously supported Math::BigFloat but it was commented out
* Add a command option (-b) to interpret number literals as BigFloat (based on commented code)
* Older perls (e.g. 5.8.8) may not support BigFloat so disable it by default
* Remove outdated comment that Math::BigFloat doesn't support hex literals
* Standard bc is not required to support hex literals, and we still don't
* Remove outdated comment that Math::BigFloat doesn't support ** operator
Output:
$ perl bc   # default 
x = 12341234123489712364.123  
1.23412341234897e+19
x ** 2
1.52306059690787e+38
quit
$ perl bc -b   # new flag
x = 12341234123489712364.123
12341234123489712364.123
x ** 2
152306059690786889006379355337832937737.559129
quit
> bc: allow Math::BigFloat again

- bin/od
* I noticed that when the number of input bytes is odd, the output of od -x is incorrect
* This was because unpack('S', $data) returns nothing if $data is 1 byte
* Standard od zero-fills the 16 bit number
* The do-remainder-bytes logic is incorrect (tangled web of pack, unpack and substr)
* float() and long() require input to be zero-filled 32-bits
* udecimal(), decimal(), octal2() and hex() require input to be zero-filled 16-bits
* Patch tested on amd64 against GNU od
Original output which uncovered this:
$ perl hexdump test
00000000  c6 f3                                             |..|
$ od -j 1 -x test # gnu od
0000001 00f3
0000002
$ perl od -j 1 -x test
00000001 0001
00000002
Also without -j:
$ xxd in2 
00000000: d8ab 7a                                  ..z
$ perl od -x in2
00000000 …
> od: zero-fill input to required byte length

- bin/ed
* Standard ed treats the address 0 as valid for both "a" and "i" commands [1]
* The meaning of address 0 is, add text at start of buffer
* When starting ed with no file argument, buffer is empty and current address is 0
* This version of ed accepts "0a" (or just "a") on empty buffer
* "0i" command currently raises error: Can't insert before line 0
* When the buffer is not empty, GNU ed treats 0i the same as 1i
* shift(@lines) in edInsert() is safe if the list is empty, so this patch treats address 0 and 1 the same for $INSERT_MODE (aka "i")
[1]. https://www.gnu.org/software/ed/manual/ed_manual.html#Commands
Existing output for "a":
$ perl ed    # a == 0a
ME: a
ME: hey
ME: .
ME: 1
ED: hey
ME: Q
New output for "i":
$ perl ed    # i == 0i
ME: i
ME: yo
ME: .
ME: 1
ED: yo
ME: Q
> ed: allow insert on empty buffer

- bin/sum
* My version of perl is 64 bit, but this version of sum assumes perl numbers are only 32 bits
* The CRC value is calculated correctly, but in the return statement the bits in $crc are inverted with ~, causing sign to extend up to 64 bits on my system
* Correct this by explicitly masking off 32 bits before return
* Now the crc printed agrees with the crc on my OpenBSD system
Verification process on OpenBSD:
echo hallo > hallo
echo hello > hello
cksum hallo hello # reference crc output
perl sum -o0 hallo hello # our version
> sum: incorrect CRC output

- bin/ed
* When viewing text in less(1) and editing with vi(1) I usually enable line numbers
* Standard ed supports the n command [1], which prints a tab after a line number prefix
* Implement the n command by adding a parameter to edPrint()
* Note: "l" is still not implemented but could be a future change to edPrint()
[1]. https://pubs.opengroup.org/onlinepubs/009604599/utilities/ed.html
> ed: numbered print command

- bin/bc
* sccs id is not useful; we use git not sccs
* Remove unreachable code for $yyn==6 (quit keyword)
* Remove code related to printing a prompt (currently no prompt is printed anyway, and prompts are not part of standard bc)
* Unused subs exec_print(), fact() --- fact is not supposed to be a built-in bc function
* main() loops forever and does not return, so statement $count will never be printed
> bc: delete unused code

- bin/ed
* Standard ed has 2 ways to enable command prompt: -p option and P command
* P command toggles command prompt mode, using either the saved -p string or the default of '*'
* Previously, P was an alias for p but this contradicts the standard
* While here, add missing POD for recently added H command
> ed: implement command prompt

- bin/units
- t/units.t
This sequence of commits addresses the above-noted issues.  From earliest to latest, here's what they include:
1. Replace backticks in six places where they were (likely inadvertently) paired with apostrophes.  Now they match.
2. Fix issue #161 "units script produces incorrect results for definitions that include a fractional factor" by adding non-capturing group directive to the Fraction pattern in sub lex.
3. Add a test script and restructure units to support (a) calling from a test script, (b) returning as a hash when testing; and (c) supporting a non-interactive mode when two units are given as command-line arguments.
4. Implement support for temperature conversions; add a new debug mode (T for temperature); revise temperature definitions in the DATA table; update the POD; add test …
> Fixes to the units utility addressing issues #161 (fractions) and #162 (temperature units)

- bin/ed
* When search is written as /hex ed finds the last match (i.e. searches backwards)
* When search is written as /hex/ ed searches forwards
* These two cases should be identical (trailing slash may be be omitted in search)
* Searching backwards should be indicated by the ?hex not /hex
* Trailing "?" is also optional for backwards search, i.e. ?hex is also ?hex?
* The fix is to strip leading and trailing question marks from $pattern
$ fgrep -n hex in | head -n 1
5:Name: hexdump
$ fgrep -n hex in | tail -n 1
216:No support for multi-byte hex display, or plain hex output.
$ ed -p 'ME>' in # GNU
4875
ME>/hex
Name: hexdump
ME>n
5	Name: hexdump
ME>q
$ perl ed in
in
4875
/hex
No support for multi-byte hex display, or plain hex output.
n
216	No support for multi-byte hex display, or plain hex …
> fix ed search direction

- bin/ed
* This feature was in Todo-list comment for a long time
* "j" by itself is an error, to match GNU ed
* "1j" and "1,1j" address a single line not a range; no change occurs
* "1,3j" is interpreted as "join lines 2 and 3 to the end of line 1 (line 4 becomes the new line 2)
* I tested this by diffing output against GNU ed output, given the same join command and the same input
* Backwards address ranges (e.g. "3,1j") generate an error before edJoin() is called
> ed: implement join command

- bin/printf
* The perl printf() called in this command does not support the escape \v
* Standard printf command supports \v as part of the format argument... <https://pubs.opengroup.org/onlinepubs/009695299/utilities/printf.html>
* Other C-escapes are supported already in this version: \\ \a \b \t \n \f \r
* Add support for \v by translating format string before printf() is called
* Now we have better POSIX support, and the limitation can be removed from the POD text
> printf: support c-escape \v

- bin/grep
* Standard grep does not recursively search a directory unless -r option is given
* This version of grep has code that infers -r based on ARGV, which doesn't follow expected behaviour of other greps
* The "is a directory" warning is printed by GNU grep, so remove the check for trace option (-T) in our code
> grep: -r set without -r being set

- bin/sleep
* Exit code for bad value of Seconds did not indicate failure, so do exit(1)
* Missing operand case already did exit(1) so probably this was missed
* Slightly improve compatibility by using stderr for errors, and make messages match GNU sleep
> sleep: exit code on error

- bin/arithmetic
* On my system, "Please type a number" message is never displayed for bad input
* Looking at the code, I see two statements (print and redo) separated by comma
* This patch makes the Please prompt appear
* While here, fix a typo in summary report
> arithmetic: make expected prompt appear

- bin/install
* The normal usage of install(1) copies files to a destination directory
* "install dir1 dir2" makes no sense because the source argument (dir1) is expected to be a regular file
* I observe that an empty file "dir1" is created in dir2 before an error is printed
* Fix this in install_files() which is invoked by default (and for -C option)
* Option -d allows all arguments to be directories; this is handled in install_dirs() and is unchanged
* Patch aligns with GNU install behavior: print a warning and continue copying the next file in list
> install: ignore directories in source file list

- bin/ed
* Avoid calling open() on a directory, which would succeed
* GNU and OpenBSD versions of ed behave consistently if a directory is specified
* Raise error: cannot read input file
* Start ed with an empty buffer
* Also print a helpful message on stderr to indicate the specified file is a directory
* edEdit() is called when opening files (initially from ARGV or via "e" command)
> ed: raise error for opening a directory

- bin/test
* Make all calls to bad_arg() consistently pass a single param
* Passing extra param of 0 here causes 0 to appear in the error message, which is confusing
* I checked that the exit code is still 2, i.e. param2 did not modify exit code
> test: improve error message

- bin/cp
* Multiple source files can be given before a destination
* Some of what process_arguments() returns was being thrown away
* For case where system() is called, cp command can handle all files at once
* For case where File::Copy::copy() is called, introduce a loop because it can't handle a list of source files
* Exit early if insufficient file arguments are provided: 0 (cp), 1 (cp srcfile)
> cp: copy many files at once

- bin/printf
* Standard printf command interprets %c in format string as: first character of string
* FreeBSD manual says: "first byte" to make it obvious we're not talking about multi-byte characters
* OpenBSD manual says: "first character"
* HP-UX manual says: "first character" <https://nixdoc.net/man-pages/HP-UX/man1/printf.1.html>
* Support standard %c in this version by translating %c to %.1s which truncates the string argument
* I compared output of (perl printf 'watch out %c%c' one two) against GNU printf and bash built-in printf
> printf: standard meaning of %c

- bin/cmp
* cmp command compares two files which may be binary but may not be a directory
* I was getting a success exit code on my system when running: perl cmp .. file.txt
* Check for directory before open() is called
* cmp exits 0 if the compared files match and 1 if they don't, so exit code 2 is designated for actual errors
> cmp: directory arguments

- bin/grep
* With -f option grep initially reads PATFILE, which contains one search pattern per line
* Following the previous commit, avoid opening PATFILE if the supplied argument is a directory
* In this case grep will terminate because we have no valid patterns to search based on
> grep: directory argument to -f

- bin/install
* This version of install does not raise an error if the destination argument is missing
* In install_files() the last element of ARGV is taken to be the destination; this is not quite correct if only one element is given
* When [original] ARGV=0 (install), usage is printed and install_files() is never called
* When ARGV=1 (install src), we don't know where to copy the file to
* When ARGV=2 (install src dst), the destination can be a directory or the name of the new file
* When ARGV>2 (install src1 src2... dst), multiple files are copied with their original name, and the final argument must be a directory
> install: raise error for no destination arg

- bin/hexdump
* For better compatibility with GNU and OpenBSD versions of hexdump, print a line at end of input with the final offset
* This happens for both canonical hex and -c mode
* This behaviour is already supported in our version of od command too
* Since the final line of input dumped might be <16 bytes, this summary line makes it trivial to see the total number
> hexdump: print offset at end of input

- bin/ed
* This version of ed will open only one file; this could be '-' for stdin
* edEdit() gets a path from $args[0] but we have this strange while-loop with an incorrect regex
* On the surface, the loop sets $SuppressCounts flag for stdin
* The loop also prevents special filename '-' from being assigned to $args[0], so that edEdit() works correctly
* Kill the loop because only one file can be opened, and replace regex
* ed now agrees to open my file named very-important
> ed refuses to open filename with a dash

- bin/split
* Print usage & exit for unknown options; previously getopts() return value was not checked --- perl split -X
* Follow GNU split: fatal error if extra args are given following filename and prefix --- perl split file.txt prefix extra
* Follow GNU split: fatal error if specified filename is a directory --- perl split .
* Fix a bug where prefix of "0" would not be allowed because of true-value check --- perl split -l 1 file.txt 0
> split: improve argument handling

- bin/ed
* Saving the buffer is useful at least for Unix-like systems
* Internal commands, e.g. "d" (edDelete), set $NeedToSave to indicate the buffer has changed
* No need to save the buffer if it was not modified since the input file was loaded
* The filename ed.hup is used by GNU ed and OpenBSD ed for the saved buffer
> ed: save buffer on hang-up signal

- bin/split
* Standard split has a mode where it reads from stdin, e.g. connected to a pipe on unix
* Currently this fails because open() doesn't accept the '-' argument
* Similar to what was done in od command, avoid calling open() if we run in stdin mode
* I tested this on my system with "dmesg | perl split -l 50"; split dmesg output into 50-line chunks using the default prefix of 'x'
> split: support stdin

- bin/install
* As previously done in mkdir command, replace custom argument parsing code with getopts()
* Quick test1: mkdir dir; perl install -m600 file1 dir/newname
* Quick test2: perl install -D file2 file3 dir/ # default mode of 0755 on unix
* Small quirk: I decided to convert $Debug into a flag, i.e. -D can't be given multiple times to increment $Debug
> install: switch to Getopt::Std

- bin/rm
* When I compare rm with and without -r, rmdir() appears to be called without -r
* I run... mkdir dir0; touch dir0/file0; perl rm dir0 # rmdir() fails becuse dir0 is not empty
* Standard rm should not remove a directory without the -r flag
* GNU rm and OpenBSD rm print a warning to stderr to indicate the directory argument is being ignored; follow this
* Global variable $arg is unused
> rm: ignore directory arg unless -r is set

- bin/od
* The input loop reads 16 bytes which are formatted as one line of output
* Move the formatting determination out of the loop because the options are only set once
* Introduce $fmt, referring to the formatter sub we need
* Calling formatter effectively sets @arr and $strfmt, both of which are passed to printf()
> od: simplify input loop

- bin/rm
* Exit code 1 indicates an error occurred when processing one or more arguments
* An error processing one argument doesn't prevent the next argument from processing
* Flag error (printing $! if appropriate) for these cases:
1) expected file, got directory
2) rmdir() failed on a directory (in -r mode)
3) opendir() failed (in -r mode), e.g. permission denied
4) unlink() failed, e.g. file does not exist
5) expected an argument, got zero
* closedir() isn't needed if opendir() failed
* While here remove -P flag for "wiping" a file
1) not part of standard rm command
2) implementation assumes writing over a file in place will effectively wipe content on disk
3) implementation assumes the file being wiped can fit in memory (creates a string the same size as file)
4) physical destruction is …
> rm: exit code 1 on error

- MANIFEST
- bin/unlink
* unlink is a trivial rm that processes a single file argument and has no option for processing directories
* The command is provided by FreeBSD, DragonFlyBSD and Linux
* We can provide it here too (mainly for the benefit of shell scripts)
> Add unlink command

- bin/od
* Standard od has -N which takes a numeric argument that is interpreted as decimal, hex or octal
* Initially add support for only decimal argument; this is the default interpretation in the standard
* -N 0 is allowed
* -j can be used with -N; -j bytes are skipped first before -N bytes are read
* Raise error for skipping past end of file with -j
* Avoid reading more bytes than -N by switching input loop to single byte read (prevents hanging waiting for input when -N <16 and reading from stdin connected to terminal)
* Tested against GNU od
> od: add -N option: limit input bytes

- bin/od
* Standard od allows "d", "o", "x" and "n" for radix value for Decimal, Octal, Hex and None
* I noticed that this version doesn't validate -A before passing it to printf()
* Offset is not supposed to be printed for -A n (including line prefix and for final summary line)
* The default value of -A is "o"
> od: validate radix argument to -A

- bin/ed
* Taken from old Todo comments
* One or more lines are moved to the line after the destination address (i.e. appended to destination)
* Address 0 is allowed for destination, moving lines to start of buffer (e.g. "10m0")
* Address 0 is not allowed for range selection (e.g. "0m1" and "0,0m1")
* When the lines being moved have a lower address than $dst, splicing @lines affects the offset $dst so insert copied lines before removing original ones
* Destination can be inferred as current line (e.g. move-to-current-line "1m")
* Source address can be inferred as current line (e.g move-current-line-to "m1")
* Tested against GNU ed
> ed: implement move command (m)

- bin/ed
* Generalise edEdit() to handle both copy-paste (t) and cut-paste (m) operations
* For 'm' it is not valid for destination address to be within source address range
* 'm' by itself means move current line to same address (do nothing)
* For 't' it is valid to copy a range into the middle of itself
* 't' by itself means duplicate current line (common usage)
> ed: implement t command (copy)

- bin/ed
* For compatibility with GNU ed and OpenBSD ed, immediately print filename and $! on stderr if open() failed, then save a simpler error message for "h"
* edEdit() opens for reading; edWrite() opens for writing/appending
> ed: consistently handle open() failure

- bin/od
* I made a test file with bytes from 0-255
* I ran "perl od -c tst" and saw warnings: Wide character in printf at od line 174.
* Standard od does not attempt to print non-printable ascii characters; instead, the character is printed as 3 octal digits
* If a c-escape is available for a non-printable character, use that instead
* unpack format should be "C" not "c" to treat characters as unsigned
* The warning appears to be present in older commits, so I guess I didn't break this recently
> od: -c flag versus non-printable characters

- bin/ed
* Having strict is desirable for maintainability, and many commands in this project already do this
* Delete unreachable code: out-of-order address check happens before calling command-specific functions, e.g. edPrint()
* Delete unused variable $NumLines in edSubstitute()
* Global variables are not being renamed, but tidy some of their comments
* Standard ed allows -s to silence the byte counts, but this version doesn't have it yet
> ed: strict.pm

- bin/ed
* GNU ed assumes -s if started with empty buffer
* GNU ed -s also silences diagnostic messages
* For now add -s here only to silence the byte counts
> ed: -s option for quieter operation

- bin/ed
* Initial implementation of edJoin() didn't allow 1-address ("1j") or 0-address ("j") variants, only 2-address ("1,2j")
* Follow GNU ed and treat 1-address join as nop (does not raise an error or mark buffer as modified)
* Single line ranges were already treated as nop, e.g. "1,1j"
* For bare "j", join current line with subsequent line (error if current line is the final line)
* j command doesn't allow extra arguments, only addresses
* Also, edPrint() and edJoin() should not accept the special address 0 (accepted by some ed commands)
> ed: join command (j) compatibility

- bin/ed
* Standard ed requires a space between "e" command and filename argument
* This version incorrectly interprets "echo" as "e cho", i.e. load file cho
* I also observed that "fun" is interpreted as "f un", but f command also requires a space
* Same with "w" and "W" commands (also expecting a filename argument)
* $fields[0] contains "echo" as entered; characters after 1st are called "command suffix"
* $fields[0] may contains a space, so only use characters before a space
* Also guard for invalid address 0 in edDelete (0 has no special meaning for "d" command)
> ed: command argument validation

- bin/ed
* This feature was mentioned in a Todo comment
* "l is a variant of the "p" (print) command so handle this in edPrint()
* Non-printable characters are printed as "\" followed by three octal digits, with no extra space on output
* Some common c-escapes are printed except for \n
* GNU ed and OpenBSD ed don't print the c-escape \0 but display \000 instead
* Extra1: Make the if-elsif block treat $command consistently by using eq
* Extra2: bump version
> ed: add list (l) command

- bin/ed
* The r command reads a file, appending its content into the existing buffer
* This is different to e and E which effectively erase the buffer when loading a new file
* r, e and E are all handled by edEdit()
* Test case: start ed with empty buffer then run "r file"
* Problem: the 1st line of file is lost and I get a "newline appended" warning
* When I debug this, $maxline == adrs[0] == 0
* The code which handles address zero should be executed, instead of the code for appending-to-end-of-buffer
> ed: edge case for "r file" usage

- bin/rev
- t/rev/rev.t
* Argument parsing in rev treated "?" as an indication to print usage, but this is not standard behaviour
* GNU rev and OpenBSD rev accept a file called "?" and we could accept it here
* I tested it with: echo hello > \? && perl rev \?
> rev: accept "?" as a file

- bin/ed
* Command suffix was already saved into $args[0] so inventing $commandsuf was a bad idea (remove it)
* Detect whitespace after $command character correctly by making it a capture variable in command regex
* "w" command has 3 different usages so handle them all correctly
* usage1: no address (w filename): write entire buffer to file
* usage2: one address: (123w filename): write single line from buffer to file
* usage3: address range: (12,13w filename): write only the lines in inclusive range to file
* style: declare filehandle as a "my" variable in edWrite()
> ed: fix range-specific write

- bin/ed
* I noticed that the recently added edJoin() didn't calculate a new $maxline...oops
* Then I realised $maxline is a function of @lines 
* Add maxline(), returning an index based on @lines; now we can retire $maxline
* The code is simpler when we don't need to calculate new $maxline values
* When reading data in, use scalar(@tmplines) instead of incrementing $tmp_maxline
* In edEdit(), $chars should count the newline appended to the last line of buffer (if newline was missing)
* When testing I typed .= a lot to verify the current line was updated correctly
> ed: remove global variable $maxline

- bin/ed
* edJoin() covers the 'j' command; edMove() covers the 'm' and 't' commands
* 'j' joins ones or more lines into a single destination line
* Current line address should be updated for 'j' to the destination address
* e.g. "5,7j" joins lines 6 & 7 to the end of 5, then sets current line to 5 (6 & 7 might no longer be valid addresses)
* 'm' and 't' moves/copies lines to one after the destination address
* Current line address should be updated for 'm' and 't' to the last line moved/copied
* e.g. "7,8m3" moves lines 7 & 8 to line 3+1, then sets the current line to 5 (i.e. the final line being moved)
* Tested against GNU ed
> ed: fix CurrentLine for commands j,m,t

- bin/fold
* Match GNU fold: If an argument can't be opened, proceed to the next argument instead of exiting
* When arguments are finished, exit with error code if we failed for one or more argument
* Avoid calling open() if argument is a directory
* Fix handling of special filename '-' (for both "fold -" and bare "fold")
* Align usage string with SYNOPSIS: file argument is optional
* Prefix warning messages with program name
> fold: continue on error

- bin/ed
* Write & quit: "wq f1" is a shortcut for "w f1" then "q"
* "Wq" also works in GNU ed, and will work here because W/w are handled in edWrite()
* "wqq" is not allowed because the command suffix is only one character
* digits are not allowed for suffix: "2,3m 1" can be written as "2,3m1", where 1 is the command argument not the suffix
* Instead of calling edQuit(), exit directly in edWrite() as we know the buffer was written
* Within edParse() only allow command suffix for W/w commands, for now
* I tested "wq" with and without a filename argument
* "1,2wqFILE" is still not accepted; FILE needs a space
* Invalid commands (e.g. "qq" and "fq file") are still rejected
> ed: add wq shortcut

- bin/nl
* argument to -w must be a positive int (may be written with '+' prefix)
* previously -w 0 was allowed, but follow GNU nl and raise error
* argument to -v must be a signed int (may be written with a '+' or '-' prefix)
* previously -v0 would incorrectly count from 1 instead of 0
* exit successfully when printing version (option -V)
* update SYNOPSIS & usage string to indicate multiple file arguments are accepted
* pod: move command options from SYNOPSIS to OPTIONS
> nl: validate numeric options

- bin/head
* No need to validate $count if the default value is used
* Raise an error for -n 0
* Reject directory arguments
* Proceed to next argument if an argument failed to process; exit with failure code when arguments are done
* compat1: print empty line before title line of next file (except for 1st file)
* compat2: don't print a space afer "<==" in title line
> head versus directories

- bin/banner
* Remove copyright comment from top of file which is already present in POD
* Remove undocumented -h option; usage is still printed
* Options -d and -t were mentioned incorrectly in a comment (usage string and SYNOPSIS only had -w)
* Update SYNOPSIS and usage to reflect that the message string is optional (user is prompted for a message)
* Immediate exit if character is not found in lookup table
* MAXMSG constant is unused
> banner: clarify usage

- bin/paste
* "paste -" should behave the same as bare "paste"
* Follow OpenBSD paste: fatal error if one file argument cannot be opened (and for directory arguments)
* Now print error string $! if open() fails
* My expected usage works, ls output in 3 columns: ls -1F | perl paste - - -
* The script works on my system with regular "use strict"
* Small POD changes
* Bump version
> paste: '-' is stdin

- bin/arithmetic
* Allow arithmetic to be terminated by either interrupt (ctrl+c) or end-of-file (ctrl+d)
* Previously eof was ignored
* Refer to C code [1]: fgets() returns NULL at end of file, causing final report to be printed
* Also the C comment: Keep looping until the correct answer is given, or until EOF or interrupt is typed
* Update POD to mention end-of-file
* Style: at end of 20 questions, call report() directly instead of via signal handler
1. https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/games/arithmetic/arithmetic.c
> arithmetic: terminate on end-of-file

- bin/paste
* I noticed unknown options were silently ignored (e.g. "perl paste -X -"), but GNU and OpenBSD versions raise a fatal error 
* Replace custom options parsers with getopts() as done in other scripts
* style: I decided to remove variable $dash_ess
> paste: reject unknown options

- bin/bc
* Previous bignum code was not correct because digit information was lost before conversion to BigFloat object
* Digits after the decimal point didn't seem to be affected though
* This version works better for me
bc -y # old
123384888888888888888888888888888888888888888888888812 123384888888889000000000000000000000000000000000000000
1.234448888888888888888888888888888888888888888888887 1.234448888888888888888888888888888888888888888888887
bc -y # new
123384888888888888888888888888888888888888888888888812 123384888888888888888888888888888888888888888888888812
> bc: integer precision problem with -b mode

- bin/bcd
* Originally I didn't translate decode()
* Lightly tested for both long (-l) and short (default) mode using output from encode
> bcd: add -d option for decode

- bin/diff
* OpenBSD diff and GNU diff have options for comparing two directories; add POD text to explain this version doesn't support it
* Add a common usage, where arg1 is a file and arg2 is a directory (arg2 is treated as a path prefix to arg1)
* pod2text ignores $0 which appeared in SYNOPSIS
* Add a hint that -f output is not compatible with ed
* Be helpful and print usage string for unexpected options
* Also explicitly print a warning about wrong number of arguments
> diff: support file2 as directory

- bin/cal
* "cal -y" wastes space, printing one month at a time vertically
* Output three months at a time, as done in OpenBSD cal (this fits into 80 columns for old terminals)
* Convert print_month() into fmt_month(), returning a string
* In -y mode the year appears once in a header line, not next to a month name
* Future direction: possibly reduce lines of code by returning a list of strings in fmt_month()
> cal: improve formatting for -y mode

- bin/diff
* Standard diff command allows either file argument to be a directory
* The previous commit assumed only file2 can be a directory
* With this patch, "perl diff /tmp a" compares /tmp/a with ./a
* As before, "perl diff a /tmp" compares ./a with /tmp/a
* Wording for POD is based on the OpenBSD diff manual
> diff: support file1 or file2 as directory

- bin/nl
* We already support multiple file arguments, similar to GNU nl ('-' is stdin)
* Follow GNU nl further: exit with error code if a file argument fails to process
* Previously no error was printed for a directory argument
* Follow OpenBSD nl: allow -i0 (GNU nl does not allow it and -i0 was previously treated as -i1)
* Argument to -i is a signed int and may be written with '+' or '-' prefix
* We already support negative -i value (similar to OpenBSD nl) but GNU nl does not allow it
* Bump version
> nl: exit(1) for bad file argument

- bin/rmdir
* Even in -p mode, GNU rmdir lists errors, but we didn't print them
* Because of truth check, we didn't remove the final 0/ component in "rmdir -p 0/0/0"
* 1/100 directory arguments might fail to remove and we didn't list the name in the error message
* Which files failed?
rmdir: Not a directory
rmdir: Not a directory
rmdir: No such file or directory
* Patched version works for "-p 0/0/0" and prints a warning if one directory wasn't empty
* POD text mentioning "head" was possibly copied from another file
> rmdir: include filename in warning

- bin/ls
* GNU ls and OpenBSD ls set the -a flag if -f is set
* Standards document also mentions -f "shall turn on -a" [1]
* Print usage and exit for unknown options instead of ignoring them
* Remove ancient commented code
* POD: add missing text in ENVIRONMENT section to make podchecker happy
* POD: mention that -f implies -a
1. https://pubs.opengroup.org/onlinepubs/009696899/utilities/ls.html
> ls: standard meaning of -f option

- bin/which
* Option -a was not mentioned in usage string so add it
* Option -a was not removed from ARGV, so "which -a ls" would search for "-a" and "ls"
* The handwritten option parser could not handle "which -a -- ls" and would search for "-a", "--" and "ls"
* Switching to getopts() avoids this problem
* Print usage and exit for unknown options instead of ignoring them
* Remove GNU-specific options --help and --version; print version in usage string as done in cat command
* Remove a level of code nesting because loop will never enter if PATHEXT list is empty 
* Bump version
> which: fix option parsing

- bin/ed
* The commands a,c,d,i,P,h,H,q,Q do not allow an argument
* The 'c' command is implemented as edDelete() then edInsert()
* edInsert() already raised an error for passing an argument, but edDelete() did not
* As a result entering "1c0" incorrectly deletes line 1, then prints a warning from edInsert()
* Handling unwanted argument in edDelete() wasn't enough
* We need to avoid calling edInsert(), so return a new success value from edDelete()
* Also raise error if commands 'P', 'h' and 'H' are passed an argument, as done in GNU ed
* Also raise error if 'h', 'H', 'q' and 'Q' and 'P' are given a line address
Now blocked:
1q
1,2q
1Q
1,2Q
q1
Q1
c1
d1
1P
1,2P
P1
1h
1,2h
h1
1H
1,2H
H1
> ed: fix handling of bad command 1c0

- bin/basename
* Despite what the pod text said, this version was not compatible with the OpenBSD version
* Paths ending in one or more '/' were not handled correctly
* Standard basename treats consecutive slashes as one, and ignores training slash
* fileparse() doesn't understand trailing slash so strip it first
* Basename of empty string is empty string; print newline to match other versions
* Basename of '/ is '/'
* Bump version number
/ -> /
/// -> /
a -> a
a/b -> b
a/b/ -> b
a/b/////////c/// -> c
> basename: '/' handling is broken

- bin/expr
* For expr the exit code of 1 is interpreted as: the expression was executed successfully and returned a zero or empty result
* Exit code 2 is reserved for syntax error, division by zero and other bad things which meant the result couldn't be determined
* Extra: my vim got a bit confused with semicolon after __END__
> expr: exit(2) for missing argument

- bin/tee
* This version of tee has a non-standard option -n to disable writing output to stdout
* When using -n without any file arguments, tee reads its input and does nothing
* Reading input has no effect so raise an error instead
* I'm happy to remove the -n option if you prefer
> tee: expectation for -n option

- bin/sort
* In case the user typed the wrong option it is better to print usage and exit
* This matches the behaviour of GNU sort and OpenBSD sort
> sort: don't continue for unknown options

- MANIFEST
- bin/seq
* Import seq command similar to OpenBSD version
* Numbers are terminated by string -s or default of "\n"
* Sequence starts at 1 by default
* Count up or down based on comparing first and last numbers
* Positive numbers support '+' prefix
* Example1: 1arg usage: count down by default -1: seq -s ' ' -2
1 0 -1 -2
* Example2: 2arg usage: count up by default 1: seq -s ' ' 4 7
4 5 6 7
* Example3: 3arg usage: count up with incr=5: seq -s ' ' 0 5 20
0 5 10 15 20
* Example4: 2arg usage: fraction step: perl seq -s ' ' -1.5 0.25 1.5
-1.5 -1.25 -1 -0.75 -0.5 -0.25 0 0.25 0.5 0.75 1 1.25 1.5
* Example5: custom printf format with fraction step: perl seq -f '%e' 1.2 0.345345 3 
1.200000e+00
1.545345e+00
1.890690e+00
2.236035e+00
2.581380e+00
2.926725e+00
> seq command proposal

- bin/colrm
* Zero was allowed for column number, but it's not valid because we count from one---raise error like BSD version does
* Also, colrm allows negative value arguments; add validation to avoid this
* For ARGV==1, when arg1 > column count, output incorrectly gets another newline appended because the substring is the full string including newline
* For ARGV==2, "colrm 1 1" is supposed to remove only the 1st column but it did nothing
* Also, the substring could be outside the string for "colrm 1000 1000" because input was not validated
> colrm: add validation

- bin/tac
* tac successfully reads from stdin when run with no file argument
* GNU tac accepts file argument of '-' for stdin but ppt version does not
* I get an error when reading from a file: perl tac tac
Bad read on [ARRAY(0x1a04270)]:  at tac line 197.
IO::Tac::get_lines(IO::Tac=GLOB(0x19ef4b8)) called at tac line 150
IO::Tac::READLINE(IO::Tac=GLOB(0x19ef4b8)) called at tac line 43
* When debugging this I found that $tell is set to zero, then in the tell() perldoc manual it explains that tell() doesn't work with sysopen()
* Calling sysread with size of zero was invalid
* Replacing tell() with sysseek() call fixes the problem on my system
> tac fails to read a file

- bin/cal
* Simplify options parsing 
* Previously -jy could be grouped, but not written as "-j -y" because options were expected to all be in $ARGV[0]
* num_args does not count options
* num_args == 0 means $month and $year are dynamically selected (month is not used if -y is set)
* num_args == 1 means $month is not used and $year comes from args
* num_args == 2 means $month and $year are both used and come from args (not compatible with -y)
* Remove non-standard -? option; usage is still printed
* Put POD after __END__
* Remove POD text referring to -n option which doesn't exist
> cal: permit -j -y and -jy

- bin/chgrp
* Which files failed?
perl chgrp root *
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
chgrp: Operation not permitted
* Successful files don't print anything
* Follow GNU chgrp and include filename in the error message
* Print "usage:" before usage
* Call usage() directly instead of die "Usage"
> chgrp: add filename argument in errors

- bin/env
* If exec() fails print the command name and $!
* Previously the exit code would indicate failure but GNU env also prints an error
* While here, option -i can be handled without a loop
* Example error: perl env ./not.here 1 2
env: failed to exec './not.here': No such file or directory
> env: print exec() failure message

- bin/wc
* Exit with failure code in usage()
* Tweak usage string: indicate zero or more files with [file...]
* Follow GNU wc: continue processing next argument if open() fails
* Delete old commented code; probably incorrect
* $opt doesn't need to be global because it is only used in the custom "Mac" code block
* Print warning for directory arguments and skip them
> wc: continue if open() fails

- bin/pr
* Unused import Data::Dumper
* Prefix usage string with the word "usage"
* Same +page typo appeared in usage string and SYNOPSIS
* Avoid calling open() and raise error if argument is a directory
* Include $! in the error string if open() fails
> pr: don't accept directory arg

- bin/xargs
* Standard xargs does not terminate for all error exit codes [1], only for exit code 255 returned by the command
* system() returns -1 if the command couldn't be started, so also treat that as a fatal error
* With patch applied, match the behaviour of GNU xargs for the following cases
* case1: don't terminate ls-loop if first file wasn't found
echo a b | perl xargs -n 1 ls -1
a
ls: cannot access 'b': No such file or directory
* case2: terminate xargs for command l which doesn't exist, system() returned -1
echo a | perl xargs l
xargs: l: No such file or directory
* case3: terminate xargs for command returning 255 (dummy example)
echo a | perl xargs perl -e'exit 255'
xargs: perl: exited with status 255
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/xargs.html
> xargs: standard loop termination

- bin/strings
* Option -t expects a single letter, but this version accepted stupid things like -t bedding
* $offset_format is only used if $opt_t is set; default usage does not print offset
* Directory arguments were silently failing; now print an error message for them
> strings: better validation

- bin/env
* Standard env command does not support -u NAME for unsetting a variable [1]
* OpenBSD env doesn't implement -u, but NetBSD and GNU do
* GNU env prevents argument to -u from having a '=' character
* NetBSD does the same, and its manual explicitly mentions this restriction
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/env.html
> env: validate -u argument

- bin/which
* The following output is incorrect because the results all refer to directories
$ perl which . .. /
/usr/local/sbin/.
/usr/local/sbin/..
/usr/local/sbin//
* The command "which" is supposed to find files available to execute, not directories
* Resolve this by adding explicit directory check before checking "-x $path"
* Style: declare path variables to make code simpler to read
> which returns directory paths

- bin/dc
* When no file argument is given, stdin is read
* When a file argument is given, run it and exit
* I noticed that after running "perl dc test.dc", dc would hang waiting for stdin
> dc: stop reading stdin too much

- bin/bc
* perl bc evaluates false "if" as an expression and returns 0, not "null"
>>> if (0 == 1) { a = 1; } 
0
* This doesn't happen if the condition is true
* I observe that if $res==0, the executed statement result ($val) is printed
* In IF-statement code, $val is returned by exec_stmt() if the condition is true
* If the condition is false, $val defaults to zero but this causes an unwanted print later
* Changing the default to undef works for my simple test.bc script
* Reading the code, I see other examples of undef being pushed into ope_stack, so I think this will not corrupt the state
* Also remove unused variable $n found by perlcritic
* Does this look ok?
> bc: don't print 0 for a false if-condition

- bin/tac
* The SYNOPSIS is helpful, but ideally we want to print a usage string and exit for invalid options
* Previously unknown options (e.g. -a) would print a warning and be ignored (inconsistent with standard tac)
* The END block can't be removed yet because there are still callers of confess() that were not updated
* Bump version
> tac: add usage

- bin/sum
* ppt had no way of generating md5 sums
* Following NetBSD sum, add an -a option for checksum algorithm
* Keep the current meaning of -o [1-2] for old1 and old2
* Follow NetBSD and select crc algorithm using -a crc, not -o 0
* Move logic for selecting correct algorithm out of argument loop
* update POD
* md5 output tested against md5sum command on my system
> sum: add md5 support

- bin/tac
* Previously tac would exit if one file argument could not be opened
* Also, the filename was not reported in the error message so it was unclear which argument was at fault
* If zero files are opened successfully, IO::Tac->new() returns undef so exit immediately
* Now print a warning for each file that can't be opened, then continue to next argument
* Avoid "bad read" error in by checking if argument is a directory before calling sysopen()
* This behaviour follows cat, and GNU tac
> tac: continue on error

- bin/look
* Delete some code by switching to getopts()
* Bad usage case 1: look requires a pattern argument to search for, but this version allowed no pattern
$ perl look | wc -l
101924
* Bad usage case 2: look requires zero or one file argument, but this version didn't raise error for multiple files
* Update usage string and SYNOPSIS
* Skip directories in FILE loop
> look: reject multiple file arguments

- bin/sum
* SHA family of algorithms are supported in NetBSD sum
* sha_all() takes advantage of algorithm name being saved in $opt{'a'}
* Digest::SHA interface is consistent with Digest::MD5, i.e. addfile() accepts a filehandle
* Update usage string
> sum: add sha1/sha256/sha384/sha512

- bin/cal
* When printing month-boxes horizontally I wasn't happy with having to split each month-box string
* Make fmt_month() return a list of lines instead
* This makes it simpler to combine month-boxes line by line
* Some common code moves into print_title()
> cal: avoid split() when formatting a whole year

- bin/cal
* Retire custom get_flags() in favour of getopts()
* Exit code 1 in display_help() to indicate something was wrong with the arguments
* Style: &display_help() -> display_help()
> cal: switch to getopts()

- bin/split
* Remove code for handling $opt{'?'} since this is not supported in getopt
* Update POD
* No intended functional change; -? would still print a warning + usage string
> split: remnants of -?

- bin/mail
* When issuing quit command (q) I was seeing the error: Failed to write to /home/ranch/mbox: No such file or directory
* Something was wrong because the file did exist
* The error message printed $self->file but the path opened was $of, which had a prepended ">"
* Possibly this is a hangover from previously switching to 3-argument form of open()
> mail can't write to mbox

- bin/pom
* Two constants were unused: MLNODE, SYNMONTH
* atan() and tan() are provided by Math::Trig
* floor() and fmod() are provided by POSIX
* floor() accepts negative arguments so I noticed FNITG() can be replaced by floor(), and sign() can be removed
* rad2deg() and deg2rad() are provided by Math::Trig (switching over means PI constant can be removed)
> pom: common library functions

- bin/id
* Problem1: id reports that my root user doesn't exist because the uid is zero
* This is because $uid is undef if getpwnam() fails, but this was treated the same as 0
$ id root
uid=0(root) gid=0(root) groups=0(root),117(lpadmin)
$ perl id root
id: root: No such user
* Problem2: id reports that 'root77' user exists when it does not
* This is because a non-numeric parameter was passed to getpwuid()
$ perl id root77
uid=0(root) gid=0(root) groups=117(lpadmin),0(root)
> id: uid 0 is valid

- bin/bc
* bc accepts file argument 0 even if it does not exist
* It appears the code was incorrectly doing a truth test on the argument list, resulting in stdin being read
* The same problem existed when selecting the next element from @file_list
* Patched version raises an error that "0" is not found
> bc: filename 0 is not special

- bin/file
* When running "perl file not.exist", I was getting a permission denied error
* Resolve this by checking for failure of stat() via return value
* For a file that I don't have permission to read, FileHandle->new() will fail and $! will be printed correctly
> file: incorrect error message

- bin/tail
* Numbers can optionally be given with '-' or '+' prefix
* The number validation function allows numbers with leading garbage (regex match was only on end of string)
* These values were accepted: aaa1 +aaa1 -aaa1
* We can pass a helpful error message to usage() to indicate which argument was rejected
* Style: indent check_number()
* Tested this by passing numbers to -n option
> tail: check_number() too forgiving

- bin/date
* Entry point is run() and only one argument is passed (into $args)
* Remove unused variable $time
* Remove commented debug code (value can be printed from debugger)
* Style: declare $format and assign initial value in one hit
> date: unused var

- bin/banner
* banner has only one option: -w NUMBER
* Numbers above zero are accepted
* Slightly less code to maintain if this uses common Getopt library
> banner: switch to getopt

- bin/xargs
* The -0 option to xargs is provided by FreeBSD, NetBSD, OpenBSD and GNU
* Tested against the output of "find . -print0"
* While here add strict (code was already compliant)
* It would be good to add a POD manual here later
> xargs: add -0 flag

- bin/strings
* Zero or a negative number doesn't make sense for the -n option so raise an error
* The shortest valid string to be printed is 1 character, but the default -n4 is more useful
* Previously -n0 was incorrectly interpreted as -n4 and -n-100 was kind of interpreted as -n0 (empty strings were printed)
* Print program name in error if open() failed (matches GNU version)
* Sprinke "my" so strict will work
> strings: validation + strict

- bin/tee
* Sometimes tee fails to open a file for writing because of a confusing filename guard regex
echo yo | perl tee  . '|o|'
tee: cannot open .: Is a directory
Unknown open() mode '' at tee line 45.
* '|o|' is a valid filename on my system if it is quoted like this
* GNU tee doesn't complain about this usage (aside from complaining about the directory argument '.')
* $mode is already determined based on -a option
* Making decisions based on the filename seems incorrect so just simplify open()
> tee: null mode param passed to open()

- bin/nl
* The usage text in POD was an exact copy of $usage, except the POD version had a typo
* Usage was printed for 2 cases: bad option and bad 'type' value to -b, -h etc
* Print a warning with the bad -b value to help the user know what went wrong
* The duplicated text can be avoided by switching to Pod::Usage (already used in this package by some other scripts)
> nl: Pod::Usage

- bin/wc
* This version of wc was being helpful and printing the basename of each file argument beside each count
* This creates the problem that output is ambiguous when counting lines of files of the same name in different directories
* Issue was noticed when testing against GNU wc
```
perl wc -l old/a new/a | sort -n 
183 new/a
3132 old/a
3315 total
```
> wc: report file arguments as provided

- bin/tail
* Behave like head; print a warning if a file argument can't be opened then proceed to the next argument
* Exit with failure code if an argument failed to open
* Issue noticed when testing against GNU tail
> tail: continue on error

- bin/tail
* I wrote a test harness for tail-zero-lines...
for opt in '-0' '+0' '-n 0' '-n -0' '-n +0' ; do echo "tail $opt"; perl tail $opt in; done;
* Some cases result in the error: The number cannot be null
* "tail -n 0" is accepted but "tail -n +0" and "tail -n -0" are not
* When debugging I found that check_number() is not called for "tail -n 0" (but it should be)
* check_number() was only called if $opt_b/$opt_c/$opt_n were true
* NB: GNU tail allows -n 0, but raising error in this version is consistent internally, and with "head -n 0"
> tail -n: 0 versus +0 versus -0

- bin/cut
* Print usage and exit with error code if user typed an incorrect option
* If getopts() succeeded but one of -b/-c/-f is not provided, print a descriptive error before usage()
> cut: error for unknown options

- bin/tail
* The -f mode of tail calls tail_f(), passing file & directory arguments as separate params
* By default handle_args() loops over Files list, not Dirs list, so directory arguments were silently ignored
* Make the default case follow GNU tail: print a warning for each directory argument, and exit with error code when arguments are done
> tail: warn for directory args

- bin/cut
* cut's -f value can be a comma-separated list of field numbers starting from 1
* The following is valid for selecting x+z: echo 'x:y:z' | perl cut -d ':' -f 1,3
* GNU cut and OpenBSD cut reject 0 as part of a field list so do the same here
* Now -f 0,1 and -f 1,0 will raise an error as expected
* Same treatment for -b 0,1 (bytes also count from 1)
* Style: replace 2 dies with warn+exit
> cut: -b 0 and -f 0 are invalid

- bin/shar
* shar did not work on my system:  Can't locate getopts.pl in @INC (@INC contains: /usr/local/lib/perl5/site_perl/5.34.1/armv7l-linux ...)
* The original intent of getopt was to raise error for any options (e.g. -x), so convert to Getopt::Std
* Add strict
* Tested this by creating archive (perl shar ar apply > new.shar) then extracting (sh new.shar)
> shar: dependency error

- bin/shar
* Some versions of shar can archive a directory but this one can't
* Avoid adding invalid entries into archives for directories; instead print a warning for each directory argument
* Following OpenBSD shar, show "x - $filename" when extracting files
* pod: mention that the archive is written to standard output
> shar: ignore directories

- bin/comm
* Add strict as done in other scripts
* COL[1] is the first element; COL[0] is a placeholder
* For my sample input files, the output is identical compared to previous version
* GNU comm prints a warning if input files are not sorted, but this version doesn't
> comm: use strict

- bin/cmp
* Fix exit code for file open failure
* style1: access $volume numerically
* style2: sprinkle more exit code constants
* EX_USAGE could possibly be merged into EX_FAILURE or given another value, but I left it alone
> cmp: exit(2) on failure

- bin/shar
* DragonFly, FreeBSD, NetBSD and OpenBSD manual pages share the example of using the find command to provide the arguments to shar
* The output of find lists a directory before the files it contains
* Add support for this usage by writing mkdir command on output if an argument is a directory
* mkdir still runs for the "." directory in the following example but this is consistent with the OpenBSD version
* Print directory name with "/" suffix when extracting
* Update POD
perl ~/ppt/shar $(find . -print) > ~/new.shar
cd; sh new.shar
x - ./
x - ./b/
x - ./b/false
x - ./apply
> shar: support directory args from find

- bin/diff
* The -U option accepts the number -1 but perl dies
perl diff -U -1  A B 
--- A	Sat Oct 28 11:49:12 2023
+++ B	Sat Oct 28 11:49:24 2023
@@ -3104,-1 +3104,-1 @@
Modification of non-creatable array value attempted, subscript -1 at diff line 383.
* For -U 0, output matches GNU diff on my Linux system  (OpenBSD diff also accepts -U 0)
* "-U hello" is interpreted as -U 0 but this should be an error
* Looking at the option parser, -C and -U have the same problem
* Standards document doesn't mention -U, but has wording about -C value being a positive integer[1]
* Follow OpenBSD diff and allow -U 0, but raise error for negative values (same treatment for -C)
1. https://pubs.opengroup.org/onlinepubs/009604499/utilities/diff.html
> diff: validation for -U and -C

- bin/cmp
* Hex and decimal offsets are permitted for arguments skip1 and skip2
* eval() was being used but hex() is good enough
* hex() can handle the "0x" prefix so we don't need to strip it
> cmp: read hex input with hex()

- bin/cmp
* Standard cmp treats file argument '-' as standard input
* Add POD entry to mention this feature
* FILE1 and FILE2 become $fh1 and $fh2 respectively
* Validate number arguments skip1 and skip2 early, before accessing file arguments
* Perform stat() comparisons between files only if both files are regular
* STDIN doesn't support seek(), so implement "skip" with sysread() in this case
* Now I can do...
echo ello > C
echo hello | perl cmp C - 0 1
> cmp: support reading STDIN

- bin/rev
* OpenBSD rev and GNU rev agree that directory arguments are skipped and a warning is printed
* This version didn't print a warning so add one (new output below)
* Now include filename in error message when checking if read failed; $! after calling rev()
```
$ echo echo > e
$ perl rev . .. e
rev: '.' is a directory
rev: '..' is a directory
ohce
```
> rev: warning for directory args

- bin/uuencode
* This uuencode always writes to stdout
* When run with only 1 file argument, read stdin and write to stdout, copying file name into output header
* Reading stdin is broken because we attempt to open literal '-'
* We can't stat() stdin so the output header gets the default permission of 644
* It would be good to add some POD later to explain the usage
perl uuencode B
uuencode: WARNING: reading from standard input
begin 644 B
can't open -: No such file or directory at uuencode line 83.
> uuencode: make stdin work again

- bin/mail
* Use logic in File::Temp to avoid name collision for temporary file
* I tested this by loading a mailbox, selecting message 2 then "viewing" it...
perl mail # reads $HOME/mbox by default
2
v
...quit vi
q
* We don't need to set file with $tmbox->file(...) because new() already set it
* While here, remove useless debug message about entering "stuff" function
> mail: improve temp file selection

- bin/ed
* edDelete() has $NumLines (argument to splice) and $Numlines (unused)
* Found by perlcritic
> ed: unused variable

- bin/patch
* Do what is advertised in POD text
* The following are valid for patching file A from the diff read from stdin...
cat my.diff | perl patch A -
cat my.diff | perl patch A
* For both cases Pushback::TIEHANDLE() was passed a '-' parameter
> patch: patchfile can be read from stdin

- bin/join
* POD text mentions '-' can be used for standard input, but it didn't work
* Code already checks if file1 and file2 are both '-' (not accepted)
* Fail immediately if either file is a directory (join is only for files)
* If close() fails, print $! instead of $1 in error message
* Tested this on my system with the same file: cat A | perl join - A
> join: '-' for stdin

- bin/diff
* As with cmp, standard diff supports the file argument '-' as stdin
* F1 and F2 become $fh1 and $fh2 respectively
* The custom option parser needs to skip over '-'
* Now the following produce the same output on my system:
perl diff A B
cat A | perl diff - B
> diff: treat - as stdin

- bin/mkfifo
* I like to write -m 0 as a shortcut for no-permissions
* Because of truth check "-m 000" invoked get_mode() but "-m 0" did not
* The minimum is 1 digit for mode and -m 7 means 007, but get_mode() expected it always gets 3
* GNU and OpenBSD mkfifo commands accept -m 0, -m 7, -m 75, ...
* Delete commented code
> mkfifo: common -m usage

- bin/mail
* The default mbox file is $HOME/mbox but -f can set a different file
* A directory is no a valid mbox file so raise an error when first loading a mailbox, not when saving it (below)
* Defer to mailbox::load() for directory check, so we can catch same error for $ENV{MAIL} passed to Interactive()
* Print error description $! as a hint to the user if open() fails for the mbox
* While here, fix truth check which prevented the file '0' from being loaded (default mbox used instead)
```
perl mail -f .
Loading the mailfile .
Mail [0.02 Perl] [linux]
Invalid message number: 1
> q
Failed to write to .: Is a directory
```
> mail: forbid directory for -f FILE

- bin/printf
* Standard printf command doesn't deal with floating point numbers
* OpenBSD printf and GNU printf interpret hex number arguments, so printf can be used for hex-to-decimal conversion
* Support this here by scanning arg list and passing input conditionally to hex()
* Exit directly instead of through die()
```
/usr/bin/printf '[%8u]\n' 0xffff
[   65535]
```
> printf: support hex number arguments

- bin/fortune
* Calling sleep() is needed only for -w, so this makes the intent easier to follow
> fortune: simplify -w flag

- bin/mail
* Entering a message range including zero is correctly treated as an error (Ma==mail)
Me: perl mail
Me: 0-0
Ma: Invalid message specification, 0 (Should Not Happen) at mail line 478, <STDIN> line 1.
* Entering a message ID of zero directly does not raise an error
Me: 0
Ma: Message: 1
Ma:
Ma: Status: RO
Ma: 
Ma: Status: RO
* Message ID zero is invalid so we should raise an error here (OpenBSD mail raises an error for this)
* Why does 0 get translated magically to 1?
* Debugging shows messagex() is called with num=0 for input "0-0", and num=1 for input "0"
* parseargs() return $cmd="p 0" and arg1 list with only element of 1 (so parseargs is at fault)
* parse_msg_list() gets param of list=" 0" and strips spaces, then takes early return (current id was 1, explaining why 0 becomes 1)
* The …
> mail: raise error for message id 0

- bin/ls
* The ioctl number assumed for TIOCGWINSZ is non-portable and would only work by accident
* The ioctl() call fails on my system because it is invalid
* Perl Cookbook example has the exact hex constant and mentions it is not portable [1]
* It seems better to remove this construct until it can be replaced with something that works
1. https://www.oreilly.com/library/view/perl-cookbook/1565922433/ch04s19.html
> ls: retire invalid ioctl()

- bin/bc
* In interactive bc, calling an undefined function does not cause a fatal error but an error is printed
* YYERROR() is called in this situation, but it seems to break something
* It appears that input tokens past the end of current statement are eaten by YYERROR
* I observed this:
ME> x = hey(1) + 2
BC> No function hey() has been defined
ME> x
ME> x
BC> 0
ME> quit
* After the error bc ignores the first time I type x (but when I ask again it politely answers)
* Replacing YYERROR with "last INSTR" causes bc to jump past the final instruction in the current statement
* Instructions in the subsequent statement are not destroyed
* With this patch, the statement after the error is executed as I expect (this matches GNU bc)
ME> x = 5
BC> 5
ME> y = heh(6) + 7
BC> No function heh() has been …
> bc: runtime error eats too much input

- bin/mail
* Introduce main::vipath() to avoid duplicated access of $ENV{VISUAL}
* Catch failure to spawn VISUAL editor by checking system() return value
* Delete "print Dumper" statements which were silently failing (maybe ancient debug code)
* When re-opening tmpfile in edit mode, file should be in read mode not write mode
* editor::edit() is invoked by the 'm' command to write a new message, then the special ~v command loads the buffer in vi
* editor::edit() input loop is terminated by a line with only a '.'
* Add File::Temp, as done in main::visual()
> mail: duplicated VISUAL code

- bin/touch
* When file argument exists and is a directory, touch incorrectly decides it needs to call sysopen() to create a file
```
%mkdir dir1 
%perl touch dir1 
touch: dir1: Is a directory
```
* The problem appears to be the -f operator matching regular files and not directories
* Exists operator -e seems more correct; patched version updates timestamp on directory as expected...
```
%ls -ld old
drwxr-xr-x 2 hi hi 4096 Oct 19 22:18 old
%perl touch old
%ls -ld old
drwxr-xr-x 2 hi hi 4096 Nov 15 22:32 old
```
> touch: support directories

- bin/unexpand
* According to the standard it is valid for unexpand to be passed no file argument
* POD text mentions reading standard input is supported (SYNOPSIS also lists file as optional)
* Add OPTIONS section to POD and remove SYNOPSIS of expand
> unexpand: read stdin

- bin/expand
* POD text mentions that reading standard input is supported
* Behave like OpenBSD expand: stdin is implied if no files are given
* Remove POD text specific to unexpand; doesn't belong here
* Now the following are equivalent on my system...
cat ar | perl expand - | md5sum
cat ar | perl expand | md5sum
perl expand ar | md5sum
> expand: read stdin

- bin/comm
* Standard comm allows '-' for standard input, for one but not both file arguments[1]
* GNU comm and OpenBSD comm support '-' in this way (this is similar to diff and cmp which also compare files)
* Explicitly close file handles at end of processing
* While here, follow GNU comm and raise error if a file argument refers to a directory
1. https://pubs.opengroup.org/onlinepubs/7908799/xcu/comm.html
> comm: accept '-' for stdin

- bin/tar
* Adding die() for directory argument ensures tar doesn't exit with a success code
* Test command: perl tar -tf .
* Found when testing against GNU tar
> tar: raise error for directory argument to -f

- bin/expr
* Possibly strict was enabled in the past because it was commented out
* strict didn't seem to work without putting evaluate() arguments in parens
* Floating point arithmetic is not available in expr, so it seems a good candidate for 'use integer'
* Remove declaration of debug() because it wasn't used anywhere
> expr: re-enable strict

- bin/strings
* SYNOPSIS indicates file is optional, but when file is omitted strings does nothing
* On my Linux system, strings is from GNU binutils 2.35.2
* On OpenBSD, strings is from a much older version of binutils
* binutils strings reads from stdin if no file arguments are given
* Standards document for strings mentions that it "shall read from the standard input"[1]
* The argument '-' does not refer to stdin in this case
1. https://pubs.opengroup.org/onlinepubs/000095399/utilities/strings.html
> strings: read stdin by default

- bin/chgrp
* chgrp does not use getopt() but it had code to handle the special argument '--' which indicates the end of options
* The handling of '--' was incorrect because ARGV list is already shfted into $opt, but the non-option argument after '--' was shifted too
* With this patch I can do: perl chgrp -- user0 dir1/
* Found this when testing against GNU chgrp
* Later, switching chgrp to getopt() could be investigated
> chgrp: '--' option terminator

- bin/pr
* GNU pr and OpenBSD pr use getopt(), so I can write "pr -- -a" to input a file called "-a"
* This version treats -- as an invalid option, and prints usage
* Add -- to option parser for better compatibility; possibly in future it can switch over to regular getopt
* Remove unused variable @files; found by perlcritic
> pr: accept -- as end of options

- bin/col
* Raise an error for bad -l values instead of silently ignoring them
* Follow OpenBSD col and reject -l values less than 1
* style: move final statement $front=1 out of if-statements where it happens for both branches
* POD: spelling correction
> col: reject 0 value for -l

- bin/ln
* Print usage and exit if an invalid option was detected
* POD: clarify that option -s is not the default
* Replace link() closure with regular dolink() function
* Move usage string out of signal handler into regular usage() function
* Exit directly via exit() rather than through die(), as done in other scripts
* Bump version
> ln: fatal error for bad options

- bin/unexpand
* Introduce unexpand_line() which processes one line at at time
* Simpler usage() function which does not take any params
* Stop documenting the non-standard -h option; usage string is still printed for -h
> unexpand: don't slurp entire input file

- bin/expand
* The standards document for expand says a backspace character on input is copied to output and the index is decremented[1]
* GNU, OpenBSD and NetBSD versions follow this behaviour
* Perl expand doesn't copy backspace to output, and the index is decremented twice
* Perl unexpand copies backspace to output and decrements the index (we want to follow this)
1. https://pubs.opengroup.org/onlinepubs/007904975/utilities/expand.html
> expand: don't suppress backspace

- bin/spell
* Rewrite word file input loop with explicit close() and without tmp_words list
* Delete commented code
* Simpler usage() which doesn't take a parameter
* Test provides same output as previous version: pod2text bc | perl spell -b/usr/share/dict/words
Output I cherry-pick for no particular reason:
assigment
assignent
generats
> spell: dictionary input loop

- bin/date
* This version of date supports the non-standard %q specifier which is also supported by GNU date
* OpenBSD date supports a number of POSIX-extension specifiers, but does not have %q
* The value of %q is [1-4]
* Include %q in the POD (it was not mentioned)
* quarter() can be written with no conditions by dividing 12 by 3
> date: document %q feature

- bin/arithmetic
* Create a usage() function so we can call it instead of the magical die("Usage")
* Update regex for validating -r value (accepting integers 0 and above)
* The format of options is compatible with getopts() so switch over to it
* Now we can write -o/ and -r100, or with a space
* Bump version
> arithmetic: use getopts()

- bin/ed
* edEdit() handles the commands 'e', 'E' and 'r' ($InsertMode indicates 'r')
* "E filename" and "e filename" replace the entire buffer with the file; specifying an address is invalid
* "r" pastes a file into the current buffer; "r" can optionally have one or two addresses
* Two-address "r" just uses the 2nd address, i.e. "1,2r file" is the same as "2r file" (paste file after line 2)
* The old code that checked $args[1] wasn't correct
* tidy1: edWrite(): make file mode a parameter to open()
* tidy2: the same error message typo appeared a few times
> ed: r command addresses

- bin/install
* When destination argument is a directory and source file argument is a relative path in another directory, install gets the wrong destination path...
```
%perl install build/apply dst 
install: copy build/apply dst/build/apply: No such file or directory
```
* The correct destination path is 'dst/apply'
* Fix this by joining target directory to basename of source file
* Tested against GNU install
> install: target path in install_files()

- bin/install
- bin/patch
`exit` has higher precedence than `?:` and `==`, so `exit $Errors == 0 ? 0 : 1` parses as `(exit $Errors) == 0 ? 0 : 1`, which is not what was intended.
> fix exit status

- bin/expand
* Changes are based on a recent commit to unexpand
* expand_line() replaces do_expand()
* Remove non-standard -h option; usage string is still printed for -h
* Update usage string to clarify that spaces are not supported in -tab1,tab2 form
* POD: Move description of supported tabstop forms into OPTIONS section (providing them is optional)
* Style: assigning the result of map() is preferred
> expand: don't slurp input file

- bin/join
* Follow OpenBSD join and print usage string for unknown options (GNU join doesn't)
* Exit directly instead of calling die()
* Update regex in validation function get_numeric_arg()
* warn() messages preceding a call to help() don't require program name prefix
> join: show usage

- bin/chmod
- bin/chown
* When fixing this previously for chgrp command I failed to notice the same pattern in chmod/chown
* Test1: perl chmod -- 755 new.txt.exe
* Test2: perl chown -- root:root new.txt.exe # run as root
> chmod & chown: -- option terminator

- bin/col
* Printing "Bad Options" forced me to look at the POD manual if I typed something wrong
* It is more helpful to print a usage string (OpenBSD col does this but GNU col doesn't)
* Exit directly rather than through die()
> col: add a usage string

- bin/ed
* ed requires that all lines in its buffer are terminated with "\n"
* ed attempts to append a "\n" if it is missing on the last line of input
* The existing append logic in edEdit() was observed to only work for 'E' and 'e' commands, but not 'r'
* With E/e the entire buffer is destroyed and replaced with the content from the new file
* The append logic would then check the final line in buffer *after* the buffer was replaced (this worked ok)
* The 'r' command inserts the file content to any position within the existing buffer (e.g. 0r to insert to beginning of buffer)
* Checking for missing newline at end of buffer doesn't work if the data is inserted at a different location in buffer
* More general fix: check final line of tmp_lines list before it is applied to the buffer
* To test, …
> ed: newline append versus 'r' command

- bin/pr
* OpenBSD pr and GNU pr treat -o NUMBER as the number of margin spaces, but this version was printing Os
* Another difference I noted was that the page header is expected to offset based on -o, but it did not
* Tested with: perl pr -o 5 pr
> pr: improve -o margin_spaces

- bin/ed
* Reduce code noise by declaring error strings in constants
* Check close() return value in edWrite() as done in edEdit()
* Move some code to end of edEdit() that was being run for both $InsertMode and !$InsertMode branches
* Reduce layers of nesting in edQuit()
> ed: error string consolidation

- bin/pr
* pr enters a strange loop for certain -l values...
```
%perl pr -l 10 ed
...
Sat Nov 25 08:56:55 2023  Page 526462
...
Sat Nov 25 08:56:55 2023  Page 526463
...
Sat Nov 25 08:56:55 2023  Page 526464
...
Sat Nov 25 08:56:55 2023  Page 526465
...
Sat Nov 25 08:56:55 2023  Page 526466
...
Sat Nov 25 08:56:55 2023  Page 526467
^C
```
* In create_col(), $pagelength is set to zero for -l 10 because $trailerlength constant is 5
* After studying GNU pr manual, if -l value is 10 or less we assume -t and don't do any formatting of output
* When investigating this I discovered printf() should not occur for "perl pr -t file" (GNU pr copies input to output)
> pr: incorrect looping with -l

- bin/pr
* Standards document for pr mentions no arguments and '-' argument means we read from stdin[1]
* GNU pr and OpenBSD pr follow this
* A filename is not printed in page header for stdin
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/pr.html
> pr: support stdin

- bin/pr
* Raise an error if count doesn't look like a number, instead of silently accepting it
* Support for a + number prefix could be added if you like (GNU pr accepts it)
* Count of zero is accepted as before; this means no offset
> pr: validate -o COUNT

- bin/uniq
* Found this when testing against GNU uniq (using test file called "-l")
* Also correct some POD that didn't look right when I looked at pod2text output
> uniq: treat -- as end of options

- bin/hexdump
* Reduce the number of times the flag $opt{'c'} is tested
* Reduce code nesting by splitting dumper() into two functions (character & hex output)
* SYNOPSIS did not agree with usage string: file argument is optional
* Replace "stdin" wording with "standard input" in POD for consistency with other POD manuals
* Retire EX_USAGE; standard behaviour says exit code above zero is an error so EX_FAILURE is enough
> hexdump: slightly simplify

- bin/cat
* Option -n is number-all
* Option -b is number-some
* OpenBSD cat and GNU cat prefer -b if -n and -b are both given
> cat: -b overrides -n

- bin/ls
* File arguments are split into two lists: Dirs and Files
* Two separate loops call List(), first for Files list then for Dirs
* "perl ls -lR a a/a" was printing a "total" line twice, once (correctly) for dir "a" then (incorrectly) for regular file "a/a"
* Directory name line "a/a:" was also being printed for argument "a/a" but it is not a directory (see below output)
* Fix this by passing a new param to List() to tell it whether the entry being listed is a directory
```
%perl ls -lR a a/a # old output
a/a:
total 176
-rwxr-xr-x   1 pi       pi           88214 Nov 21 10:20 a/a
a:
total 224
-rwxr-xr-x   1 pi       pi           88214 Nov 21 10:20 a
drwxr-xr-x   2 pi       pi            4096 Dec  1 19:32 b
-rw-r--r--   1 pi       pi           20480 Nov 20 04:02 new.tar
a/b:
total 8
-rw-r--r-- …
```
> ls: too many totals

- bin/diff
* "perl diff . -" and "perl diff - ." are not valid usages because comparing stdin with a directory is not allowed
* Instead of failing in open() with a confusing error, output an error consistent with GNU diff
> diff: comparing stdin with directory

- bin/base64
* Print error message to show user something went wrong
* Exit code will be non-zero, indicating error to scripts
> base64: check close() return value

- bin/install
* Option -s is implemented and listed under DESCRIPTION in pod
* Add -s to usage() and pod SYNOPSIS
* It's ok that -f and -M are not listed in usage string & SYNOPSIS because these are only stubs for compat
> install: update usage string

- bin/tr
* GNU tr and OpenBSD tr do not allow a 2nd argument with -d, but allow it with -ds
```
%echo hello | perl tr -d l l # -d is ignored and l is replaced with l
hello
```
* Align usage string with SYNOPSIS
* test1: delete letter l: echo hello | perl tr -d l
* test2: delete letter l and o: echo hello | perl tr -d lo
* test3: exchange letters e and o: echo hello | perl tr eo oe
* Prevent $ARGV[0] from being set to undef by s/// in options loop
> tr: improve -d option

- bin/tr
* Switch code over to getopts() as done in other scripts
* This makes the option terminator -- work as in other versions of tr
* $opts declaration changes because %opt now only has bool values, not the option letter stored as the value
> tr: delete custom option parser

- bin/pig
* Changes are based on testing the NetBSD version of pig
* Print a usage string for bad arguments
* Ignore command arguments instead of implicitly treating them as file arguments
* Remove -h option
* Teach Dr. Bronner a new trick, that uc() can be applied without ucfirst() if $allcaps and $initcaps are both true
%perl pig asd # previously...
Can't open asd: No such file or directory at pig line 62.
> pig: NetBSD compat

- bin/diff
* Usage string: '|' before -e was missing
* Usage string: -q flag was missing
* Error message for >2 arguments incorrectly stated that arguments were missing
* When checking $opt_q we don't need to check @$diffs a second time
* Detect incompatible options with set_diff_type() which only allows default type of OLD to be overridden
* -U10 overrides -u and -C10 overrides -c (previously the final option wins the race)
* Introduce a regular usage() function
* Supported diff types...
perl diff a b       # diff_type=OLD context=0
perl diff -c a b    # diff_type=CONTEXT context=3
perl diff -C10  a b # diff_type=CONTEXT context=10
perl diff -e a b    # diff_type=ED context=0
perl diff -f a b    # diff_type=REVERSE_ED context=0
perl diff -q a b    # diff_type=ED context=0 (exit early compared to …
> diff: options handling improvements

- bin/diff
* Avoid doing s/// in a loop to add trailing newline to each element of outlist
* I checked that output is not changed for -e and -f options
> diff: output_ed_diff() tweak

- bin/apply
* The usage string suggests the 1st argument after the command name is not optional
* "apply echo 1 2 3" runs echo command 3 times
* "apply echo" by itself is not valid, so invoke usage()
* Exit with failure code in usage() so shell scripts can detect an error for bad options
* I found this when testing against OpenBSD version of apply
> apply: argument required after command

- bin/find
* It is good enough for awk front-end to print a short error with the name of the required CPAN module
* Make the error message printed by find front-end consistent with this
%perl find 
This program needs the App::find2perl module.
%perl awk
This program needs the App::a2p module.
> find: simpler error message

- bin/apply
* According with OpenBSD, "apply 1 2 3" should print an error message each time "1" command fails to run, then exit with error code
* "apply false 2 3" should not print an error message because "false" runs successfully, then exit with error code
* The return value from system() was not checked previously so no feedback was provided if something went wrong
* Prefix "usage:" to the usage string
* Bump version
* In future it would be useful to add debug option (-d) to show but not run the target commands
> apply: capture system() failure

- bin/words
* Join paths with File::Spec catfile() as done in other scripts
* Indroduce regular usage() function
* Print usage string for bad options instead of "Bad options"
* Print error if readline() failed
* Avoid open() if word-file is a directory
* Explicitly close word list
* Delete counter variable $words which was unused
%perl words -m2 -w /usr/share/dict/words oboeb
be
bob
boo
boob
ebb
oboe
> words: raise error for directory argument

- bin/uuencode
* Avoid open() if input file is a directory (otherwise garbage is printed with an error)
* Usage string was wrong because a file is required for -p flag
* Replace die("XXX") with regular exit() for success case
* Use getopts(): only -p flag is supported ($opt{p} is used directly)
* No need to print a warning when reading from stdin for special argument '-'
* Perform stat() on filehandle after open instead of file name
> uuencode: fail early for directory argument

- bin/sort
* Simplify usage() with Pod::Usage as done in other commands
* Remove "see docs" text from SYNOPSIS; seeing this in pod2text output is just confusing
* A few typos in POD manual
> sort: better usage()

- bin/env
* Test case repeated for GNU and OpenBSD env
```
%env -i -- O=o printenv
O=o
```
* This code doesn't use getopt so add '--' manually for now
* Remove ENVIRONMENT section of manual which is misleading
> env: '--' is valid option terminator

- bin/uudecode
* Print usage string for bad options
* Implement flag -i from OpenBSD and FreeBSD which raises an error instead of overwriting an existing file (default will overwrite)
* Create a basic OPTIONS section in POD manual
> uudecode: implement -i option

- bin/which
* Running "which" without an argument is an error (minimum of one argument is required)
* On my linux system, exit code is 1 and no output is printed
* On OpenBSD a usage string is printed; follow this
> which: expect an argument

- bin/apply
* Argument loop for apply -2 will continue while there are 2 remaining arguments
* If an odd number of arguments is given, the left-over argument is discarded and an error is raised
* OpenBSD apply ignores the odd argument, prints an error and does exit(1)
* This version ignores the odd argument but doesn't raise an error
* While here, move more common code into run_cmd(); calling system() in one place will make adding -d flag simpler
%perl apply -2 echo  1 2 3 4 # beautiful even args
1 2
3 4
%perl apply -2 echo  1 2 3 # test case, patch applied
1 2
apply: unexpected number of arguments
> apply: bad arg count

- bin/apply
* Add -d option (provided on OpenBSD & FreeBSD) to show the commands that would be executed
* At this time options cannot be grouped because getopt is not being used
* Update usage string
* Mention new option in pod
* Bump version
%perl apply -d -2 echo 1 2 3 4 
exec echo 1 2
exec echo 3 4
%perl apply -d -0 echo 1 2 3 4 
exec echo
exec echo
exec echo
exec echo
> apply: implement -d option

- bin/chown
* Add filename to error string if chown() fails; now it is consistent with stat() error message
* Remove -e file test before chown(); if file doesn't exist chown() will catch it
* Add program name to error messages
* Introduce regular usage() function
* Prefix usage string with "usage:"
* Replace exit($warnings) with exit($rc); now that sig-warn is gone we set $rc directly if chown() failed for any file
> chown: show filename in error message

- bin/cmp
* Save code by switching to getopts(); no special options parsing is required for cmp
* Now the TODO comment about grouped options can be removed
* Remove non-standard "-." option (usage is still printed)
* Raise error for -l and -s options together; these are mutually exclusive and GNU cmp raises an error here
* Print $! detail for failed open()
> cmp: forbid -s flag with -l

- bin/cmp
* Slightly simplify code by unpack()ing buffers that are not equal
* $lines_read becomes a tally, and $report_lines is always ahead by one because $lines_read counts from zero
* When printing the differences with -l flag, ord+substr pattern is avoided by using unpacked buffers
* Retire EX_USAGE which had same value as EX_FAILURE
> cmp: avoid repeated substr() on binary buffer

- bin/od
* Byte offsets were broken in a previous commit
* $offset1 is advanced by -j SKIP_BYTES; otherwise it counts from zero
* Advance $offset1 only after successfully printing a line of output (this does not affect $is_limit)
* At EOF, $offset1 is advanced by the remaining bytes; length($data) is correct
```
%perl od -c od | head -n1
00000017   #   !   /   u   s   r   /   b   i   n   /   p   e   r   l  \n 
%od -c od | head -n1
0000000   #   !   /   u   s   r   /   b   i   n   /   p   e   r   l  \n
```
> od: fix line offsets

- bin/pom
* Print usage for bad options instead of ignoring them
* Introduce checknum() helper function; negative numbers are not allowed
* Internal values $gm_hh/$gm_dd/$gm_mm do not need checknum()
* Avoid nested sub in kelper() function (found by perlcritic)
> pom: fatal error for unknown options

- bin/od
* Output for -b flag is handled in octal1()
* When debugging I observed $len == 1, but arr list contains 16 elements
* $pffmt needs to repeat for each element of arr list
* Repeating $pffmt was was handled correctly in other formatting functions, e.g. decimal(), so follow this
```
%perl od -b od | tail -n5
00013600 162 
00013620 157 
00013640 162 
00013660 145 
00013670
```
> od: strange output for -b option

- bin/fortune
* Print usage and exit if an unknown option was entered, following OpenBSD version[1]
* -h is not really an option
* Mention -n option in usage string as done in SYNOPSIS
* Document the purpose of -d flag in usage string and pod
1. https://github.com/openbsd/src/blob/master/games/fortune/fortune/fortune.c#L304
> fortune: fail for bad options

- bin/pr
* GNU pr and OpenBSD pr read option -3x as -3 -x
* An error is raised because -x is not a valid option
* This version was incorrectly absorbing non-digits after the "-3"
* Removing the dot-match makes this version consistent
* redo statement allows -x to be interpreted as the next option after $columns is set to 3
> pr: fail for -3x option

- bin/ar
* Previous version failed on my system with the error: "Can't locate getopts.pl in @INC"
* test1: bad option: "perl ar -Z" prints usage as expected
* test2: new archive: "perl ar -rc 123.a cmp col" creates a file successfully
* test3: list members: "perl ar -t 123.a" shows cmp and col
* test4: extract all: "perl ar -x 123.a" creates the files as expected
* NB: did not test with ar file generated by GNU binutils ar
> ar: missing library error

- bin/ls
* Future changes to ls are a little easier with strictness toggled to ON
* I checked that has("tput") is still ok on my linux system
> ls: add strict

- bin/head
* There's no standards requirement to interpret the argument '-' as stdin [1]
* The pod documentation did not mention the '-' argument having a special meaning
* Align the code with OpenBSD version: stdin is used if no file arguments are given
* head is supposed to be the inverse of tail, and tail doesn't support '-' as stdin
* This patch removes functionality; head becomes more consistent with tail
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/head.html
> head versus tail versus stdin

- bin/cat
* Undocumented -? option was accepted by getopt but ignored
* This option doesn't appear in GNU or OpenBSD version
* The only option mentioned by standards document is -u [1], so there is probably no reason to keep -?
* While here, prefix usage string with "usage:"
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cat.html
> cat: stop accepting -? flag

- bin/ar
- bin/file
* Previously the calls to open() were standardised to have 3 arguments
* Some scripts open files via FileHandle->new() instead of open()
* The pr command already used the preferred 2-argument form; also switch ar and file commands over to this
> Use two-argument form of FileHandle->new

- bin/tail
* I habitually type "tail -n5"; this is supported by GNU tail and OpenBSD tail
* Enabling bundling option in Getopt::Long makes it work in this version
* Style: avoid capture variable when the entire argument string "+590" is passed to check_number()
* test1: "perl tail -5 tail" -- historical option format, last 5 lines
* test2: "perl tail +590 tail" -- historical option format, line 590 to end
* test3: "perl tail -n5 tail" -- last 5 lines
* test4: "perl tail -n-5 tail" -- last 5 lines
* test5: "perl tail -n+590 tail" -- line 590 to end
> tail: allow -n1 and -n 1

- bin/grep
* Some calls to warn have string quoted with qq()
* Remove stray " from end of error messages, which caused perl to append "at grep line x"
> grep: trailing characters in error messages

- bin/ed
* The $offsetexpr variable can be used directly to avoid conditional code when calculating effective line address
* $offsetexpr is either "+123" or "-456"; both forms are valid to feed to int()
* I found this when reading perlcritic warnings for fixed-pattern regex
* The following test sets initial line address to 5 (output is the same for previous version and for GNU ed)
```
%perl ed -p '>>> ' asa
1903
>>> 5
Name: asa
>>> -1n
4	
>>> -1n
3	=begin metadata
>>> +2n
5	Name: asa
>>> q
```
> ed: simplify CalculateLine()

- bin/primes
* OpenBSD version prints an error if start>stop, which seems better than silently exiting
* Also, remove redundant comment text which is duplicated in the POD
> primes: error for bad start-stop range

- bin/cut
* Options -b and -f are consistent in how the value is handled
* Byte and field numbers count from 1
* Negative numbers are treated as a range end, with range starting from 1
* Regular ranges have 2 numbers separated by '-'
* Introduce a number validation function
* test1: positive -b value: "echo 'a:b:c:d' | perl cut -b 3" --> byte 3 is "b"
* test2: negative -b value: "echo 'a:b:c:d' | perl cut -b -3" --> bytes 1-3 are "a:b"
* test3: -b range: "echo 'a:b:c:d' | perl cut -b 2-3" --> bytes 2-3 are ":b"
* test4: positive -f value: "echo 'a:b:c:d' | perl cut -d ':' -f 2" --> field 2 is "b"
* test5: negative -f value: "echo 'a:b:c:d' | perl cut -d ':' -f -2" --> fields 1-2 are "a:b"
* test6: -f range: "echo 'a:b:c:d' | perl cut -d ':' -f 2-3" --> fields 2-3 are "b:c"
> cut: better input validation for -b and -f

- bin/col
* GNU col and OpenBSD col treat the +2 as a bad option; usage string is printed
* This version accepts '+2' as a filename but prints strange output 
* I started reading manuals and discovered col is *not* supposed to accept file arguments
* Only stdin is supposed to be read according to standards document[1]
* The "usage" error for GNU & OpenBSD occurs because remaining arguments are found after getopt is finished
1. https://pubs.opengroup.org/onlinepubs/7908799/xcu/col.html
```
%perl col +2 col # old output
Can't open +2: No such file or directory at col line 71. #!/usr/bin/perl
=begin metadata
...
p
r
i
n
t
$
s
p
a
c
e
s
;
Can't use an undefined value as an ARRAY reference at col line 246, <> line 267.
```
> col: incorrectly reads file argument

- bin/primes
* This version of primes accepts garbage characters at the end of number arguments Start and End 
* e.g. "primes 1xxx 9yyy" is accepted as "primes 1 9"
* Align with OpenBSD behaviour and print an error for this
* I still want to discover why 2 appears before 1 in the output
> primes: error for numbers with trailing non-digits

- bin/ed
* Take a hint from the TODO comments
* The big regex in edParse() doesn't help because spaces have a special meaning; the new branch bypasses it
* "!" line is printed at end of command output (or after error message if command can't be started)
* Ignore if the command exits with non-zero status; print error only if command doesn't start
* edPipe() doesn't take any line addresses because the output is not saved into the buffer
* Tested against GNU and OpenBSD versions
* test1: shell pattern: "!for i in 1 2 3; do echo $i; done"
* test2: zero exit status command: "!ls"
* test3: non-zero exit status command: "!false"
> ed: implement ! command

- bin/fish
* Usage string is one line, so no need for here-doc
* Declare and init $foo in one statement
* Assign result of map() instead of using map() in void context
* Remove unused variable ```@BOOKS```, found by perlcritic
> fish: style

- bin/ed
* In GNU ed, subcommand "f" requires a space before the filename argument, but the first non-space and everything after it becomes the argument
* e.g. for command "f why hello", command is "f" and argument is "why hello"
* The current command parser doesn't agree with this
* This problem was why I implemented "!" subcommand outside the big regex, but it's better for a more general fix
* Within the big regex, only non-spaces matched as the argument but any remaining characters should match
* test1: "!ls -a" no space between "!" and "l", which unfortunately gets taken as command suffix and has to be re-added into $args[0]
* test2: " f 12 " space after 12, sets file argument to "12 "
* OpenBSD ed agrees with GNU version for these tests
> ed: allow whitespace in argment

- bin/ed
* Based on prior regex, "+-" and "-+" are invalid relative addresses; GNU ed accepts "+-" but this version treats it as "extra arguments" error
* "++n" is numbered print, 2 lines ahead of currentLine
* "--n" is numbered print, 2 lines behind currentLine
* Only one of $pluses or $minuses will be set at this time
* Writing the logic in this way will make it easier to support "--++" in future for GNU compat
> ed: simplify relative line calculation

- bin/sort
* Basic validation
* Options -F and -y are non-standard and control allocation limits within sort
* Currently if the value of zero is given, it is ignored because of truth-test
* Negative amounts are accepted but don't make sense in the context of a limit size
> sort: enforce minimum value of 1 for -F and -y

- bin/echo
* Sometimes echo is built into the shell
* Standards document for echo doesn't mention the -? flag [1]
* The versions of echo that I tested don't support it
* I think it's better to follow convention and not treat -? as an option
* Sync pod and fix a typo in DESCRIPTION
1. https://pubs.opengroup.org/onlinepubs/009604599/utilities/echo.html
```
% builtin echo $BASH_VERSION
5.1.4(1)-release
% builtin echo -?
-?
% builtin echo --version
--version
% /bin/echo -?
-?
% /bin/echo --version
echo (GNU coreutils) 8.32
% builtin echo -?
-?
% builtin echo --version
--version
% builtin echo $KSH_VERSION
@(#)PD KSH v5.2.14 99/07/13.2
% /bin/echo -?
-?
% /bin/echo --version
--version
```
> echo: remove non-standard -?

- bin/tail
* Handle historic -NUM option before calling GetOptions(); -5 is -n5
* The options -b, -c and -n are incompatible; print usage and exit as done in OpenBSD tail
* Clarify an error message: s/null/zero/
```
perl tail -n2 tail | wc -c # last lines
6
perl tail -c2 tail | wc -c # last bytes
2
perl tail -b2 tail | wc -c # last blocks (512 bytes)
1024
perl tail -b2 -c2
perl tail -b2 -n2
perl tail -c2 -n2 
perl tail -b2 -2
```
> tail: bad option combo

- bin/head
* The POD text lied because the code was not compatible with OpenBSD
* Make head consistent with tail by accepting the historic -NUM form as -n NUM
* While here, correct the name of helper function: s/tail_fh/head_fh/
```
%perl head -2 head
#!/usr/bin/perl
%perl head -n 2 head
#!/usr/bin/perl
%perl tail -2 tail
=cut
%perl tail -n 2 tail
=cut
```
> head: support -NUM

- bin/ed
* edEdit() is always called and expects a filename to be passed in $args[0]
* Special filename '-' is the same as no filename; edEdit() expects $args[0] to be unset and will read stdin
* Extra file arguments are not allowed; only one file can be edited at a time
* When stdin is read, byte counts are not displayed
> ed: eliminate global variable $fname

- bin/rm
* Add pod description for -v flag and include it in usage string 
* Currently nothing calls usage(), but this is still helpful for reading pod2text
> rm: document -v

- bin/uniq
* Retire undocumented flags -? and -h (usage is still printed)
* Prefix usage string with "usage: "
```
%perl uniq -x
uniq: invalid option -- -x
usage: uniq [-c | -d | -u] [-f fields] [-s chars] [input files]
```
> uniq: print usage for invalid options

- bin/cat
* Guarantee that if close() failed for file1 that we print a warning for file1 before proceeding to process file2, then eventually exit with error code
* To preserve "cat - -", make sure *STDIN is not closed (on my linux system I type ctrl-d twice to terminate do_file() with EOF)
> cat: explicitly close files

- bin/install
* Making usage() exit instead of returning a string is more consistent with usage() in other commands
* test1: "perl install -G" --> unknown option
* test2: "perl install" --> no arguments
* test3: "perl -c -d ABC DEF" --> -d not allowed with -c
* test4: "perl install awk xargs" --> final argument is not a directory
> install: "usage()" > "die usage()"

- bin/fold
* Tested against GNU fold and OpenBSD fold
* POSIX semantics: If I want to fold a file called "-s" I put it after "--" (perl fold -s -- -s)
* Single "-" means read stdin; "---" is an invalid option
* Based on a similar patch to uniq
> fold: terminate options with --

- bin/grep
* NetBSD and FreeBSD versions of grep have an environment variable called GREP_OPTIONS which is added before any options given on the commandline
* This version did the same thing for env variable TCGREP so it could be renamed for slightly better BSD compatibility
* Update pod to explain how commandline options are used with respect to GREP_OPTIONS
* Referring to grep as tcgrep in the pod manual is confusing because the program is installed as grep not tcgrep; users might looks for tcgrep and not find it
> grep: GREP_OPTIONS preferred env name

- bin/cp
* When testing "perl cp awk awk" on my linux system, the OS cp command is being run via system()
* Source and destination are the same; cp fails with exit-code 1
* system() returns 256, but only the lowest byte is used when passed to exit(); shift system() return value as suggested in "perldoc -f system"
```
%perl cp awk awk 
cp: 'awk' and 'awk' are the same file
%echo $?
1
```
> cp: pass on child exit-code

- bin/wc
* Not all commands know about "--" yet
* Conversion to Getopt::Std is simple for wc because options are all single letter flags
* Remove differences for MacPerl which likely don't matter anymore (Getopt::Std will work on OSX perl)
* test1: "perl wc -c -- -c" --> process a file called "-c"
* test2: compare output of GNU version (below); different count for -w flag was present in previous versions
```
%for opt in c l m w; do echo "GNU -$opt"; wc -${opt} awk; echo "PPT -$opt"; perl wc -${opt} awk; echo; done GNU -c
4595 awk
PPT -c
4595 awk
GNU -l
204 awk
PPT -l
204 awk
GNU -m
4595 awk
PPT -m
204       675      4595      4595 awk
GNU -w
701 awk
PPT -w
675 awk
```
> wc: terminate options with --

- bin/sleep
* Align sleep with OpenBSD version, which shows usage string if extra arguments are given
* Previously this version ignored extra arguments
* Make pod text more useful
* test1: "perl sleep" --> no argument
* test2: "perl sleep -x" --> bad option
* test3: "perl sleep -- 1" --> valid: supported by GNU and OpenBSD
* test4: "perl sleep -- -1" --> bad interval
* test5: "perl sleep -- 1 2" --> too many arguments
> sleep: fail for extra args

- bin/fmt
* This version of fmt uses Getopt::Long to validate that the -w argument is a number
* Problem1: -NUM in the wrong place is treated as a valid option
*  e.g. with "perl fmt A -1 B", the expected input files are A, '-1' and B (-1 is not an option because A terminates the options)
* Problem2: -w argument needs a space (GNU fmt allows -w40)
* Now "-10", "-w10" and "-w 10" are treated the same
> fmt: improve -NUM option parsing

- bin/id
* With this patch, usage string is still printed for -h, but explicit code is not needed for it
* Standards document does not mention -h [1]
* Fix a typo in the pod document
1. https://pubs.opengroup.org/onlinepubs/009696899/utilities/id.html
> id: retire non-standard -h

- bin/ed
* Simplify -d option to become a flag and not take an argument
* The only supported argument was "parse", so this patch makes debugging easier to enable
* The old way with -ddebugstring did not provide any feedback if I typed an unsupported string
* Sync usage string in Usage() and Synopsis
* Remove redundant comment where usage string was also being maintained (but wasn't up to date with -s or -p)
> ed: simplify debug

- bin/od
* Dedicated if-statement is not required for setting -o as the default output format for od; use the default case for setting $fmt instead
> od: refactor default output mode

- bin/xargs
* BSD versions of xargs don't support the -l option
* Standards document for xargs mentions -L but not -l [1]
* Follow GNU version and accept -l as an alias for -L, but list standard -L in usage string
* Behaviour of -L/-l didn't match xargs on my linux system: input loop was terminated on first empty line of STDIN
* Skipping empty lines makes the behaviour match GNU version (empty means the line contains no non-spaces)
1. https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/xargs.html
```
%cat -n in # not all lines have content
1	#!/usr/bin/perl
2	
3	=begin metadata
4	
5	Name: awk
6	Description: pattern-directed scanning and processing language
7	Author: Tom Christiansen, tchrist@perl.com
8	Author: Larry Wall, larry@wall.org
9	License: perl
10	
%xargs -L 1 < in # …
```
> xargs exits on empty line from stdin

- bin/od
* The file offsets incorrectly jumped from 0 to 17, instead of 0 to 16
* When debugging this I found the formatting routines were modifying the value of $data by appending pad bytes
* Fix offsets issue by not modifying the value of $data
* Using global $len in the format routines is also not correct since the input loop was previously changed and $len will always be 1 (padding was added incorrectly in some cases)
* Remove global variable $upformat and provide the unpack format directly to unpack()
* Remove unsupported -a flag from the SYNOPSIS; it was not mentioned in help()
> od: incorrect file offsets after first 16 bytes

- bin/apply
* apply has a special mode where %NUM in the command string is substituted with an argument
* %NUM can be repeated in the command string, and the highest number determines how many arguments are consumed
* The explanation of this feature in the pod manual could be improved
* This example takes 2 elements from ARGV per instance of echo command (example tested against OpenBSD version)
```
perl apply 'echo %1 %2' a*
a ab
ab.diff ab.diff.orig
ac.diff ac.diff.orig
ac.diff.Orig ac.diff.ORig
ac.diff.ORIg ac.diff.ORIG
a.col addbib
alink apply
apply.new ar
ar2 arch
arithmetic ar.unexpand.new
ar.unexpand.old ar.uu
asa asd
a.uniq awk
```
> apply: use library max() instead of hand-rolled

- bin/arch
* Make arch command more compatible: no arguments are allowed
* Incorrect options were ignored but should raise an error
* GNU and OpenBSD versions raise an error for these 2 cases; OpenBSD prints usage string
* test1: "perl arch -k arch" --> valid option, invalid argument
* test2: "perl arch -x" --> invalid option
> arch: forbid command arguments

- bin/ed
* In edMove(), special code isn't needed for $count of one because the .. operator can handle 1..1
* edPrint() already relies on this because it loops with "$adrs[0] .. $adrs[1]", where both can be equal
* Tested with command "1m20" to move the 1st line in buffer ($end is inferred from $start)
* Remove chmod() comment in edWrite(); OpenBSD version does not perform chmod() and that is a better reference
* Standards document mentions nothing about changing file modes/permissions[1]
* In edHelp() the saved error will be printed each time the "H" command enables the help flag; avoid extra return statement
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ed.html
> ed: clean some redundant code

- bin/rev
* GNU and OpenBSD versions of rev use getopt(), so they support '--' for terminating options; add getopt() here too
* Remove --help (-h); usage string is still printed
* Update SYNOPSIS and usage() to indicate multiple input files can be processed
* test1: "perl rev -- -v 01 02" --> 3 input files (now I can read file called "-v" without typing "./-v")
* test2: "perl rev -x" --> bad option
> rev: terminate options with --

- bin/paste
* Behave more like standard paste; zero arguments is considered invalid usage [1]
* Update SYNOPSIS and usage string to indicate a file argument is needed
* Add description in pod to explain special '-' file argument
* Style: Merge declaration+assignment of file handle in loops
* test1: "perl paste" --> now print usage
* test2: "perl paste paste" --> same as cat
* test3: "cat paste | perl paste -" --> same as test2
* test4: "ls | perl paste - - -" --> ls output 3 items at a time
1. https://pubs.opengroup.org/onlinepubs/7908799/xcu/paste.html
> paste: reject implied file argument

- bin/ed
* If current line is 10, and I enter 1s/e/E/, the substitution was occurring for lines 1-10 instead of just line 1
* If I want substitution on lines 1-10 I'm supposed to type 1,10s/e/E/
* If I only want to substitute on the current line I omit the addresses and type s/e/E/
* Patch is based on existing behaviour of edPrint()
* When searching for assignments of $adrs[1] I didn't find any more instances where it's set to current line
* Add validation to prevent line address 0 for "s" command (0 is valid for a few ed commands though)
* Fix logic in edHelp() for "h" command
> ed: 1s/pat1/pat2/ incorrectly processes multiple lines

- bin/cat
* When printing line number prefix for -n and -b flags, terminate the line number with a tab character
* This makes the output compatible with the OpenBSD and GNU versions
* Flags -n and -b are not covered in standards document [1]
* Line number can be printed directly without modifying the value of line buffer $_
* Now md5sum matches for /bin/cat -n and -b output on my linux system
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cat.html
> cat: line number compat

- bin/maze
* Program name comes after the "usage: " prefix
* Init maze data without using a counter variable
> maze: tweak usage string

- bin/id
* Improve the pod SYNOPSIS by adding the different usages  which were listed in help()
* Usage string should not include -a option because it is ignored (as documented in pod)
* getopts() parameter only needs one 'a'
> id: don't suggest -a in usage

- bin/bc
* Standards document does not mention special interpretation of file argument '-' for bc [1]
* Argument '-' is treated as a literal filename on FreeBSD, OpenBSD and Linux
* Standard input is only read if argument list is empty
* Bypass call to open() if file argument is a directory
* Update pod SYNOPSIS
> bc: standard behaviour for '-' argument

- bin/nl
* Expand input validation code to cover -n option
* As mentioned by the usage string, only 3 values for -n are accepted
* This was found when testing against GNU nl
> nl: validate -n option

- bin/fold
* GNU fold treats '-' as a special file argument but that is an extension
* Standards document contains wording that stdin is only used if no arguments are given; OpenBSD follows this [1]
* The pod manual also says stdin is only used as a default for no file arguments ('-' is not documented to have a special meaning)
* This change was recently made to bin/head also
1. https://pubs.opengroup.org/onlinepubs/009695299/utilities/fold.html
> fold: '-' is not stdin

- bin/bc
* Set up signal handlers before running any code
* Global $YYTABLESIZE is unused
* Delete commented code related to old goto-label "outer"
> bc: unused var

- bin/basename
- bin/dirname
* This change is covered by Exit Status section of these documents:
https://pubs.opengroup.org/onlinepubs/007904975/utilities/dirname.html
https://pubs.opengroup.org/onlinepubs/007904975/utilities/basename.html
* This was found when testing against the GNU version
* While here, prefix usage string with "usage: "
> basename/dirname: exit(1) for no args

- bin/fish
* Init the deck without a loop
* Loop in fisher_yates_shuffle() can be written without a "next" statement; swap if unequal
> fish: reduce loops

- bin/cmp
* $checklength is the maximum offset in buffer to check which byte(s) in the 2 buffers are not equal
* The subsequent loop is from 0 to $checklength, so avoid potentially accessing $bytes1[$chunk_size]
* If $read_in1 and $read_in2 are equal to $chunk_size, the value of $checklength is not decremented
* Calculate minimum of $read_in1 and $read_in2 (these will never exceed $chunk_size), then decrement by 1
> cmp: check length off-by-one

- bin/whoami
* Follow OpenBSD and GNU versions of 'whoami' by raising an error if argument count is not zero
* Add symbolic exit codes, as done in other scripts
> whoami: treat arguments as error

- bin/kill
* The existing validation for signal-number-too-big doesn't work correctly when "use integer" is enabled
* I tested this with a very large number
* "perl kill -7685876587234234 12" proceeded to kill process 12 incorrectly
* Removing integer pragma fixes this issue for me
> kill: signal number validation

- bin/bc
* In exec_stmt(), instruction 'p' takes an array name and index number, then pushes the array element onto the stack (implicit print)
* The default value for array elements is 0
* The instruction '=P' assignd a value from the stack into an array element
* Make the code for 'p' simpler by appending '[]' to $name, as done for '=P' instruction
* For instruction '=P' the value being assigned to array should not be printed (this is controlled by $return variable)
* For input "a[9] = 123; a[9];" the value of 123 should be printed once, for the 2nd statement
* Tested this input against GNU and OpenBSD versions
> bc: array assignment incorrectly prints

- bin/wc
* As noted earlier, word count output in wc did not match GNU version
* A word is one or more non-space characters, surrounded by whitespace (including newline)
* The old code seemed to count the spaces in between words, but I couldn't follow it
* To test this I built the OpenBSD version of wc on my linux system, then compared total word count for a set of files between OpenBSD, GNU and perl
```
%$wc_obsd -w s*
wc: s: Is a directory
0 s
524 seq
330 shar
319 shar2
225 sleep
4098 sort
1789 spell
895 split
wc: sssss: Is a directory
0 sssss
444 strings
1116 sum
9740 total
%perl wc -w s*
wc: 's' is a directory
524 seq
330 shar
319 shar2
225 sleep
4098 sort
1789 spell
895 split
wc: 'sssss' is a directory
444 strings
1116 sum
9740 total
%/usr/bin/wc -w s*
/usr/bin/wc: s: Is a directory
0 s
524 …
```
> wc: unexpected counts for -w flag

- bin/yes
* Align usage with Free/Net/Open/DragonFly BSDs and Mac-osx
* Command options are not supported: "yes --hey" prints "--hey"
* String printed is the 1st command argument; extra arguments are ignored: "yes a b" prints "a"
> yes: remove GNU extension

- bin/ed
* edEdit() handles both "r Filename" and "w Filename"; "w" replaces entire line buffer
* $chars is the number of bytes read into the buffer from the file
* Use $chars directly as the byte count instead of copying the value from $tmp_chars (reduce confusion)
* Variable tmp_lines2 also gets removed
* Return 0 for failure as advertised at top of edEdit()
* Change remaining regex to eq in command interpreter for consistency
> ed: simplify edEdit()

- bin/diff
* Mapping loop is more direct to write with map()
* Check for error instead of success in output_diff()
* Tested this with -e, -f and -u flags on some small files
> diff: reduce code noise

- bin/paste
* $current_sep alternates between the available separator values
* By default only one separator is used, so the (index) value is always 0
* Use mod (%) to wrap the value back to 0; now the value is only modified in one place
* For the default (non -s) mode, line[n] of each file is joined
* Instead of using chop to kill the extra separator (as done in -s code), separator only gets added to line[n] of files before the last
* Having $current_sep++ inside quotes made reading the code annoying
* Test commands produce the same output as GNU paste
* test1: "perl paste -d 'AB' cp cp cp" --> cp^3
* test2: "perl paste -s -d 'AB' yes yes" --> yes^2
> paste: field separator index

- bin/colrm
* In 2-argument mode, the default variable $_ is not used in the loop
* Adding \n back to line is reversing the chomp at start of loop
* I checked that $_ did not have a value here
* test: "perl colrm 2 2 < file.txt" removes the 2nd character on each line of file.txt
> colrm: accidental $_

- bin/env
* If I typed the wrong option to env, e.g. -x, print the usage string to show the correct options (BSD version does this)
* pod: clarify that the -u option can be used more than once
* pod: words found by spell-checker
> env: print usage for bad options

- bin/cmp
* Usage string states that file1 and file2 are required
* Standards document indicates file2 is not supposed to be inferred as stdin [1]
* Either file1 or file2 can be specified as '-' for comparison against stdin
* test1: error: no args: perl cmp
* test2: error: bad option: perl cmp -x 
* test3: error: file2 omitted: perl cmp test.txt
* test4: error: two stdins: perl cmp - -
* test5: compare stdin with file bc: echo '#!/user/bing' | perl cmp - bc
* test6: skip 1 byte of file1: perl cmp ar awk 1
* test7: skip 1 byte of file1 and file2: perl cmp ar awk 1 1
* test8: error: too many args: perl cmp ar awk 1 1 1
1. https://pubs.opengroup.org/onlinepubs/009604499/utilities/cmp.html
> cmp: 2-argument minimum

- bin/look
* Exit code 0 means one or more lines were found based on input search pattern
* Exit code 1 means no lines were found
* Exit code 2 means the program failed (e.g. bad path for argument2)
* Clarify this by declaring 3 constants
* With this patch, usage() exits correctly with 2
* Style: remove global $def_dict, which is a function of global $filearg
> look: standard exit code

- bin/addbib
* If file argument '0' was given to the -p option, it was incorrectly ignored
* extra1: remove warnings.pm as done in other scripts
* extra2: simplify prompt input regex by writing it as a character group; found by perlcritic
> addbib: -p option handling

- bin/apply
* It is safe to pass @_ to system() if @_ is empty
* This happens when running apply with the -0 option
* test: "perl apply -0 echo 1 2 3" --> echo runs 3 times with no argument
> apply: simplify run_cmd()

- bin/primes
* This version of primes takes 0, 1 or 2 arguments
* 0 args: read Start from standard input and use default End
* 1 arg: Start is arg1 and End is default
* 2 args: explicit Start and End
* This patch is compatible with NetBSD, which prints usage if >2 args are given
> primes: fail for too many args

- bin/expand
* This version of expand follows standard and does not treat '-' as stdin [1]
* Unfortunately the regex for the -1,2,3 tab-stop form was matching incorrectly because:
1) zero characters after '-' were allowed (valid usage requires at least 1 digit after dash)
2) '-' was allowed to appear after the first character
* With this patch, invalid usage "perl expand - -" fails on the first instance of '-'
1. https://pubs.opengroup.org/onlinepubs/007904975/utilities/expand.html
> expand: regex too greedy

- bin/tac
* The code at beginning of file was not covered by "strict"
* When adding strict at top of file, %opts was not in global scope
* This patch fixes a bug where options such as -s SEP were being ignored
> tac: strict.pm coverage

- bin/ed
* edInsert() handles Append "a" command and Insert "i" command
* The special case for address 0 can be removed; the code with tmp_lines2 is general enough to handle this, i.e. for address 0, tmp_lines will be added at start of buffer and tmp_lines2 will be empty
* In insert mode the target address is the addressed line; decrement is needed for conversion to correct array index
* test1: "0a", "0i" and "1i" --> add input to start of buffer
* test2: "1a" and "2i" --> add input after buffer line 1, and at buffer line 2 (equivalent)
> ed: edInsert() mostly duplicate code

- bin/shar
* Print usage and exit if no file arguments are given (in docs, at least one file argument is required and standard input is not used)
* Remove variable $dirty for keeping track of whether header was printed; just print it once before loop
* Introduce variable $done to count how many files were processed
* Checking $dirty at end of loop was incorrect; this resulted in printing an error on success and exiting with error code
* test1: "perl shar" --> no args, usage
* test2: "perl shar no-such-file" --> print message "no files were processed"
* test3: "perl shar tar" --> archive one file 'tar' successfully
> shar: error detected for no files processed

- bin/deroff
* File argument is documented as optional, but deroff fails when I omit it
* Patch is the result of testing against deroff on OpenBSD
* Convert file processing into a function taking a filehandle param
* Add strict
* Print usage and exit for bad options (previously bad options were treated as a file arg)
* Check return value of close()
* test1: "zcat /usr/share/man/man1/sum.1.gz | perl deroff" --> no args; read stdin
* test2: "perl deroff -" --> error because I have no file called '-' and '-' does not indicate stdin for this program
* test3: "perl deroff deroff deroff" --> 2 file args; program assumes input is in expected format
> deroff: allow standard input

- bin/ping
* Print usage and exit for invalid option -x
* Include -n flag in usage string
* Throw error if extra arguments appear (closer to BSD version)
* test1: "perl ping" --> error; no host
* test2: "perl ping -x" --> error; no -x flag
* test3: "perl ping 127.0.0.1 10" --> success; localhost with timeout of 10 seconds
* test4: "perl ping 8.8.8.8 10 11" --> error; 11 means nothing
> ping: fatal error for unknown options

- bin/asa
* Problem1: asa would refuse to open a file with a dash
* Problem2: if opening a file fails, asa did not proceed to the next file argument
* This patch brings the code closer to NetBSD version [1]
* test1: "echo hi | perl asa" --> no args; read stdin
* test2: "perl asa real-file" --> one file argument; real-file is not a command option
* test3: "perl asa notfound real-file" --> warn for not opening 'notfound', process 'real-file' then exit with code 1 to indicate error
1.  http://cvsweb.netbsd.org/bsdweb.cgi/src/usr.bin/asa/asa.c?annotate=1.17
> asa: regex too greedy

- bin/uname
* As with bin/arch, uname does not accept any arguments
* For this case the Linux version fails with 'extra operand' error and the OpenBSD version prints usage
* POD after __END__
> uname: reject command arguments

- bin/nl
* Standard nl is not required to support multiple input files [1]
* Follow BSD versions of nl and support only one input file, which may be '-' for stdin
* Also checked SunOS manual page, and it is consistent with BSD [2]
* Update usage string and description in POD
* While here, add explicit close() call in do_file() so we can exit with failure code if close() fails
* Delete comment at top of file which duplicates what is written in POD
* Bump version
1. https://pubs.opengroup.org/onlinepubs/009695399/utilities/nl.html
2. https://shrubbery.net/solaris9ab/SUNWaman/hman1/nl.1.html
> nl: support one file argument

- bin/tee
* The following command works the same on Linux and OpenBSD: "tee -- -mylog"
* The argument list contains one file called "-mylog"; it's not an option as it appears after '--'
* Perl code has a custom option parser so it needs to handle '--' directly
> tee: '--' option terminator

- bin/od
* Standards document specifies multiple input files should be processed [1]
* Follow BSD od and read stdin only if no arguments are given
* Update usage string
* Options -N and -j affect the input stream overall, not just the 1st file processed
* Uneven input data left over at EOF is combined with input from the next file
* Uneven input data at end of the last file gets its own dump_line() call
* Formatting routines are now written without the need for global $pffmt
* test1: "echo hello |  perl od -c -N 2" --> format 1st two bytes from stdin as characters
* test2: "od -j 1 -x  awk ar" --> dump awk and ar files as hex, skipping 1st byte of input
1. https://pubs.opengroup.org/onlinepubs/009696899/utilities/od.html
> od: support multiple input files

- bin/unshar
* I noticed that shar works with command line "perl shar -- -file1", but unshar doesn't
* There was no unshar command on my Linux or OpenBSD system to test against
* I installed gnu sharutils 4.15.2 and proved that it does support '--'
/usr/bin/unshar -- -file1
fs error 2 (No such file or directory) stat-ing -file1
> unshar: '--' option terminator

- bin/split
* "perl split -b 0 file" is invalid but did not raise an error due to truth check on $opt{b}
* -b NUMBER has no default value, but it must be >0
* Add explicit checks for options -b, -l and -p which cannot be used together
* test1: "perl split -b 0 file" --> now fails
* test2: "perl split -b 1 file" --> one byte per file
* test3: "perl split -b 5 file" --> final file with <5 bytes (remainder)
* test4: "perl split -l 2 file" --> two lines per file
* test5: "perl split longfile" --> default -l mode: 1000 lines per file
> split: raise error for -b 0

- bin/ar
```
%perl ar -a -x
Uncaught exception from user code:
fileparse(): need a valid pathname at ar line 40.
File::Basename::fileparse(undef) called at /usr/local/lib/perl5/5.34.1/File/Basename.pm line 222
File::Basename::basename(undef) called at ar line 40
```
* Flags -a and -b require extra position value in ARGV; if this is missing it is reasonable to print usage and exit
> ar: runtime error for bad args

- bin/cut
* Invalid usage resulted in undocumented behaviour; "perl cut -b 1 -f 1" would run handle_b(), exit and ignore "-f 1"
* GNU and OpenBSD versions fail in this case because only one of -b and -f can be specified
* For Perl version, option -c is an alias for -b, so add validation check after equivalence code for -c
> cut: -f not allowed with -b

- bin/which
* Previously, bin/which would use exit code 0 (success) even if it failed to locate a command, making it more difficult to use in shell scripts
* Follow GNU version and treat exit code 2 as internal error, 1 as partial-or-no-match, 0 as all-commands-matched
* Follow OpenBSD version and print error to stderr for each command that does not match
* Bump version
* test1: "perl which" --> invalid usage due to no argument, exit(2)
* test2: "perl which sh ls" --> sh and ls are both found on my system, exit(0)
* test3: "perl which sh brash" --> sh is found and brash is not, exit(1)
* test4: "perl which -a awk" --> 3 awks are found on my system, exit(0)
> which: 3 distinct exit codes

- bin/glob
* A tilde by itself signifies $HOME if it is not followed by a username
* I regularly type "cd ~/somedir" but an error was being raised by this version of glob
* Splitting the code into separate regexps makes this a bit clearer
* With this patch the output matches the following globs from bash
* test1: "echo ~" --> /home/pi
* test2: "echo ~/" --> /home/pi/
* test3: "echo ~pi" --> /home/pi
* test4: "echo ~pi/" --> /home/pi/
* This also matches output from perl's glob() on my system
> glob: handle bare tilde

- bin/ed
* Code can be reduced by checking for error instead of checking for success
* Style: consistently return 1 or 0 (return value is not currently checked)
* test1: open file with "perl ed awk", then hit return/enter to proceed to maxline+1 (error for increment case)
* test2: open file with "perl ed awk", then type "1" (success for jump case)
* test3: open file with "perl ed awk", then type "10" then hit extra return (success for increment case after jump to 10)
* test4: open file with "perl ed awk", then type "1000" (error for jump case; line number out of range)
> ed: simplify edSetCurrentLine()

- bin/fmt
* Explicitly open() input files so we can exit with a failure code if open() fails
* Input loop is converted into a function; line buffer remains global
* Ignore directories as done by GNU fmt
* Read stdin if no file arguments are given
* Tested patch against previous version and I get the same output
> fmt: indicate open() failure

- bin/sum
* This version of sum attempts to be compatible with NetBSD by offering -o 1 and -o 2 for the historic BSD and SYSV sum algorithms respectively
* When -o is used for selecting an algorithm, forbid -a option which is used for selecting newer algorithms such as md5
> sum: ambiguous options

- bin/expand
* The default number of spaces for a tab is 8
* The number of spaces is changed by running something like "perl expand -12 file", but when doing this I get one space not 12
* line_desc is only set if multiple tabstops were specified (not relevant to this usage)
* When one tabstop is given, e.g. "expand -12 file", $tabstop has been updated and we should use its value
* Now -12 argument works the same as OpenBSD and GNU version
> expand: single tabstop correction

- bin/expand
* Accept usage that GNU expand accepts: "perl expand -4 -- -a" for a file called "-a"
* Remove stray quote from error string
> expand: '--' option terminator

- bin/id
* This version of id follows BSD and only supports one user argument
* Instead of ignoring extra arguments, print usage and exit as done by OpenBSD version
* test1: valid usage: "perl id 0" --> display root user on my Linux system
* test2: invalid usage: "perl id 0 0 0 0 0" --> previously did not raise error
* test3: valid usage: "perl id" --> user taken as "current user"
> id: don't ignore extra arguments

- bin/ar
* In quick-append mode (-q), ar creates a file if it doesn't exist and appends to a file if it exists
* I discovered that if a file is created in this way, the valid header record is not printed, making the archive invalid
* GNU ar is smart enough to print file header in this case
* step1: quickly create archive with one file: perl ar -q new.ar addbib 
* step2: append another file to archive: perl ar -q new.ar asa
* step3: list files in archive: perl ar -t new.ar
> ar: file header not printed for -q

- bin/tar
* I want to extract a tar
* It's not possible to create a tar with this program because -c option is not implemented
* I create a tar with GNU tar (v1.34), but extraction didn't work
* Problem1: stdin was being read because file descriptor wasn't redirected properly; instead just declare $fh as input file handle
* Problem2: in extract_entry() file mode wasn't being handled properly; shifting bits wasn't correct because mode was already 0755 in the test tar
* Removing the early return allows the tar to be extracted
* test: copy new.tar to a new directory, change directory into it and run "perl $PPT_DIR/tar -x -f new.tar"
> tar: file extraction fix

- bin/nl
* As outlined in usage string, the valid line numbering types for options -b/-f/-h are a/t/n/pexpr/eexpr
* 1st character of option-value gets split into "type" list; validate this list at start of program
* Invalid usage example: perl nl -b a -f n -h o
> nl: numbering type validation

- bin/ln
* Short-hand usage of ln on Linux and OpenBSD: "ln -s /etc/hosts" creates a symbolic link "hosts" in the current directory
* This version of ln did not enter files loop if only 1 argument is given
* test1: "perl ln -s awk" --> fail because awk already exists in current directory
* test2: "perl ln -s /etc/not-exists" --> successfully creates a synlink to a non-existent file
* test3: "perl ln -s /etc/hosts"
> ln: single argument usage

- bin/od
* I noticed the duplicate line identifier "*\n" was repeated for each duplicate line, instead of being printed only once
* In dump_line() the variable $ml had no effect; possibly it was broken by previous changes
* Make $ml a flag which is set when previous line was duplicate *and* "*\n" was already printed; flag is set until a line differs
* With this patch, output is equivalent when dumping /dev/zero on OpenBSD and Linux
```
%dd if=/dev/zero bs=1000 count=1 2> /dev/null | perl od -c 
00000000  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0 
*
00001740  \0  \0  \0  \0  \0  \0  \0  \0 
00001750
```
> od: duplicate marker incorrectly repeats

- bin/unexpand
* This was identified when testing against GNU version
* Rewrite option parser to align with bin/expand; global $arg variable is not needed
* Example valid usage: "perl unexpand -a -2 -- -a" --> tabstop=2, aflag=1, read file "-a"
* Example bad usage: "perl unexpand -x -2 3" --> no -x
> unexpand: -- option terminator

- bin/ar
* ar -p mode with no arguments prints all members of the archive to standard output
* ar -p can be given explicit member names to print
* If I type the wrong member name GNU ar gives me a warning and proceeds to print the next member argument
* Example: "perl ar -p new.ar notfound asa" --> print warning on stderr for notfound not being found, then print content of file asa on stdout
> ar: warn if archive member isn't found

- bin/hangman
* An empty wordlist.txt could be provided, in which case hangman should fail because no lines can be read
* Also, there was no code after the read-words loop to check if $word was given a value
* Rewrite read-words loop without the need for $line_num variable
* test1: create empty wordlist with "touch wordlist.txt"
* test2: create a list with 1 word: "echo hey > wordlist.txt"
> hangman: more validation

- bin/join
* This was found when testing against the GNU version of join
* Add handling to custom option parser get_options()
* test: "cp awk ./-a && perl join -- -a -a | md5sum" --> join file "-a" with itself
> join: '--' option terminator

- bin/printenv
* Remove -? which is not present in GNU or BSD version of printenv
* The BSD version does not support options starting with a dash
* While here, restructure code to avoid multiple exits; exit code 1 is designated for the (optional) argument not being found in environment
> printenv: retire -? flag

- bin/ar
* ar was mostly compliant with strict except for option variables
* Instead of summing $opt_d, $opt_m etc (which might be undefined), count options using a list
* Don't access $ARGV[0] if it doesn't exist
* test1: "perl ar" --> invalid: need a major option to determine mode
* test2: "perl ar x notfound" --> valid: equivalent to ar -x notfound
* test3: "perl ar -x -m" --> invalid: -m and -x are not compatible
> ar: add strict

- bin/touch
* Standards document does not specify behaviour of -f flag for touch, so it's not a bug to leave it unimplemented [1]
* NetBSD and OpenBSD currently treat -f as no-op, but previously OpenBSD implemented it
* No need to document differences from OpenBSD which no longer exist
* Don't suggest -f in usage string because it's silly
* Fix typo in pod
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/touch.html
> touch: remove -f from usage()

- bin/kill
* version1: bash: "builtin kill -h" --> "invalid signal specification" error
* version2: GNU: "/usr/bin/kill -h" --> prints usage string
* version3: pdksh: "builtin kill -h" --> "unknown option" error
* version4: OpenBSD: "/bin/kill -h" --> "unknown signal" error, then print signal list
* To me, version4 is the most helpful because it saves the user having to type "kill -l" to see the list
* test1: "perl kill" --> no pid given; print usage
* test2: "perl kill -h" --> print error, show signal list, exit(1)
* test3: "perl kill -l" --> show signal list, exit(0)
* test4: "perl kill 1" --> fails as expected because my user doesn't have permission to kill init process
> kill: list signals for bad sig name

- bin/du
* du can take a number of file arguments
* GNU and OpenBSD versions will print a warning if a file fails to stat, then proceed to the next file
* test: "touch there1 there2 && perl du nothere1 nothere2 there1 there2" --> two warning lines and two du summary lines
> du: warn on stat() failure

- bin/install
* Test: running "perl install -m a=rx xargs build/" didn't install xargs with the correct permissions
* Problem1: Return value of mod() was not saved into $bits
* Problem2: When doing '=' operation, the value of the current permissions ($current) was being used incorrectly
* Resetting permissions to 0 for '=' operation allows only the appropriate bits to be set, not extra ones based on source file stat()
* Problem3: The permission bit for 'r' saved in $perms{$s} was lost because of assignment of permission for 'x'; code should use OR on $perms{$s} instead
* Operators '+' and '=' should both apply OR to the permissions; the difference is that '+' applies to the Source file permissions whereas '=' applies to 0
* Test2: "perl install -m u=rwx bc build/" --> install bc with permissions of 700 …
> install: broken symbolic permissions

- bin/maze
* The usage string is the source of truth; optional maze algorithm flag goes before optional width and height arguments
* Remove the grep that reconstructs ARGV with options removed; this caused the incorrect usage "perl maze 20 30 -sf" to be accepted
> maze: options before arguments

- bin/bc
* The default mode of this bc is not bc at all because it is not arbitrary precision; numbers are just perl floating point values
* It's still useful enough as a basic calculator, but not as a bc-compatible one
* For fun I booted DamnSmallLinux live-cd v4.4.10
* The version of perl on this old linux doesn't include Math::BigFloat
* bc would not load, even in default mode because of a "use" statement; lazy-load with "require" avoids the error
* test1: "perl bc" --> load in not-arbitrary-precision mode and 2**128/33333 is a perl floating point number
* test2: "perl bc -b" --> fail to load Math::BigFloat on old perl
> bc: regression on old perl

- bin/bc
* Previously this change was committed for internal =P instruction, which runs when assigning an array value, e.g. "ary[0] = 1"
* Apply the same change to the =V instruction, for regular variable assignments
* Instruction =V happens for shortcut assignment operators too
* This patch makes bc agree with GNU version and Gavin Howard version
x = 1
x += 2
x -= 1
x *= 4
x /= 2
x ^= 2
> bc: assign '=' should not print

- bin/test
* The wording of standards document is "exit 1 if expression evaluates to false, or if expression is missing"
* A usage example might be "if [ $xyz ]" in a shell script; unquoted variable will substitute to empty string if not set so no argument is passed to test command
* 4 different versions of test exit(1) consistently for this case: pdksh builtin, bash builtin, /usr/bin/test on Linux and /bin/test on OpenBSD
1. https://pubs.opengroup.org/onlinepubs/009695399/utilities/test.html
> test: exit(1) for no argument

- bin/mail
* In package "mailer", hostname() is a setter method for object attribute "hostname" (L48)
* Sys::Hostname auto-imports a hostname() which causes a conflict; as a result I cannot send a mail message with 'm' command
* Prevent auto-import of Sys::Hostname symbols to resolve this
```
%perl mail
Loading the mailfile /home/pi/mbox
Mail [0.02 Perl] [linux]
N  1                                    154/ 904 (no subject)
2           nobody  Mon Sep 17 00:00  41/1036 [PATCH] another patch
3           nobody  Mon Sep 17 00:00  32/ 706 re: [PATCH] another patch
4           nobody  Sat Aug 27 23:07 120/3138 [PATCH 1/2] GIT: Try all addr
5           nobody  Sat Aug 27 23:07 107/3764 [PATCH] Fixed two bugs in git
6           nobody  Mon Sep 17 00:00  72/2926 [PATCH] a commit.
7           nobody  Mon Sep …
```
> mail: overloaded hostname() definition

- bin/bc
* Negative array index is being caught when accessing a value (p instruction), but is not caught when assigning a value (P instruction)
* Adapt existing guard code from 'p' instruction
* For consistency with undefined-function error, replace YYERROR call with "last INSTR"
* Only the 2nd-from-top ope_stack element is needed; fetch it with splice instead of pop+push dance for $value
```
%perl bc -d # before patch
ary[-1]
instruction: N, 1
instruction: m_
instruction: p, ary
Non-integer index -1 for array
ary[-1] = 123
instruction: N, 1
instruction: m_
instruction: N, 123
instruction: P, ary
instruction: =P
wat
```
> bc: forbid negative array index

- bin/bc
* Array names are allowed to contain numeric digits but cannot start with a digit: ary2 is valid but 2ary is not
* Assigning then fetching an array value didn't work as expected
* I got a hint when adding debug statement to the =P instruction: "name[[]] idx[] varName[ary2[]1] at bc.y line 982, <STDIN> line 2." 
* The regex did not match because varName is "ary2[]1"; the regex expected that a digit would only be found after the "[]" substring
* Make the code more correct by splitting on "[]" to get the array name "ary2" and the index of "1"
* varName string is built earlier by the P instruction
```
%perl bc -d # before patch
ary2[0] = 1
instruction: N, 0
instruction: N, 1
instruction: P, ary2
instruction: =P
ary2[0]
instruction: N, 0
instruction: p, ary2
0
```
> bc: array name versus digits

- bin/awk
* My Linux system has perl 5.32.1, and I installed App::a2p under it using cpanm
* Now my system has /usr/local/bin/a2p command available
* I built a newer version of perl; now one perl has App::a2p and the other doesn't
* This version of awk does not use App::a2p, it only runs the command a2p
* The SANITY check was not sane because both perls are able to run a2p, but the awk wrapper refuses on one perl because of App::a2p check
* Delete the SANITY code; there is already a check if a2p fails to run so this is good enough
* Also remove the too-helpful error check for long options; users will still see "unknown flag" error which clearly communicates that the option can't be used
* With patch applied, both perls can run my trivial awk script
```
%cat test.awk
BEGIN {
printf("\n");
} …
```
> awk refuses to use a2p

- bin/awk
* awk wrapper doesn't clean up after itself and I am left with all these spam files... a2pin.6695 a2pout.6695 a2pin.6697 a2pout.6697 a2pin.6699 a2pout.6699 a2pin.6702 a2pout.6702 a2pin.6951 a2pout.6951 a2pin.6953 a2pout.6953
* unlink before exit is better, whether or not the files are written in /tmp
> awk: remove temporary files

- bin/printf
* Rewrite printf command to not use eval()
* Format string is parsed into a list of literal substrings and format specifiers
* The print loop executes at least once; missing argument are implied as 0 for numbers and '' for strings
* Remove RESTRICTIONS section from pod now that we check input and don't allow arbitrary things into eval()
* Previous version could be exploited like this: perl printf '";;CORE::dump();";dumpassaasdasd'
Aborted
* test1: perl printf 'hey%d' --> implicit argument of zero, "hey0"
* test2: perl printf 'hey%d' 1 --> explicit argument, "hey1"
* test3: perl printf 'hey%d' 1 2 3 --> format string applied 3 times, "hey1hey2hey3"
* test4: perl printf '%20s:%-20s' pri ntf --> length specifier with string
```
pri:ntf                 
```
* test5: perl printf --> error, at …
> printf: remove eval

- bin/spell
* On OpenBSD and NetBSD I run "spell -d PATH" if I want to use a custom dictionary [1] [2]
* FreeBSD and solaris9 do not have the -d option, but define -b as a flag (not option with value) meaning to use the british dictionary not the american one [3] [4]
* Remove -b instead of re-defining its meaning; introduce -d instead
* Allow a space between -d and the file, as supported by existing -s option
* Update pod text and usage string
1. http://man.openbsd.org/spell
2. https://man.netbsd.org/spell.1
3. https://man.freebsd.org/cgi/man.cgi?query=spell&apropos=0&sektion=0&manpath=FreeBSD+14.0-RELEASE+and+Ports&arch=default&format=html
4. https://shrubbery.net/solaris9ab/SUNWaman/hman1/spell.1.html
> spell: compatible -d option

- bin/printf
* When testing against bash-builtin and GNU version of printf command, octal escapes allow 3 digits but input >255 are interpreted as mod-256 (e.g. \400 wraps around to \0)
* For hex escapes, only 2 digits are allowed so entering input above FF is not possible anyway
* The hex digits can be mixed case, but the "x" prefix must be lowercase
* test1: terminate word list with NUL: perl printf '%s\0' over here
* test2: windows line-ending string with hex: perl printf 'hey\xd\xa'
> printf: hex & octal escapes

- bin/whois
* Print usage string for incorrect options; previously invalid option -X was treated as a domain name
* Write "\r\n" to socket, not "\n\r" (hint taken from NetBSD code)
* Don't connect to whois server if no domain arguments were provided; print usage string in this case
* Make the different whois server options mutually exclusive 
* Test: I still get a positive response for "perl whois installgentoo.com"
> whois: fail for bad options & no args

- bin/tac
* tac -S option takes a number of bytes to read; this option does not exist in GNU version
* It doesn't make sense for -S value to be negative or zero so enforce a minimum of 1
* Printing usage string seemed slightly helpful, so create a usage() function
* The -S option might provide no benefit to the user and could be removed in future
> tac: validate input for -S option

- bin/spell
* The dictionary file is read into memory before taking input list of words to check
* Fail early in extreme case where no words were read from dictionary, e.g. touch empty && spell -d empty
* Avoid open() on a directory, e.g. spell -d ..
> spell: fail for empty dictionary

- bin/kill
* Avoid passing non-numeric pids to kill()
* Printing "Can't kill a non-numeric process ID" is not helpful because kill can accept many pids and the error doesn't indicate which pid is bad; print a helpful error instead
* This was found when testing against the bash-builtin kill
> kill: validate pid

- bin/printf
* I discovered incorrect looping behaviour for: perl printf a b c
* In the loop, b and c are never shifted off ARGV list, so it never terminates
* The 1st argument is interpreted as the format string, but it contains no format specifiers
* bash-builtin printf, as well as GNU and OpenBSD versions agree that arguments b and c should not be used
* On OpenBSD there is no pdksh builtin printf to test against
* Text in the standards document is not very helpful: "If the format operand contains no conversion specifications and argument operands are present, the results are unspecified." [1]
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/printf.html
> printf: ignore args case

- bin/whois
* NetBSD version of whois takes multiple domain names
* NetBSD version does a new connection for each domain name, so we can follow this [1]
* The query submitted by this version is not correct when multiple names are specified
* With this patch I can successfully query 2 domains in one go
1. http://cvsweb.netbsd.org/bsdweb.cgi/src/usr.bin/whois/whois.c?annotate=1.36.30.1
```
%perl whois installgentoo.com omledom.com   # before patch
No match for "INSTALLGENTOO.COM OMLEDOM.COM".
```
> whois: submit new query per domain

- bin/comm
* GNU and OpenBSD versions of comm accept this usage: "comm -1 -2 -3 -- -file1 -file2"
* This version only worked if options were grouped as -12 or -123
* Conversion to getopt allows grouped and ungrouped usage, and supports '--' terminator (useful for files starting with dash)
* COL list controls which columns are suppressed, so $COL[1] is false if -1 is given, etc
> comm: don't enforce grouped options

- bin/col
* I observed strange output from col when the input file was large
* Finally I discovered the issue is related to code that runs when the buffer fills up
* The input loop adds lines to a buffer which are printed in a subsequent loop; however, the buffer code triggers early printing within the input loop
* I could reproduce error earlier by setting a smaller buffer size with -l:  "perl col -l 5 ching"
* The pod manual says -l buffers at least n lines of input
* I propose ignoring -l and buffering the whole file, this at least doesn't result in a runtime error
* Correct buffer management code could be investigated later
> col: buffering code broken

- bin/whois
* I didn't notice that strict was not declared; when adding it, a declaration for $line was needed
* While here, prefer error string from IO::Socket over $! if connect fails (same change proposed for bin/mail)
```
%perl whois -h 127.0.0.1 good.juan.com
127.0.0.1: IO::Socket::INET: connect: Connection refused
```
> whois: add strict

- bin/mail
* When sending a mail message we need to connect to a relay host
* Append the system error string to the nice error in $emesg, which is already terminated with a newline
* This makes the error take up 2 lines but I think it's still better because we can see more specific error info
```
%RELAYHOST=127.0.0.1 perl mail go@google.com # now shows...
Unable to connect to the specified relay host
IO::Socket::INET: connect: Connection refused
```
> mail: connect() error tweak

- bin/whois
* A correctly formed whois query will contain non-whitespace characters so catch invalid input before connecting to whois server
* Example bad input: perl whois ' '
> whois: forbid query containing only whitespace

- bin/glob
$glob_expr assigned but not used in match_glob()
> glob: unused variable

- bin/arithmetic
* regex m/\D/ didn't match on empty string, so previously if I typed enter instead of a number it was treated as a wrong answer
* It's more correct to treat empty line as bad input and prompt again for a number
* While here, make the input loop more user friendly by trimming leading and trailing spaces before testing for m/\D/
> arithmetic: empty answer is not a number

- bin/ed
* An empty filename (ed '') is incorrect usage and should show an error
* GNU ed attempts open() and fails; OpenBSD ed fails with "invalid filename" error and avoids open() (follow OpenBSD)
* In edEdit(), $filename could still be undefined in default case because $RememberedFilename is undefined when starting ed with empty buffer
* The code was a bit redundant because the value of $RememberedFilename was saved into itself again
* Save $RememberedFilename only if filename is taken from $args[0]
> ed: input filename validation

- bin/bc
* Remove #ifdef checks around $yydebug usage
* Toggle parser debugging by running "bc -y"
* Follow the pod text and don't look at environment variable YYDEBUG to determine whether to run in -y mode
* Toggle output state machine debugging by running "bc -d"
* Some statements run under "bc -d" need Dumper() imported into namespace; previous commit broke that
* Simplify variable init in yyparse(); write $yyss[$yyssp] as $yyss[0]
> bc: unifdef YYDEBUG

- bin/tail
* GetOptions() return value was not checked
* Symbolic exit codes were already declared so use them more consistently -- this usage() takes an exit code parameter
> tail: die for bad options

- bin/file
* If an invalid option was given along with a file argument, the option was ignored (perl file -x FILE1)
* Follow GNU file by printing usage and exiting in this case; nothing should be processed
* While here, re-order declarations so pragma appears above library modules
> file: die for bad options

- bin/asa
* The 1st two regex in run_file() handled empty lines and lines not starting with 1, 0, '+' or '-'; i.e. both regex were run together resulting in output of "\n"
* Structure run_file() differently to avoid running every regex when a single lookup in a mapping table is good enough
* The patched version appears to produce the same output as previous version
> asa: avoid repeated regex

- bin/mkdir
* Multiple lazy-loads of File::Basename in the one script seemed a bit overcomplicated; just import basename() and dirname() so they can be used as needed
* When I typed a wrong option the entire manual was printed when I only needed to know the usage, not the license details; reducing the verbose level of pod2usage() helps this
> mkdir: style patch

- bin/bc
* GNU and OpenBSD versions support the following usage: "bc -- -a" to open a filename starting with a dash
* Teach option parser about '--'
* Treat argument -a as an option instead of as filename otherwise; -a is not supported so print a usage string and exit
> bc: fail for bad options

- bin/fish
* I am lazy to type shift+a for ace; do what I expect whether I type A or a
* This could've been done in less code, but I wanted a table of valid card names instead of using grep()
* Catch^C^Cgoing fish is so much more fun now
> fish: fold case

- bin/mkdir
* Follow GNU & OpenBSD mkdir by failing early if the mode string (-m option-argument) was empty
* Previously -m '' was interpreted as -m 0
* Make one error message easier to read
> mkdir: make empty mode an error

- bin/ed
* Similar to previous patch in edEdit(), avoid assignment of $RememberedFilename into itself if $args[0] is not set
* The empty string check for $args[0] in edEdit() is not needed here because the input was already passed through the main parse-commads regex
> ed: simplify edWrite()

- bin/bc
* In yyrule list, strings were not escaped properly
* Use yyclearin() where possible to reset $yychar
* Eliminate #line directives which cause perl debugger to print misleading line numbers
* In grammar rule 84 (expr=IDENT), access $yyvs[$yyvsp] directly instead of accessing a hash inside it which doesn't exist (this is consistent with rules 86,87,etc
* Replace string-eval with block-eval in main()
> bc: add strict

- bin/split
* Rewrite validation routine to use only 1 regex, which extracts the number prefix and optional multiplier suffix
* Remove warnings for users
* The following are valid for -b argument: 1, 1k, 1K, 1m, 1M (not 0 and not empty string)
> split: refactor get_count()

- bin/awk
* Take a hint from bin/find program, and use File::Temp instead of manually opening TMPIN and TMPOUT
* File::Temp also handles removal of the files, so the END block gets simplified
* Brace filehandle argument in one instance of print()
* "perl awk -f hello.awk" still produced the same output with patch applied
> awk: now with File::Temp

- bin/fish
* Declare a variable $hand for current player's hand
* If we init DECK from the hash keys, entropy is added prior to the shuffle function because perl changes the order of keys for each invocation
> fish: delete duplicate code

- bin/bc
* Found by perlcritic
* For instances of "my $val", it is already declared above exec_stmt()
* $code wasn't needed at top level scope
* Also one "$" wasn't escaped in ```@yyrule``` declaration
> bc: remove alias variables

- bin/ed
* Fix the assumption in edEdit() that >0 bytes will be read from input file; it might be empty
* Error discovered with "perl ed some.txt" then "1r EMPTYFILE" ... Modification of non-creatable array value attempted, subscript -1 at ed line 722.
* Follow GNU ed and print the number of characters read (0)
* I found that the default calculation of $CurrentLineNum was correct for all cases of insert mode, so use that
> ed: runtime error on empty file

- bin/bc
* When temporarily enabling warnings in bc I observe warnings for incorrect use of "next"
* Function yy_err_recover() jumped to a label outside of itself, within yyparse()
* yyparse() was structured so that it first initialises flags then enters main loop
* Jumping back to yyparse() was unsafe because the flags would all be cleared again, including $yyssp (yy_err_recover() already adjusts $yyssp)
* Clear flags before calling yyparse(), and let yyparse() enter the loop immediately so that it's safe to call it from yy_err_recover()
```
%perl bc # before patch
4++
line 1: syntax error
Exiting subroutine via next at bc line 1387, <STDIN> line 1 (#1)
```
> bc: eliminate jump into yyparse()
