README.pod
Sorry for sending two PRs on the same thing - this is another location where I found the same grammar mistake as my last PR.
=> Fix another minor grammar error

Makefile.PL
This is a trivial change to some bad grammar in Makefile.PL.
=> Minor syntax fix

bin/apply, bin/arithmetic, bin/basename, bin/cat, bin/chgrp, bin/chmod, bin/chown, bin/dirname, bin/false, bin/head, bin/ln, bin/mkdir, bin/moo, bin/morse, bin/rain, bin/random, bin/rmdir, bin/touch, bin/true, bin/which, bin/yes
=> Updated ancient email address

Makefile.PL
I should have looked for comments before submitting a PR. This one should be after a successful rebase.
=> Fix windows build

Makefile.PL, bin/echo, t/echo.t
My first shot at converting a tool to a modulino writing some tests for it.
=> turn echo into a modulino and add some tests

bin/units
Added standard sections and copied content from [FreeBSD's units][1].
[1]: https://www.freebsd.org/cgi/man.cgi?units
=> Add documentation to units utility

CONTRIBUTING.md
Hi brian!
This is part of the CPAN pull-req challenge. I hope to have something more substantial soon, but I wanted to keep my pull-req single-scoped per the CONTRIBUTING.md.
Please consider merging it - all tests pass.
=> Correct "you" to "your" in the CONTRIBUTING.md .

bin/addbib, bin/apply
to clear kritika/PerlCritic violation
=> enable warnings in apply

bin/ppt
Hi @briandfoy 
Please review the PR.
Many Thanks.
Best Regards,
Mohammad S Anwar
=> Added strict pragma to bin/ppt.

bin/arch, bin/cmp
Hi @briandfoy 
Please review the PR.
Many Thanks.
Best Regards,
Mohammad S Anwar
=> Added strict pragma.

t/cat.t, t/compile.t, t/find.t, t/sort.t
Just as a by-the-by, a lot of this wouldn't be necessary if the scripts were all modulinos (#85) as testing would be much easier.
=> Fix tests for Windows, also "perl in space"

bin/rot13
Created rot13 filter script
Checked version installed from bsd-games, and it ignores any arguments.
=> Check-in initial version of rot13

bin/whoami
Co-authored-by: Michael Mikonos <Michael.Mikonos@tpgtelecom.com.au>
=> Simplify whoami exit logic

bin/cat
=> cat should exit with 1 if there's an error

bin/nl
=> Fix exit code to nl

bin/bc
Co-authored-by: Michael Mikonos <Michael.Mikonos@tpgtelecom.com.au>
=> bc reversed the array index and value

bin/addbib, bin/asa, bin/clear, bin/colrm, bin/mkfifo, bin/tsort, bin/uname
I've emailed Jeffrey to see if he agrees with this, but maybe just mentions @jsh will work. Jeffrey - if you want some other license just let me know and I'll fix it up.
=> Add a perl license to the tools from Jeffrey S. Haemer

MANIFEST, bin/hexdump
* reference for default output: hd command on linux
* character-dump option -c, based on linux hexdump
* reverse hexdump option -r, based on xxd command
=> hexdump tool proposal

bin/rev
* Currently this code supports only one file argument
* Implement what the manual says: read stdin if no file argument is provided
* Also fix issue where newlines get swapped to the beginning of the line (split before chomp)
* Successful exit code at end of program
* Remove code that treated ARGV elements as strings to be reversed
=> rev: support reading from stdin

bin/base64, bin/hexdump
These were the only two file actually missing a metadata section.
=> Add metadata POD to base64 and hexdump

bin/base64
* I am still reading through how various commands are treating directories
* Future changes: possibly add special handling for files containing garbage (non-base64 characters)
=> base64: fail early for directory argument

bin/chmod, bin/install, bin/mkdir, bin/nl, lib/PerlPowerTools/SymbolicMode.pm
=> (WIP) Recover SymbolicMode.pm 

bin/hexdump
* Same problem as found in bc; truth test prevents file 0 from being opened
* I found an instance where $Program should be used
* Add missing license
=> hexdump: filename 0 is not special

bin/printenv
* SYNOPSIS: make it clearer that "name" argument is optional
* As done in env command, remove misleading ENVIRONMENT section
=> printenv: pod tweak

bin/arithmetic
* Validation code for number range option -r was looking at the wrong variable name
* The intent of the code is for only validated input to be assigned to $range
=> arithmetic: -r validation

t/date/date.t
https://github.com/briandfoy/PerlPowerTools/issues/505
=> fix fox  Unquoted $^X in date.t #505

bin/fish
The new card taken from DECK is pushed into the player's hand unconditionally
=> fish: simplify draw()

bin/moo
* Introduce a regular usage() function
* Size of 0 is still not allowed (the puzzle must have 1 or more numbers)
=> moo: usage() > warn("Usage")

bin/tac
* -B flag can be grouped with -b and -r (all may be provided together)
=> tac: group optional flags in usage string

bin/xargs
Quick'n'dirty pass at documenting the features of this xargs.
The -I option appears to work but I'm not familiar with it.
=> xargs: initial manual

bin/ls
* Now users can inspect installed without having to read source
* Based on a recent patch to bin/cat
=> ls: add --version

bin/mkdir
* Sync usage string with BSD version
* Make --version flag work as done in other scripts
=> mkdir: add --version

bin/col
* --version flag is supported in other scripts so add it here too
* style: $_  can be omitted for substitution
=> col: add --version

bin/mail
* When mail is waiting for the next input I can hit ^D to terminate the program [1]
* Tested against OpenBSD
1. https://pubs.opengroup.org/onlinepubs/7908799/xcu/mail.html
=> mail: EOF terminates program

bin/bc
* Convert the functions e(), j() and l() to builtin
* j() is actually the standard jn() function
=> bc: unhook mathlib

bin/dc
* Enabling strict will help catch some errors for future changes to dc
* Add explicit defined() checks for result of readline (suggested by diagnostics.pm when temporarily enabled)
=> dc: add strict

bin/fish
* When redirecting input from a file I noticed that fish reads past eof in the playguess() prompt loop
* This change is similar to commit 57c92da82e5a225aad7f6f31aac5479e520415ad for bin/moo
```
%printf "hohoho\n" | strace perl fish # read() retval 0 ignored
...
read(0, "", 8192)                       = 0
write(1, "You ask me for: I have 7 cards i"..., 43You ask me for: I have 7 cards in my hand 
) = 43
write(1, "There are 38 cards remaining in "..., 42There are 38 cards remaining in the stock
) = 42
write(1, "\n", 1
)                       = 1
read(0, "", 8192)                       = 0
write(1, "You ask me for: I have 7 cards i"..., 43You ask me for: I have 7 cards in my hand 
) = 43
write(1, "There are 38 cards remaining in "..., 42There are 38 cards remaining in the stock
) = 42 …
```
=> fish: loop on eof

.github/bin/labeler, .github/workflows/new_pull_request.yml, bin/glob, t/glob/glob.t
Part of #965. This is a wrapper around File::Glob
=> Reimplement glob

MANIFEST, bin/ls, t/bc/input.t, t/ls/ls.t, t/rm/run.t
=> Respect symlinks in bin/ls
