briandfoy/PerlPowerTools

bin/touch
* Option -r takes a file argument to copy stat() data from
* Fix issue where filename of "0" is ignored because perl treated it as no-r-argument-given
=> touch: -r argument truth check

bin/printf
* Follow GNU printf command and attempt to show the bad format specifier which caused an error
* Example: "perl printf '%9 -asd'" now reports "printf: invalid format: '%9'" instead of just "internal error"
=> printf: descriptive error message

bin/shar
* shar from GNU sharutils can work with a filename with spaces, but this version can't
* Address this by quoting the filename passed to mkdir and sed
* It's not harmful to quote files which don't have a space
* While here, print an error if close() failed
```
%perl shar '0 1' > new.shar
%sh new.shar
x - 0 1
sed: can't read 1: No such file or directory
```
=> shar: handle filename with space

bin/kill
* Only one regex match is needed to extract a value from $ARGV[0]
* test1: perl kill -trap $$
* test2: perl kill -9 $$
=> kill: less regex

bin/cmp
* Non-standard -? option doesn't exist in BSD versions of cmp either
* For systems with no perldoc command installed we provide a bin/perldoc, so running "perl perldoc cmp" is preferred (i.e. the same way to show the manual for maze and other programs too)
=> cmp: remove -?

bin/rmdir
* Avoid calling rmdir() on file arguments unless stat (via -d ARG) indicates the file exists and is a directory
* Technically rmdir() would fail anyway, but this seems more defensive
* Symbolic exit codes were already declared here, so use them
=> rmdir: stat file first

bin/mkfifo
* Test case: "mkfifo A B C", when A & B exist but not C
* On Linux and OpenBSD, an error is printed for A and B, then C is created; the program terminates with a non-zero exit code
* Treat mkfifo() error for one file argument as a warning and not a fatal error to allow subsequent args to process
* As done in bin/rmdir do a stat() (via -e ARG) before calling library function; no command option exists for clobbering existing files
=> mkfifo: continue on error

bin/pwd
* "perldoc Cwd" explains that getcwd() can return undef on error, so handle this instead of printing "\n"
=> pwd: print error for getcwd() failure

bin/du
* Rename usage function for consistency with other commands
* Passing an exit-code param is overkill; just exit(1) because 1 is always passed
=> du: s/usage_exit/usage/

bin/touch
* Fix typo in pod and one in error string
* Replace sysopen+fcntl with IO::File->new()
* Add return-value check for close()
=> touch: fix typos

bin/file
* The usage "file -" is allowed for GNU and OpenBSD: explicitly read stdin
* The usage "file" with no argument is not valid; stdin is not read implicitly
* This version doesn't support "file -", but the argument loop terminates and results in exit(0)
* Using die for this not-implemented error results in non-zero exit code, which is more compatible with the standard[1]
1. https://pubs.opengroup.org/onlinepubs/007904975/utilities/file.html
=> file: avoid exit(0) for stdin case

bin/tar
* "perl tar" with no argument would read stdin but this is not desirable
* GNU tar prints usage in this case, and OpenBSD tar reads default tape device
* Make the file option (-f) mandatory; follow OpenBSD version where "tar -f -" indicates an archive is read from stdin
* Re-enable strict
=> tar: don't read stdin by default

bin/ed
* The program crashes when fed unexpected input after the initial "s" command
* I found this when investigating a capture-variable-outside-of-condition warning from perlcritic
* $char is the 1st character after the "s"; normally it would be "/" as in s/old/new/
* Return early if $args[0] is an empty string
* Adding eval guard around the confusing regex constructed from $char prevents the error
* Possibly the code could be changed later to enforce that $char is '/'
```
perl ed -p 'ed% ' a.c
63
ed% 1
ed% s*asaaa*
Unknown verb pattern '' in regex; marked by <-- HERE in m/((*) <-- HERE [^"*"]*(*)[^"*"]*(*)?)([imsx]*)/ at ed line 519, <> line 2.
```
=> ed: runtime error in edSubstitute()

bin/bc
* Catch illegal division before it happens
* In bignum mode an error would not be thrown previously for this case; testing with is_zero() resolves this
* I tested this in interactive mode for -b and not-b; the die() is caught so bc does not terminate---this is consistent with GNU bc
=> bc: divide by 0

bin/diff
* Test case: "touch empty && perl diff empty empty"
* Program seems to hang; ctrl-c in perl debugger hints that we are stuck in Algorithm::Diff::traverse_sequences()
* Program grew to use >2GB of memory before I killed it
* traverse_sequences() doesn't seem to handle when both lists of input lines are empty (I didn't bother investigating why)
* Put a sanity check before diff()+traverse_sequences() are called; input files are read in total before diff() so the size of line list is know
* I also tested a non-empty file against an empty one
=> diff: empty files are the same

bin/ed
* Difference observed when testing against GNU ed and OpenBSD ed
* If current line doesn't contain "A", the command s/A/B is expected to generate the error "no match"
* This error happens for searches (? and /), but not for s///
* The logic in edSubstitute() was wrong because LastMatch assumed the current line was a positive match before the loop starts
* The corrected version sets LastMatch only if a match occurred
=> ed: no-match error for s///

bin/cal
* Example scenario: I type "perl cal -r", expecting it to work like "cal -r" on NetBSD
* I get a message that -r is invalid. Ok
* I get a message that cal is part of perl power tools; I don't care, I just want to see the valid options
* Remove the introductory text from display_help() and prefix the usage string with "usage: "
* The distribution info is still available at the bottom of the manual (perl perldoc cal)
=> cal: display_help() tweak

bin/bc
* Entries in sym_table hash need to have type & value
* When investigating a warning for "eq on undefined value" on L2400 I noticed that the newly created sym_table entry needs a type of "var" (this code handles auto-assignment of zero to variables)
* The hint came from further down in the code, where array values are initialised to zero (virtual 'p' instruction)
* Also remove the C preprocessor declaration of YYBYACC which was not referenced anywhere
=> bc: symbol table correction

bin/bc
* Variables in bc are can have a fractional part
* A variable can be used as an array index
* Discard the fractional part of index, so 3.3 is equivalent to 3
* Negative array index is still not allowed
```
%perl bc 
>>> ary[3.3] = 2
>>> ary[3.3]
2
>>> ary[3]
2
>>> a = 3.4 
>>> ary[a]
2
quit
```
=> bc: standard array index

bin/banner
* Program was previously converted to use DWIDTH constant, but the init code for printmask list can use it too
* Explicitly convert values to int which will be used as array index; some elements in printmask list are implicitly 0
* Tested with "perl banner -w 40 perl2u"
=> banner: magic number

bin/col
* No need to init $opt_f; it is already false
* Avoid setting $row negative instead of correcting it afterwards
* Move default exit() above print_line() sub
=> col: small tidy

bin/pig
* -v flag was mentioned in usage string but not in SYNOPSIS
* Follow what was done in bin/rev: remove -v and support --version by declaring VERSION_MESSAGE
* Now usage string and SYNOPSIS agree (--version is not explicitly mentioned)
=> pig: support --version

bin/cut
* Program flow is slightly clearer by exiting at top level, not within handle_b() and handle_f()
=> cut: less exit()

bin/units
* --warranty and --copying are no longer options; if this was a good idea it would be included in every single perl script and not just this one
* Replacing the statement before END marker prevents the warning "Useless use of a constant ("PerlPowerTools::units") in void context"
* Fix a typo in pod manual
=> units: remove nested GPL document

bin/units
* Remove $read_unittab from read_unittab()
* Also, call usage() directly in process_args() so the variable $USAGE is no longer needed
=> units: unused variable

bin/bc
* Global $YYMAXDEPTH was not referenced anywhere
* While here, remove the $yynerrs counter variable which was incremented in YYERROR() and yyparse() but never used for anything
=> bc: unused variable

bin/spell
* Remove global $alt_dict_file
* If the current argument doesn't start with a "-", terminate the option parsing; this avoids copying temporary files list back into ARGV
=> spell: unused variable

bin/nl
* Linux and OpenBSD don't support nl -V for displaying version
* Standards document doesn't specify a version flag[1]
* GNU nl has --version, which can be supported here as done for bin/rev
1. https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/nl.html
=> nl: retire -V

bin/xargs
* Test cases: "perl xargs" and "perl xargs ls"
* Text entered manually:
1
2
3
^D
* xargs correctly runs a program (echo or ls) on 1, 2 and 3, then incorrectly waits to read more data from stdin
* Checking eof() after each read indicates whether xargs should terminate (no more args will follow so the program should not loop)
* Tweak usage string to clarify that "prog" is optional (echo is the default)
=> xargs: eof ignored

bin/cut
* The substring length calculation in handle_b() wasn't correct in all cases
* If start==end, then length==1
* Pass parameters to handle_b() and handle_f()
* Use defined() to test for presence of command options; 0 should not be ignored
* test1: "perl cut -b 2-3 a.c" -> chars 2-3
* test2: "perl cut -b -3 a.c" -> chars 1-3
* test3: "perl cut -b 10 a.c" -> char 10
* test4: "perl cut -f 1,2 -s  -d ' ' a.c" -> fields 1&2, delimited by space, ignoring lines without a space
=> cut: fix substring for -b flag

bin/cut
* These 3 test cases agree between GNU and OpenBSD, but this version of cut didn't work properly
* Multiple bytes can be separated by commas
* A negative number means a range  1-x
* Two numbers joined by dash means a range x-y
* If the same byte number is repeated, only print it once
* test1: "perl cut -b 1,1,1,3,1 a.c" --> interpret as -b 1,3
* test2: "perl cut -b 1,1,1,-3,1 a.c" --> interpret as -b 1-3
* test3: "perl cut -b 1,1,1,3,2-4 a.c" --> interpret as -b 1-4
=> cut: field list semantics for -b

bin/pom
* Deliberate crash1: COLS=-1 perl pom -e Out of memory!
* Deliberate crash2: LINES=-1 perl pom -e Can't take sqrt of -0.5625 at pom line 298.
* For crash1 I noted the value of $terminal_width was 4294967292, i.e. sign-extension of -1
* Avoid these errors by displaying a "bad terminal width" or "bad terminal height" error instead
* Make use of checknum() which is already able to catch negative numbers, and other bad input
* Extra change: convert aspect ratio to a constant
=> pom: avoid using bad environment values

bin/nl
* Usage string incorrectly mentioned "-l num", but this results in "unknown option" error
* GNU and OpenBSD versions support -l; it could be added to this version later if desirable
=> nl: -l option unsupported

bin/units
* Usage in SYNOPSIS was correct
* usage1: no command args; all input is entered after prompts
* usage2: two unit names are given as arguments, e.g. "perl units cm inch"
=> units: correct usage string

bin/split
* The default branch is really for -l flag, i.e. line-based split mode
* The user doesn't need to type -l if they are happy with default of "-l 1000"
* Only one of -b/-l/-p is allowed
=> split: dead code

bin/rm
* Don't ignore bad options
* e.g. for usage "perl rm -x f1", file f1 should not be removed
* Reduce verbose level of pod2usage() so only SYNOPSIS and Options are displayed
* I found this when testing against GNU rm
=> rm: print usage for bad options

bin/lock
* Reduce code by making usage() not return; this convention is followed by other scripts
* While here, correct spelling errors in pod
=> lock: usage() exits

bin/ar
* Don't attempt to open an archive file if no archive was specified (all valid usages require an archive to operate on)
* exit(1) in usage() to indicate that something went wrong (matches GNU version)
=> ar: sanity check archive argument

bin/cp
* Preserve control structure of returning from run() by passing NOEXIT to pod2usage()
* Remove empty line in SYNOPSIS and Bquote which didn't look right in the pod2usage() output
* Tested for "perl cp -x" and "perl cp src"
=> cp: print usage for bad options

bin/ed
* Replace large if-else block with a more declarative lookup table
* Some helper functions were needed for functions which implemented multiple commands (e.g. edHelp() implements 'h' and 'H')
* Add missing default "else", i.e. print a warning if edParse() was successful but the handler didn't exist in cmdtab hash
* No intended functional change, aside from the extra bad-command warning
=> ed: refactor command tree

bin/factor
* Numbers with leading '-' are not accepted by this version
* I tested GNU factor and it didn't accept negative numbers either
* Text about BSD manual being incorrect might have been relevant 20 years ago, but current OpenBSD manual states that numbers may only have a leading '+' [1]
1. http://man.openbsd.org/factor
=> factor: pod update

bin/bc
* YYERROR() was an alias for yy_err_recover()
* YYERROR() was only called once, so call yy_err_recover() directly
* When testing, I temporarily forced $return=2 instead of working out how to trigger it
=> bc: remove alias sub

bin/grep
* The following correct usage was not accepted: "perl grep 0 file"
* Within parse_args(), $opt{e} was initialised to 0 but that is confusing because 0 could be a pattern; instead set it to empty string
* First check if $opt{e} and use it if not empty
* Expect pattern to be the next ARGV element
* Raise error via usage() only if there were no remaining ARGV elements (previously usage() was called if it was 0, i.e. false)
=> grep: pattern of 0

bin/join
* Usage string is still printed for -h with this patch
* When looking at POD I discovered the SYNOPSIS fails to mention -j option, but address this later
=> join: remove non-standard -h flag

bin/wc
* Follow GNU and OpenBSD versions by doing non-zero exit() if one or more file arguments cannot be processed
* Add return check for close() as done in other scripts
```
%echo $BASH_VERSION
5.1.4(1)-release
%set -e
%perl wc -l not-exist
```
=> wc: indicate error in exitcode

bin/install
* In install_dirs() the final loop calls modify_file() for each directory
* modify_file() is skipped via "next" if $implied is true, so the call to modify_file() doesn't need its own guard
* modify_file() will not run if $Unix is false, so the loop can be bypassed
=> install: remove extra check for $implied

bin/diff
* -q flag means no diff output is printed, so effectively the diff type (format) has no meaning
* OpenBSD diff ignores  -e -n -u -f -c formatting flags if -q is given; do the same here with exception of -n which is not supported
* output_diff() doesn't really output a diff for ed diffs (but it does for reverse-ed diff)
* Make the calling code for output_ed_diff() more obvious that it is not called for reverse-ed diff type
* test1: no output difference for ed and reverse-ed diffs compared to previous version
* test2: no errors raised for... for opt in c e f u; do perl diff -${opt} -q diff.new diff; done
=> diff: compatible -q flag

bin/ls
* get_columns() has the side effect of running external commands via unix() function
* Not all modes of ls need the value of $WinCols, e.g. "ls -1" and "ls -l"
* Init $WinCols the 1st time it is used within List()
* "defined" guard is there because List() can be called repeatedly, e.g. "ls dir1 dir2"
=> ls: conditional get_columns()

bin/sum
* Program name variable was already declared and used in usage string
* While here, avoid calling into algorithm function for directory arguments
=> sum: more $progname

bin/ln
* Move version-info line out of usage() into VERSION_MESSAGE() as done in other scripts; this allows Getopt::Std to handle --version flag
* While here, spell a word correctly in pod and spell a variable differently to avoid conflict with global ($target)
=> ln: support --version

bin/bc
* When adding previous commit to avoid divide by zero, mod 0 was missed
* Patch tested under default mode and bignum mode (bc -b)
```
a=123
b=0
a%b
```
=> bc: mod zero

bin/ed
* If I open a file and edit it, the $NeedToSave flag is set
* If I attempt to edit a new file with "e" command, the new file was opened and read into a temporary buffer before validation based on $NeedToSave executes
* I noticed this because I observed a "cannot open file" error when typing a nonexistent filename, instead of a "buffer modified" error
* When editing a new file with "E" command the $NeedToSave flag is not checked, but for "e" command it is
```
%perl ed a.c    # before patch
63
P
*1d
*e aa.cc
aa.cc: No such file or directory
?
*h
cannot open file
*
```
=> ed: edEdit() validation

bin/bc
* A previous commit replaced a goto into yyparse() with a call to yyparse() but this introduced an infinite loop for a file with a syntax error
* yy_err_recover() returns bool; returning 1 instead of calling yyparse() again allows yyparse() to itself return and break out of "yyloop"
* The pattern of return(1) from yy_err_recover() was already established; this patch just makes it more consistent
* Regarding the removed yyclearin() call, that would be called from main()->clear_flags() before yyparse() would be called again
* test1: echo '1++' > A.bc && perl bc -y A.bc
* test2: echo '~' > B.bc && perl  bc -y B.bc
```
%echo '1++' > A.bc && perl bc -y A.bc   # before patch
yydebug: state 1, reading 0 (end-of-file)
yydebug: state 1, reducing by rule 2 (stmt_list_exec : stmt_list_exec …
```
=> bc: yyparse() loop regression

bin/ed
* The previous empty-file guard added to edEdit() wasn't good enough
* Before returning from edEdit() the buffer was not replaced with an empty buffer
* Line 1 is no longer a valid address after "e empty" command
```
%perl ed a.c    # before patch
63
P
*1
*e empty
0
*1
*q
```
=> ed: edit empty file

bin/cmp
* FreeBSD, NetBSD & OpenBSD list usage strings make it clear that flags -l and -s are not compatible
* Code can be simplified slightly by adopting a compatible usage string
=> cmp: sync usage string

bin/cut
* Technically the inclusive byte range of 2-2 is a single byte
* When testing against GNU and OpenBSD versions, the usage of "cut -b 2-2" is allowed and interpreted as "cut -b 2"
* This version raised an error previously but it's more compatible to allow it
=> cut: allow -b range of 1

bin/join
* The meanings of options -a and -v are incompatible
* Usage string from standards document indicates -a OR -v [1]; this version prints a compatible usage string
* Follow OpenBSD version and fail early if both -a and -v are given
1. https://pubs.opengroup.org/onlinepubs/009604599/utilities/join.html
=> join: -a or -v

bin/patch
* Make the regular Patch::end() aware that print_tail() should not be called for ed diffs
* Now the subclass definition of Patch::Ed::end() can go away
=> patch: single definition of end()

bin/ed
* Line addresses can be inferred when entering a range with a comma
* An explicit range has two addresses, e.g. "1,2" or "4,$"
* If first address is not given it is always 1
* If first and last address are both not given, last address is $ (last valid line address)
* I discovered this when testing against OpenBSD and GNU ed
* test1: ",n" --> interpret as 1,$n
* test2: ",5n" --> interpret as 1,5n
=> ed: inferred range commands

bin/du
* du had a documented bug where '/' was the path separator
* As done in other scripts, make use of catfile() when joining a directory name to a filename
* This works the same on my Linux system, but in theory it will work better on windows
* catfile() can handle directory names with a redundant separator at the end, so a conditional expression is not needed
* Remove global variable $dirsep
=> du: remove unix path assumption

bin/expr
* Check for 0 before divide and modulo operations
* Add newlines to die() to prevent line numbers appearing in "syntax error" messages
=> expr: avoid divide by zero

bin/grep
* Previously it wasn't possible to show $VERSION info
* While here, sync usage string with SYNPOSIS in pod
* Also add dashes to the options in the extended usage description for clarity
=> grep: add --version

bin/cat
* Listing version number in the usage string was a bad idea
=> cat: add --version

bin/grep
* Move regex code for -v flag down to avoid modifying patterns list for fixed-string mode (-F)
* Fold patterns list to lowercase for -i flag and perform substring match against lc(LINE) with index()
* For -v mode (negated match), test for index() retval -1
* Always do quotemeta() on pattern list for fixed-string mode so a quote (') can evaluate correctly in $match_code
* test1: "perl grep -F alice names" --> no match because my names file had Alice
* test2: "perl grep -Fi AlIcE names" --> now Alice matches
* test3: "perl grep -Fv joe names" --> non-joe
* test4: "perl grep -Fiv JOE names" --> non-joe2, fold case (excludes joe and Joe)
* test5: "perl grep -F "'" names" --> correctly matches on quote
=> grep: disable regex search for fgrep mode

bin/rm
* I noticed that if I provide "long" options to rm, it gets confused and attempts to remove files starting with a dash
* When debugging this, preprocess_options() was incorrectly deciding to save long options into new_args list; call usage() instead because this rm only supports single letter options
```
%perl rm --this    # before patch
rm: cannot remove '-t': No such file or directory
rm: cannot remove '-h': No such file or directory
rm: cannot remove '-i': No such file or directory
rm: cannot remove '-s': No such file or directory
```
=> rm: raise error for long options

bin/grep
* The following search should match, but did not because of the '#' character: perl grep -F '#include' a.c
* This was because quotemeta() was escaping it as ```\#``` which was then expanded between single quotes
* The $matcher closure can refer to patterns list directly; this avoids having to expand pattern strings within quotes
* This version is easier to follow because duplicate statements are not added to the closure code if many patterns are specified
```
%perl head -n1 a.c
%perl grep -F '#include' a.c
%perl grep -Fi '#includE' a.c
```
=> grep: fix regression for -F search

bin/tr
* Remove mention of open() failures in BUGS section of manual
* Similar to bin/tee and bin/xargs, change the loop to read STDIN to make it more obvious that tr does not open any files
* On my Linux system, if I redirect stdin from /etc/shadow as a regular user, bash shows a permissions error and sets $? to 1; this takes place before perl is started
* Remove header comment that is duplicated in pod
=> tr: pod update

bin/grep
* When combining grep -F and -h flags, the filenames were not listed for matches (correct), but they still were not listed when unsetting -h (incorrect)
* test1: "perl grep -F '/' awk ar" --> output should show "$filename:" prefix
* Init of global variable $Mult was missed due to early return in parse_args()
* I also tested that -Fl works as expected
* While here, remove the need for variable $optstring by passing options directly to getopts()
=> grep: fix -Fh

bin/ed
* Simplify getopt by removing -v flag which BSD versions of ed don't support (neither is -v a standard ed flag)
* Remove TODO comment related to adding 'x' command; this command is not supported on OpenBSD (nor FreeBSD from what I see in its manual)
* Remove comment with outdated url
* Sync SYNOPSIS and usage string
=> ed: add --version

bin/cat
* Implement idea from BSD version of cat: bypass input processing if none of options -b -e -n -s -t & -v are provided
=> cat: add raw mode

bin/xargs
* Remove non-standard -l alias for -L which is not supported by OpenBSD or NetBSD versions
* The usage string never documented -l so users were theoretically not aware of it
* The code being deleted possibly had a bug where -I option would set $o{l} to 1 but only the value of $o{L} was being used in the main loop
=> xargs: retire -l option

bin/grep
* ARGV list was supposed to have the value '-' added if it was empty
* I noticed that grep would simply exit for the following test: echo hello1 | perl grep -F 1
* In this usage the argument "1" is shifted off ARGV list and the code to reset ARGV was happening too late (problem caused by recent grep -F code addition)
=> grep -F versus stdin

bin/look
* Main file loop is not needed because we only search in one file; the loop was only to determine which file to search
* Remove the need for globals $opened and $found
* Introduce a search function which returns found/not-found
* pod: add a leading dash to the option letters to make it clearer
=> look: simplify program

bin/install
* The -M flag is a stub and was included for compatibility; however, version of install from GNU, Solaris[1] and OpenBSD do not support -M
* -M was never mentioned in the usage string or SYNOPSIS but it can be removed entirely
* NetBSD install has -M but it takes a value, so would not be compatible with this stub
1. https://shrubbery.net/solaris9ab/SUNWaman/hman1b/install.1b.html
=> install: remove -M flag

bin/od
* BSD and GNU versions support -a for printing literal characters, with control character names printed
* GNU version deliberately masks highest (8th) bit per byte, so we follow this
* This is consistent with standards document[1] wording: "named characters from the International Reference Version (IRV) of the ISO/IEC 646:1991 standard. Only the least significant seven bits of each byte shall be used"
* Standards document doesn't mention -a flag, but generally -a is taken to mean the same as "-t a"
* Attempt to document the available options
* When testing this against GNU "od -An -a", whitespace alignment of characters was different but "diff -w" showed no difference for a random test file
1. http://ktiml.mff.cuni.cz/~kucerap/unix/susv4tc2/utilities/od.html
=> od: implement -a option

bin/mail
* On OpenBSD the exit command in mail has 3 aliases: x, ex, xit[1]
* I'm not sure why someone would type "xit" instead of "x", but add it here too for completeness
1. http://man.openbsd.org/mail.1
=> mail: exit command

bin/words
* words command takes only one argument; show an error if user accidentally provides 2 arguments instead of ignoring the second
* Zero-args case was already handled
=> words: throw error for too many args

bin/cp
* Single-letter options can be grouped; one combo I type sometimes is -iv
* Tell Getopt::Long to allow this
```
%perl cp -iv ar ar.rar
'ar' -> 'ar.rar'
```
=> cp: bundled options

bin/ed
* When searching with ?pattern or /pattern in a file not containing the pattern, ed incorrectly printed two '?' prompts and did not capture the expected 'no match' error
* The code after edParse() returns is not supposed to do anything in this case since edParse() already does the 'no match' error (seen when repeating the search with H mode enabled)
* Reintroduce old behaviour by adding a nop action in cmdtab (now edParse() can signal for no subsequent work to be done without a 'bad command' error being raised)
* While here, reduce code by folding edSetCurrentLine() into cmdtab
* edSetCurrentLine() is the default action if a search matches
* The structure of performing a search within CalculateLine() is confusing; this could be improved later
=> ed: failed search regression

bin/nl
* test1: no space between number and line (perl nl -s '' a.c)
* test2: 0 between number and line (perl nl -s0 a.c)
* Patch tested against GNU nl
=> nl: -s separator versus 0

bin/whoami
* Make code even simpler by splitting USER and USERNAME checks into their own subsequent closures
* Tested this by commenting the other subs and running 'perl env -i USERNAME=bob perl whoami'
=> whoami: factor conditional

bin/tail
* Make tail use "==> FILENAME <==\n" format when printing output from multiple files; this conforms with GNU and OpenBSD versions
* This is also consistent with the filename title printed by bin/head
* test: same md5 sum compared to tail(1) on my Linux system: "perl tail -n 50 awk ar arithmetic | md5sum"
* While here, delete dead code in parse_args(); $point is always assigned a default value of -10 at top of function
=> tail: tweak filename title

bin/tail
* The standard tail command doesn't support -h [1]
* GNU and OpenBSD versions print "unknown option" error
* With this patch, usage string is printed after the error, which matches OpenBSD version
* Simplify usage() so it only takes a single (optional) error message param
1. https://pubs.opengroup.org/onlinepubs/007908799/xcu/tail.html
=> tail: retire -h flag

bin/ed
* When testing against GNU and OpenBSD versions, "i" command was with a 2-address prefix was treated as invalid
* Be compatible and treat effective address as 2nd address if 2 were specified
* ed commands "a" and "i" are both handled in edInsert(), so this patch covers both
* test1: "1,2i" --> 2i
* test2: ",2i" --> 2i
* test3: "1,2a" --> 2a
* test4: ",2a" --> 2a
=> ed: 2-address insert command

bin/ed
* Too much code was at the top level, so add an input() function which is called forever
* Now the error branches can just print a warning and return
* Remove comments about how to add a new command; commit history has adequate examples of how to do this
* Also clean up remaining '&' sigils for function calls
=> ed: restructure input loop

bin/ed
* When testing previous commit I discovered that this version of ed incorrectly accepts "0,1w file.mp3" command
* Address range 0-1 is not valid because lines count from 1
* Error was also not raised for "0w file.mp3", i.e. single-address mode
* Follow OpenBSD and GNU versions by printing invalid-address error
* Technically, the command ",1w file" is valid; this is interpreted as implied range of "1,1" which is the same as just "1w"
=> ed: line 0 is invalid for write command

bin/od
* Standards document outlines the -s flag is intended for 2-byte signed decimal display [1]
* OpenBSD, FreeBSD, GNU and Solaris support this meaning of -s [2]
* The -i flag already follows OpenBSD and prints 2-byte signed decimal, so make -s equivalent to -i
* NB: FreeBSD and GNU treat -i as decimal-of-size-int instead of decimal-of-two-bytes, but -i is not standardised
1. https://pubs.opengroup.org/onlinepubs/009696899/utilities/od.html
2. https://shrubbery.net/solaris9ab/SUNWaman/hman1/od.1.html
=> od: standard -s option

bin/ls
* The manual explains that if output is not a tty, ls will infer the -1 flag (i.e. print one entry per line)
* The old filemode check code did not work on my Linux system but this patch does
* I tested this with a pipe into cat, and with a redirect into a file
=> ls: -1 for non-tty

bin/ed
* Fix the error 'Can't "last" outside a loop block at ed line 189', triggered by ctrl+d (eof) after loading a file in ed
* When adding the input() function the "last" statement was missed in the error handling code
* Consistently clear globals before calling edParse(); prevent saved state from previous command input from being used by subsequent commands
* Follow OpenBSD ed and make ^D equivalent to typing the regular "q" command
* Example case: Open a text file and delete 1st line with "1d" command, then hit ^D
* The first time I hit ^D in command mode, edQuit() will print a warning about the modified buffer (called via edQuitAsk())
* When I hit ^D a second time, edQuit() remembers that a warning was already printed, so the program exits
=> ed: command mode versus ctrl+d

bin/od
* Free/Net/Open BSDs document that "od -B" behaves the same as -o
* GNU version appears to support this as well, but I couldn't find reference to this in its manual
=> od: support -B alias for -o

bin/od
* GNU and OpenBSD versions of od support -e and -F for printing two 8-byte floating point numbers per line
* Write a new formatting function to handle this
* While here, add whitespace for readability of -f flag (regular float dump) and increase the precision digits to 7 to match GNU
=> od: add double precision float dump

bin/od
* GNU and OpenBSD support "od -H" and "od -X" options for 4-byte hex format, so add it here too
* Rename 2-byte hex format function to avoid conflict with perl built-in hex()
* Bump program version
=> od: add 4-byte hex dump option

bin/od
* Odd length input was not producing the correct output in all cases; I found this with od -l
* Make a general padding function to avoid duplication in the formatting functions
* Single-byte formatting functions, such as octal1() and char1(), don't require any padding
```
%wc -c a.c
197 a.c
%od -l a.c | tail -n 2   # gnu reference
0000300  1933534308          10
0000305
%perl od -l a.c | tail -n 2   # before patch; no value of 10 in output
00000300 1933534308 
00000305
```
=> od: fix data padding

bin/od
* OpenBSD/FreeBSD/NetBSD and GNU versions support big -O for 4-byte octal, and little -o for 2-byte octal
* Patch appears to produce equivalent output to od on my linux system
=> od: add 4-byte octal dump

bin/du
* Recursive call to traverse() is slightly easier to see when it's not surrounded by "unless"
* Move bypass for . and .. directory entries to top of loop because the result of catfile() would be ignored
* Also switch to "my" to declare handle for opendir(); this makes perlcritic happy
=> du: traverse() tweak

bin/cal
* $remain was unused in make_month_array()
* perlcritic didn't find this one for me, possibly because of the assignment in the declaration statement
=> cal: unused variable

bin/rm
* A filename starting with a dash can be given as an argument like this: ./-o-
* The cp program seems to support this but rm does not (see below)
* I also tested a file called a-b
* Debugging showed that preprocessed_args is incorrectly ['-c','-p','-.','-1']
* Stepping through preprocess_options() revealed a regex on L146 which was not bound to the start of the string
```
%perl cp cp ./-cp.1
%perl rm ./-cp.1 
Unknown option: c
Unknown option: p
Unknown option: .
Unknown option: 1
Usage: rm [-fiPrRv] file ...
```
=> rm: can't delete a filename including a dash

bin/rm
* NetBSD, OpenBSD and GNU versions do exit(0) for "rm -f" with no file arguments
* Standards document says -f flag should not modify the exit status for nonexistent operands[1]
* Support this here too
* Make the program more consistent by exiting directly via exit() instead of mixing calls to exit() and $self->exit() (definition of custom exit() can be eliminated)
* Behave more like BSD version by printing usage for bare "rm" with no -f and no args
1. https://pubs.opengroup.org/onlinepubs/009695399/utilities/rm.html
=> rm: zero args versus -f

bin/grep
* Copy the code pattern from bin/du when running grep in recursive mode
* Joining directory entry names with catfile() is likely more portable
* I didn't test this patch on windows, but grep works the same with patch applied on my linux system, e.g. "perl grep -r grep ."
=> grep: sprinkle catfile()

bin/glob
* Remove the section with default values for historical MacOS; people using current Mac would use the suggestions for Unix
* While here, remove the extra empty line in the suggested values for DOS
=> glob: pod improvement

bin/split
* Strict was disabled in function nextfile() but this masked that the program depends on a few global variables
* Declare the variables explicitly; FH becomes $Fh to avoid aliasing the name $fh which is used later on
* The benefit of the "package" declaration in nextfile() is unclear to me
=> split: more strict

bin/diff
* Strict was disabled within Algorithm::Diff::import() which was importing diff() function into the main namespace
* I gave up converting import() to strict because the code was a bit magical
* Settle for removing import() entirely and calling fully qualified Algorithm::Diff::diff()
* Now the entire program can run under strict mode
=> diff: increase strictness

bin/split
* The check for the special argument '-' should take place before stat
* The old code was wrong because "split -" produced 2 different results depending on whether I had a directory called "-"
* test1: "perl split -"  == stdin
* test2: "perl split ./-" == file called "-"
* test3: "perl split -- -" == same as test1
=> split: out-of-order check

bin/ar
* When listing archive file contents with "perl ar -tv file.a", the -v flag enables printing the file permissions for each archive member
* Take advantage of the $mode param being an octal string
* As before, only take the last 3 octal digits and deal with trailing spaces in $mode param
* By inspecting the 3 octal digits separately, there's no need for a modemap table to interpret the bits at the various positions for user/owner, group and other
* Patch tested against a file created by this ar, and another file created by binutils
```
%perl ar -q test.a words wordlist.txt.old
%perl ar -tv test.a
rwxr-xr-x    1000/1000       3975 Jun 12 09:13 2024 words
rw-r--r--    1000/1000         23 Feb  7 13:00 2024 wordlist.txt.old
```
=> ar: simplify strmode()

bin/shar
* For binary files, shar will construct input that is passed to the uudecode command
* When testing files from /bin on my Linux system, I saw decode errors when extracting with "sh new.shar"
* The file sizes didn't match
* When inspecting the output of shar from GNU sharutils, there was a terminating line with only a backtick immediately before the "end" line
* Adding the backtick line in this version makes uudecode work correctly; I tested this against a few files from my /bin
* binmode() isn't needed for STDOUT because shar always prints text output
* Convert FH to a regular variable
* The command line for decoding a binary file doesn't need a pipe through sed because the 'X' prefix letter is never added to the uuencoded data
```
%sh bash.shar  # before patch
x - bash
uudecode fatal …
```
=> shar: uudecode problem

bin/factor
* The END-block was defined for handling die() to make the program effectively do exit(1)
* die() is not called explicitly, so the END-block has marginal benefit
=> factor: dead die() handler

bin/cp
* When running on non-unix, avoid passing a directory to File::Copy::copy() and print a helpful warning message
* GNU and OpenBSD versions print a warning for this case too
=> cp: warn for source directory

bin/cp
* When cp runs in non-unix mode, take advantage of File::Copy::copy() setting $! on failure
* When the destination was a non-existent directory, cp would do exit(1) but did not show the reason for failure
=> cp: warn on File::Copy::copy() failure

bin/mkfifo
* Function can be written with a single return statement
* test1: symbolic mode: perl mkfifo -m a=rw fifo1
* test2: numeric mode: perl mkfifo -m 704 fifo2
=> mkfifo: factor get_mode()

bin/tee
* Standards document mentions that only SIGINT is ignored for "tee -i" [1]
* Dragonfly/Free/Net/Open- BSD manuals are consistent and list only SIGINT
* Other historical systems documented that -i ignored interrupts but did not explicitly say which ones
1. https://pubs.opengroup.org/onlinepubs/009696699/utilities/tee.html
=> tee: standard -i flag

bin/tee
* There is no need to support -n, which is not provided by the BSD or GNU versions (nor AIX [1], Solaris)
* Make some changes to prepare for enabling strict mode, e.g. add missing declaration for $status variable
1. https://www.ibm.com/docs/en/aix/7.2?topic=t-tee-command
=> tee: remove nonstandard -n option

bin/tee
* Correct left-over reference to variable $unbuffer
* Remove custom SIGPIPE code which doesn't exist in the BSD version (the only reference to signals is SIGINT being ignored)
* Standards document mentions nothing about SIGPIPE in Asynchronous Events section[1]
* Output files table (%fh) is now keyed based on file descriptor and contains filehandle and the saved filename from ARGV
* Explicitly check for directory before opening a file
* test1: "ifconfig | perl tee out.1" --> out.1 created
* test2: "ifconfig | perl tee -a out.1 out.2" --> existing out.1 appended, out.2 created
1. https://pubs.opengroup.org/onlinepubs/009696699/utilities/tee.html
=> tee: add strict

bin/tee
* The standard tee writes output in unbuffered mode by default, so the -u option is not needed
* The code guarded by $opt{'u'} now happens unconditionally
* Introduce $VERSION and make the --version option work
* Add some basic content for the manual
=> tee: remove -u option

bin/diff
* Algorithm::Diff::LCS() was never called, and I am doubtful that the code would be correct
* Declaring EXPORT_OK in Algorithm::Diff is also not needed, because the program doesn't explicitly import
* Correct a comment that actually referred to the function Algorithm::Diff::diff()
* As a regression test I ran "perl diff -e" then "patch -e" against the output
=> diff: unused function

bin/sort
* Usage string incorrectly advertised that the first file argument is required; all file arguments are optional
* Document that the program will read from stdin by default
* Remove second-person language from manual
=> sort: documentation fix

bin/paste
* As with PR675, check for '-' argument needs to occur first
* The argument '-' doesn't have a special meaning for all commands
=> paste: out-of-order check

bin/grep
* grep supports '-' argument for stdin
* On L180 '-' is added to ARGV if it is empty
* The directory check in matchfile() was happening too early, so move the '-' check to top of loop
* test1: "mkdir ./- && echo hi | perl grep hi" --> previously the directory check would get in the way and terminate grep
* test2: "ifconfig | perl grep '^[a-z]'" --> ifconfig lines starting with an interface name
=> grep: out-of-order check

bin/kill
* Move some top-level code into a function
* Fail early if the result of split() is an empty list; this shouldn't happen but previously the list size was not checked
=> kill: sanity check siglist

bin/fold
* Reduce the amount of custom code for pre-posix argument handling of -NUM
* Pre-process ARGV by converting -123 to -w123, then hand off to getopts()
* Prefix usage string with "usage:"
* Sync usage string with pod document; no need to encourage people to use the old -NUM form for width
* test1: "echo `perl cat cat` | perl fold -40" --> process stdin with -w 40
* test2: "perl fold -s -w 72 moo" --> regular -w form with file input instead of stdin
=> fold: add getopts()

bin/patch
* Program is written in oo-style with subclasses of Patch (Context, Ed, Normal and Unified) 
* Declare subclasses as subclasses with "use base" instead of calling Patch->import() manually
* Now the custom import() code can be deleted
* Two example methods called from subclass are note() and throw()
* I noticed this when searching for "no strict" within bin/ directory
* test1: patch a normal diff (output of "diff a.c b.c")
* test2: patch a unified diff (output of "diff -u a.c b.c")
* test3: patch an ed diff (output of "diff -e a.c b.c")
* test4: patch a context diff (output of "diff -c a.c b.c")
=> patch: retire Patch::import()

bin/fmt
* I observed a suspicious warning when providing negative number as input...
```
%perl fmt -w-1000000 a.c > /dev/null
Negative repeat count does nothing at fmt line 34.
```
* Value for -w must be an int; follow OpenBSD fmt and raise error for 0 and negative
* test1: "perl fmt -w 1.1  a.c" --> already covered by Getopt::Long
* test2: "perl fmt -w''  a.c" --> same as test1
* test3: "perl fmt -w0  a.c" --> new validation
* test4: "perl fmt -w-100  a.c" --> same as test3
=> fmt: validate width

bin/fmt
* Follow pattern from OpenBSD fmt: print warning and guarantee non-zero exit code if a file arguments was a directory (e.g. "perl fmt .. .. text.txt")
* Sync SYNOPSIS with usage string; the -w option is preferred over the traditional -NUM option
* Document that the standard input is read by default
* Add a pod section for EXIT STATUS
=> fmt: exit(1) for directory

bin/spell
* NetBSD and OpenBSD versions of spell use the -s option as a "stop list" instead of an extra dictionary
* Remove -s here to avoid confusion
* Add the +extra_list option, which can be repeated, for adding more optional dictionaries to the main dictionary being read
* Update usage() and pod to document +extra_list
* test: " perl spell -d wordlist.txt +extra.txt NOTES"  ---> spell-check NOTES combining custom dictionaries wordlist.txt and extra.txt
=> spell: rename -s option

bin/pr
* The -NUM option can be used for setting column count, but -0 is not a valid input
```
%perl pr -0  a.c
Illegal division by zero at pr line 338.
```
*  When tracing this, COLINFO list is empty and $columns is zero
* Follow GNU implementation and raise error for -0
=> pr -0 causes divzero

bin/bc
* Standard bc does not require any signal handling [1]
* Different versions of bc treat SIGINT differently
* The previous code resulted in bc exiting on ^C on my Linux system, so there's effectively no difference with this patch
1. https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/bc.html
=> bc: remove signal handling

bin/tee
* Follow wording from standards document that write() errors should cause the current file to stop being written to; however, remaining files and stdout should continue
* Switching to syswrite() guarantees the output is unbuffered as expected, and makes detecting failure simpler
1. https://pubs.opengroup.org/onlinepubs/009696699/utilities/tee.html
=> tee: detect write() failure

bin/patch
* patch failed with a strictness error when I specified a file that does not match the context of my diff
* Patch::apply() calls back into Patch::Context::apply() on L714 with the wrong params
* When setting a breakpoint in Patch::apply(), its params are not identical to Patch::Context::apply(), so passing @_ as parameter obviously fails
* Reading the code, this would only be a problem for applying context diffs (no callback to self->apply() happened for the other diff types)
* I confirmed that this error was not caused by the recent use-base.diff (now I suspect it goes back to 1999)
* Removing the code with the incorrect self->apply() call causes patch to correctly report that applying Hunk1 failed, then the program exits with status 1 to indicate that >=1 lines could not be applied
``` …
```
=> patch: runtime error when patching the wrong file

bin/patch
* "patch --check" can be implemented in less code using File::Temp to provide a garbage filehandle which is automatically cleaned up later
* I tested this by repeatedly running "perl patch -C original.c my.diff"; original.c is not modified so each instance is successful
* For --check mode there is no need for o_fh and d_fh to be a different filehandle because data written to it is discarded anyway
=> patch: simplify --check

bin/units
* I found this when testing against the OpenBSD version
* The old code unhelpfully bypassed opening the file specified by -f FILE option if it did not exist
* Make read_unittab() handle 3 cases...
* case1: implicit unittab ($file is undefined; read definitions in __DATA__)
* case2: $file is a directory (ignore it to match OpenBSD; read __DATA__)
* case3: otherwise... open the file and terminate the program if it couldn't open
* While here add defined() checks after prompting for input; this silences warnings seen when terminating program with ^D
=> units: fail if custom unittab file doesn't open

bin/grep
* This grep has the standard meanings of options -s and -q backwards [1]
* -s is to suppress some errors
* -q is to make grep not show matches, and perform a quick search of one match per file
* test1: "perl grep -c yo grep" --> count the matches of "yo"
* test2: "perl grep -cv yo grep"-->  count the lines not matching "yo"
* test3: "perl grep -q perl  grep" --> quiet search for "perl"; exit status 0 indicates Match
* test4: "perl grep -q pascal grep" --> quiet search for "pascal"; exit status 1 indicates NoMatch
* test5: "perl grep -s greg greg" --> silent search for "greg" but the file doesn't exist; exit status 2 indicates Error
* Correct POD manual and usage string
1. https://pubs.opengroup.org/onlinepubs/009604299/utilities/grep.html
=> grep: -q and -s options reversed

bin/grep
* grep output is expected to show the filename if grep is searching many files, or in a recursive search (grep -r)
* The -h flag disables the filename prefix
* $Mult flag controls showing the filename, and was being set to 1 sometimes when it shouldn't be
* test1: "perl grep perl awk" --> show matches for 1 file (no filename prefix, single file argument)
* test2: "perl grep  perl awk ar" --> matches for 2 files (filenames included)
* test3: "perl grep -h perl awk ar" --> matches for 2 files (filenames disabled by -h)
* test4: "perl grep -hr perl ." --> recursive search (filenames disabled)
* test5: "echo elmo | perl grep elm" --> show matches for stdin (no filename prefix, no file arguments)
* test6: "perl grep -l awk a*" --> show filenames matching awk
* test7: "perl grep -r package ." …
=> grep: filename prefix correction

bin/id
* Previously commit 92678daec769369d29fef632fc9e412b511698b1 was added to allow resolving "root" to uid 0
* When testing -g option a similar issue was discovered (gid of 0 was being treated as a failure of getpwnam)
* This was discovered while testing against id on my Linux system
```
%grep '^root' /etc/group 
root:x:0:
%/usr/bin/id -g root
0
%perl id -g root # before patch
1000
```
=> id: gid 0 is valid

bin/grep
* The -q flag in grep is concerned if a match was found in any file
* The program can successfully terminate after the first match without searching subsequent files in argument list
* GNU grep behaves in this way; strace on my Linux system confirms that only the 1st file in argument list is opened when that file contains a match
```
%strace  grep -q perl ar awk 2> trace # gnu grep
%grep open trace
...
openat(AT_FDCWD, "ar", _RDONLY|O_NOCTTY|O_LARGEFILE) = 3
^^^ final openat() in process
```
=> grep: shortcut exit path for -q

bin/cmp
* Input loop terminates if sysread on file1 fails
* If sysread failed on file2, $read_in2 would be undef, then $checklength would be undef
* It is not correct to compare the two input buffers in this case; $buffer2 possibly wouldn't have been modified since the previous loop iteration
* Skip the buffer comparison if $checklength is zero (treat sysread failure in the same way because there are no bytes to compare)
* In this case it would be correct for cmp to report "EOF on file2" because the read length for file1 is greater
=> cmp: sysread failure guard

bin/patch
* Remove note about GNU patch requiring a space between -D and argument (this might have been true for ancient versions but not anymore)
* This version of patch outputs a trailing comment for the ifndef blocks; the OpenBSD version does this also
```
%ifconfig > A
%sed 's/eth0/ent0/' A > B
%perl diff -u A B > AB.diff 
%/usr/bin/patch --version 
GNU patch 2.7.6
%/usr/bin/patch -Dostuff -o C A AB.diff
patching file C (read from A)
%perl patch -Dostuff -o D A AB.diff
Hmm...  Looks like a unified diff to me...
Patching file A using Plan B...
Hunk #1 succeeded at 1.
done
%perl diff C D 
5c5
< #endif
---
> #endif /* ostuff */
```
=> patch: pod update for --ifdef

bin/ar
* After opening an archive, print $! if it wasn't possible to read the file
* Now it's easier to tell between i/o errors and files which don't contain the magic number data
* Conditionally declare $attr in printList() which is only needed for verbose mode
* test1: "ar t ." --> directory error
* test2: "perl ar t /bin/sh" --> file format error
* test3: "perl ar t test.a" --> short listing of archive contents
* test4: "perl ar tv test.a" --> detailed listing of archive contents
=> ar: failed read() error

bin/awk
* Switch from calling tempfile() to File::Temp->new() to allow the input and output files to be unlinked automatically when the program terminates
* This prevents remnant files in /tmp if die() happens
=> awk: auto-clean /tmp

bin/morse
* When demonstrating the morse program to my son I found an error in decode mode; it can be reproduced like this: %printf "\n.\n" | perl morse -rs 
: unknown token at morse line 68, <> line 2.
* The following worked as expected, going from text2morse2text:
%printf "aye\nbee\nc++\n" | perl morse -s | perl morse -rs
* So I put on my debuggin' shoes... $line was "\n.\n", split() returns list ('', '.') and the program barfs on the empty string
* Empty string is also indicated by the "unknown token" error message with no character before the ':'
* Fix this by trimming leading whitespace before split()
=> morse: leading whitespace failure

bin/patch
* When testing against GNU and OpenBSD patch commands I found that -d DIR in this version is interpreted after reading a patch file
* The standard says -d is interpreted "before processing" [1]
* Follow the other versions of patch and do chdir() as early as possible:
A) Failure to chdir() will terminate the program before any input is read
B) If -d option is used, files in the argument list are relative to that directory not to the originating directory
* test1: "perl patch -d ... a.c" --> fail (no such dir)
* test2: "patch -d .. a.c a.diff" --> patch ../a.c with ../a.diff
1. https://pubs.opengroup.org/onlinepubs/007904975/utilities/patch.html
=> patch: chdir happens too late

bin/patch
* Fail as early as possible if a negative number was given for --fuzz option
* Getopt::Long already validates --fuzz argument as a number, but  a negative value was previously ignored (the default of 2 would be used)
* Found when testing against GNU patch
=> patch: reject negative --fuzz value

bin/random
* Comparing the NetBSD version of the random-lines game, unknown options should result in usage string being printed
* Usage was already printed for too-many-arguments case
* Create a regular usage() function as done in other scripts
```
%ifconfig | perl random -r 6 # test1: -r
RX packets 0  bytes 0 (0.0 B)
inet6 ::1  prefixlen 128  scopeid 0x10<host>
RX packets 2057  bytes 452554 (441.9 KiB)
%perl random -e 100 # test2: -e
%echo $?
35
%perl random -x # test3: bad option
Unknown option: x
usage: random [-er] [denominator]
%perl random 123 456 # test4: too many args
usage: random [-er] [denominator]
```
=> random: raise error for bad option

bin/patch
* Allow '-' to be interpreted as standard out for -o option (aka --output); this works for Linux and OpenBSD versions
* GNU diff writes notifications to stderr so they aren't jumbled with patch output; update note() to follow this
* When writing to standard out, don't check if there's a file called '-' in current directory because it is not correct to make a backup by renaming it
=> patch: allow --output to stdout

bin/dirname
* Standards document has an example where "--" option terminator is used.. $(dirname -- file) [1]
* dirname is not a bash builtin on my Linux system
* GNU and OpenBSD dirname support "--" so add it here too
* GNU version supports multiple path arguments, but that does not follow the standard (this version already raised an error for multiple arguments)
* test1: "perl dirname -- $(pwd)/A" --> single file argument after -- is valid
* test2: "perl dirname a b" --> too many args
* test3: "perl dirname --" --> not enough args 
* test4: "perl dirname -x -- -A" --> bad option error
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/dirname.html
=> dirname: support -- terminator

bin/basename, bin/dirname
* Similar to what was committed for bin/dirname, '--' should be interpreted as the end of options (currently it is taken literally)
* This was found when testing against OpenBSD version
* test1: "perl basename --" --> error, no argument
* test2: "perl basename -x" --> error, bad option
* test3: "perl basename -- -x" --> basename of "-x"
* While here, one call to usage() in bin/dirname was missed
=> basename: support -- option terminator 

bin/basename
* The pod manual mentioned that the optional suffix could be a normal string or a regex
* Follow the standards document and implement string match, being careful to match only at the end of the string, and not to match the entire string (after prefix is stripped) [1]
* Remove reference to regex suffix in pod
* Bump version
```
%perl basename `pwd`/a.c  # test1: no suffix
%perl basename `pwd`/a.c eyy.si  # test2: no match for suffix
%perl basename `pwd`/a.c a.c  # test3: match consumes all of remaining string so it is ignored
%perl basename `pwd`/a.c .c   # test4: file extension .c is removed
```
1. https://pubs.opengroup.org/onlinepubs/007904975/utilities/basename.html "If the suffix operand is present, is not identical to the characters remaining in string..."
=> basename: suffix argument did nothing

bin/moo
* When prompted for a guess, "q" terminates the program
* If stdin is attached to a file/pipe, or I run moo interactively and hit ctrl-d I observe a repeated prompt
* The least confusing thing is to act like a "q" command was seen and terminate the program
* test: "ifconfig | perl moo" --> series of "bad guess" messages then the program ends
=> moo: quit on EOF

bin/diff
* Similar to commit 2531425311b604d2f1becee81120373d60a886f5 for bin/grep, join a filename to a directory with catfile(), which would make the correct choice of separator for windows
* To test this I make a directory, copy a file in there and compare it with the one in working directory
```
%mkdir dir0
%cp a.c dir0
%perl diff a.c dir0
%perl diff dir0 a.c
```
=> diff: catfile > join

bin/ar
* I noticed there were 4 calls to FileHande->new() to open files, but only 3 calls to binmode()
* The function missing the binmode() call was writeAr(); this is responsible for writing a modified archive to disk, or creating a brand new archive
* Archives are allowed to contain binary files so enabling binmode() here seems like a good idea
* I didn't test this on Windows but I didn't see any regression with patch applied on Linux
```
%cc a.c
%perl ar -qv A.a a.out # create new archive with just the binary a.out
a - a.out
```
=> ar: binmode for writing archives

bin/ar
* If extracting or deleting multiple archive members, process all arguments even if some members are not found
* This patch follows how binutils version works
```
%ar -t test2.a # list archive members
words
wordlist.txt.ol
%ar -xv test2.a not1 not2 words # extract 3 files (1 is extracted)
no entry not1 in archive
no entry not2 in archive
x - words
%ar -dv test2.a test test2 words # delete 3 files (1 is deleted)
No member named `test'
No member named `test2'
d - words
```
=> ar: best-effort extract & delete

bin/glob
* $matches unused in "main" program block
* $anyfound set but not used in recurseglob()
* Directly declare escape sequence hash "map_esc" instead of declaring intermediate global list "escapes"
* Regression test: ```perl glob '*.c*'``` versus ```ls -1 *.c*``` (i.e. glob function built into bash shell)
=> glob: unused variables

bin/pwd
* This version of pwd already acted like the BSD version because it would raise an error if any non-option arguments are provided
* When testing against OpenBSD, the usage ```pwd -L --``` is valid; this version raised an error because '--' was interpreted as an argument instead of option terminator
* getopts() handles -- internally, so switch over to it as done in other scripts
=> pwd: don't raise error for -- terminator

bin/addbib
* When entering "vi" at the Continue prompt, perl would execute a shell instead of executing vi directly
* The filename ";halt" combined with vi produces two commands passed to the shell
* There is still a problem in the loop where the filehandle is closed before hitting "y" to continue, but this can be addressed separately
```
%perl addbib ";halt"
Instructions? (n) n
Author name: a
Title: a
Journal: a
Volume: a
Pages: a
Publisher: a
City: a
Date: a
Other: a
Keywords: a
Abstract: a
a
^D
Continue? (y) vi
Failed to halt system via logind: Interactive authentication required. Failed to open initctl fifo: Permission denied
Failed to talk to init daemon.
system 'vi ;halt' failed: 256 at addbib line 109, <> line 1.
```
=> addbib: avoid interpolated params to system()

bin/addbib
* BSD version of addbib allows vi, ex, edit and ed [1] [2]
* This version supported emacs (keep it) but not ed
1. https://github.com/AaronJackson/2.11BSD/blob/main/usr.bin/refer/addbib.c#L215
2. https://man.freebsd.org/cgi/man.cgi?query=addbib&apropos=0&sektion=0&manpath=FreeBSD+14.1-RELEASE+and+Ports&arch=default&format=html
=> addbib: support ed editor

bin/addbib
* I discovered the cause of the close() error I was seeing when editing a database entry with vi, then hitting y to continue
* When continuing a new entry is expected to be appended to the database
* The file was closed and re-opened between executing vi; however, due to the "my" declaration in the open() call an alias of the global filehandle $DATABASE was made
* Make sure there is only one $DATABASE variable; now I can correctly append new entries after editing an entry with vi
```
%perl addbib 123c
Instructions? (n) n
Author name: 123
Title: 123
Journal: 123
Volume: 123
Pages: 123
Publisher: 123
City: 123
Date: 123
Other: 123
Keywords: 123
Abstract: 123
Continue? (y) vi
Continue? (y) y
Author name: this 
Title: 234
Journal: 234
Volume: 234
Pages: 234
Publisher: 234
City: 234
Date: 234 …
```
=> addbib: correctly re-open database

bin/col
* GNU and BSD versions of col support -h which is the same as the default operation of col
* In those versions -h and -x given together negate each other, so the final one wins
* getopts() doesn't disclose the order of options, so document that -x takes precedence over -h if both are given
* Sync usage() function
* test1: "perl col < col | md5sum" --> normal output
* test2: "perl col -h < col | md5sum" --> same output as test1
* test3: "perl col -x < col | md5sum" --> multiple spaces output
* test4: "perl col -xh < col | md5sum" --> honour -x despite -h coming last; same output as test3
=> col: add -h option

bin/col
* Partial file buffering code was removed in commit 5da850a4719b91919d42c3cbbe993cc5a33493de
* Argument to option -l was being validated as a number, but $opt_l was effectively unused
* Remove validation code but it's not harmful keeping -l option as a stub since it appears in other versions (e.g. GNU and FreeBSD)
* Update description of -l in POD
=> col: dead buffering code

bin/grep
* Current perl treats study() call as no-op so delete it [1]
* grep was the only caller of study(); no other scripts need updating
* While here, convert a "use" statement within a condition to a "require" (found by perlcritic)
* Regression test: "perl grep -Hn include a.c b.c" --> still highlights the matching part of each line on my Linux system
1. https://perldoc.perl.org/functions/study
=> grep: retire study()

bin/grep
* Declare globals directly with "my" instead of "use vars"
* Declare $term variable only in the context of Term::Cap eval failure
=> grep: small cleanup

bin/grep
* This version of grep skips binary files by default; this behaviour is inconsistent with GNU version but the difference could be addressed later
* If the file argument exists but cannot be opened, grep was skipping the file with a strange "binary file" message
* I found this when testing "grep -s", which is expected to exit with 2 if a file couldn't be opened
* I triggered open() error by removing file permissions on my Linux system
```
%chmod 0 a.c
%perl grep -T include a.c
grep: skipping binary file "a.c"
```
* Correct the binary file condition; skip the file argument if file is binary (filetest -B) and we're not running grep -a
* Correct the logic for exit code; $Errors should increment regardless of -s because exit code is determined from it
* Bump version
* With patch applied, grep …
=> grep: wrong exit code for grep -s

bin/grep
* Standards document mentions that option -x should work with fixed strings [1]
* This version didn't allow -x with -F; add it now for better compliance with standard
* I have a small test file with some C code
* test1: "perl grep int a.c" --> matches "int\n" and "printf(...);\n"
* test2: "perl grep -i Int a.c" --> same match as test1
* test3: "perl grep -iv Int a.c" --> matches all except "int\n" and "printf(...);\n"
* test4: "perl grep -v Int a.c" --> matches all lines because Int doesn't appear at all
* test5: "perl grep -F -x int a.c" --> matches only "int\n"
* test6: "perl grep -Fxi Int a.c" --> same match as test5
* test7: "perl grep -Fxiv Int a.c" --> matches all except "int\n"
* test8: "perl grep -Fxv Int a.c" --> matches all lines because Int doesn't appear at all
1. …
=> grep: implement -x for fixed strings

bin/grep
* Make this grep follow the BSD version better
* A warning is already printed under trace mode (-T option) for each file argument processed, but there is no need to warn by default
* GNU grep doesn't warn for this test case either
* Fix a nit where the trace message is supposed to use the variable $name
* While here, consistently append "\n" to error messages 
```
%ifconfig | perl grep -T flags # after patch ...
grep: checking <STDIN>
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
```
=> grep: silence stdin warning

bin/grep
* GNU and BSD versions support -L which is the opposite of -l
* Using -L is easier than filtering grep -c output for 0
* Document that -L overrides -l and update usage string
* Bump version
```
%perl grep -c include ar a.c
ar:0
a.c:2
%perl grep -l include ar a.c
a.c
%perl grep -L include ar a.c
ar
```
=> grep: add -L option

bin/grep
* When temporarily enabling warnings+diagnostics in grep I observed a warning related to FILE being used only once
* The close(FILE) statement was incorrect because the current input file is actually $fh
* The correct place to close the file was after the LINE-loop
* Technically $fh was being closed implicitly after each FILE-loop, but keep the pattern of explicitly closing it
* Style: where possible, refer to the LINE-loop when jumping from within the LINE-loop
* Also convert PATFILE into a regular "my" variable, so there are no more bareword files
=> grep: bad filehandle passed to close()

bin/grep
* Remove the need for variables $zeros and $nulls for processing opt-hash before calling getopts()
* opt-e is guarded against undef by length() check
* opt-p and opt-P are used in a print() statement so init these to empty string directly
* When overriding opt-1, opt-g and opt-c, use logical operator instead of addition operator, which would warn for undef operand
* As done previously with filehandles, convert directory handle DIR to a my-variable (this is used for for grep -r)
* Correct an assignment to opt-hash which should not have used "->"
=> grep: simplify parse_args()

bin/grep
* When running in recursive mode, standard grep is not required to support sorting of directory entries by modification time [1]
* The -t option does not exist in BSD, GNU, Solaris or Plan9 versions of grep
* Remove -t to follow BSD version more closely (bump version since now a usage string is printed for -t)
1. https://pubs.opengroup.org/onlinepubs/009604299/utilities/grep.html
=> grep: retire -t extension

bin/par
* Change par to raise a fatal error if invalid options are passed, e.g. "perl par -X"
* Change the order or ARGV check to after getopts() call, so that an option is not counted incorrectly as a file argument, e.g. "perl par -S"
=> par: reject bad options

bin/what
* -s flag means to stop searching the current file argument, and move to the next file argument, after the first match
* Input loop reads lines, and a line might contain NUL
* NUL is expected to terminate patterns in the same way as newline, but NUL was only handled correctly if -s flag was not set
* I found this when comparing the output with and without -s
```
%perl strings /usr/bin/cvs | perl grep -Fi miros  # string order = lowercase miros 1st
@(#)rcsid_bron: $miros: src/gnu/usr.bin/cvs/lib/getdate.y,v 1.14 2021/01/30 02:28:27 tg Exp $
@(#)rcsid_code: $MirOS: src/gnu/usr.bin/cvs/lib/getdate.c,v 1.19 2021/01/30 02:30:17 tg Exp $
%perl what /usr/bin/cvs # all matches
/usr/bin/cvs:
rcsid_bron: $miros: src/gnu/usr.bin/cvs/lib/getdate.y,v 1.14 2021/01/30 02:28:27 tg Exp $
rcsid_code: …
```
=> what: -s flag prints out of order

bin/what
* Similar to grep command, exit code 0 means at least one match occurred when looking at input files
* Unlike grep, exit code 1 is shared between no-match and error conditions (e.g. file could not be opened) [1]
* Continue to bail on the 1st open() failure, but now go through exit() instead of die()
* Difference discovered when testing against OpenBSD version
1. https://pubs.opengroup.org/onlinepubs/009696799/utilities/what.html
=> what: exit(0) only for match

bin/grep
* When running grep -g or -u, the default code uses Term::Cap but this fails over to executing external tput command
* tput would be available on Linux/BSD but is not a consideration for Windows
* Feed the TERM environment variable to tput command in single quotes to prevent shell commands from being initiated though TERM
* To verify this I had to temporarily bypass the Term::Cap code on my Linux system
* No other instances of backticks, system() or exec() calls within grep
```
%TERM='linux;halt -p;' perl  grep -g include a.c   # with patch applied tput fails but system doesn't halt
tput: unknown terminal "linux;halt -p;"
tput: unknown terminal "linux;halt -p;"
#include <stdlib.h>
```
=> grep: avoid shell code evaluation

bin/grep
* Define each of the different matching modes as its own closure within parse_args()
* All matching modes support multiple patterns
* The code is more readable because code doesn't get passed to eval() as a string
* The code in the closures is now able to fail at compile time, instead of deferring failure to runtime eval() call
=> grep: remove code-generator

bin/what
* In printWhat(), both sides of if-else branch had the same code except for one side having a loop
* Structure code so it's possible to loop over a list for both cases (in the case not requiring the split() the list contains a single element)
* I don't notice any difference in output after applying this patch
=> what: remove duplicate code

bin/grep
* If -e and -f are not provided, the first argument to grep is a pattern
* If -e or -f is provided, the first argument to grep is a file
* Allow multiple -e and -f options to translate to multiple elements in the ```@patterns``` list
* This patch follows how GNU and BSD versions behave
* Bump version
* test1: "perl grep -e include -e return a.c" --> 2 patterns, one file argument
* test2: "echo include > P1 && echo return > P2 && perl grep -f P1 -f P2 a.c" --> 2 pattern files with one pattern each; one file argument
* test3: "grep return a.c" --> one (default) pattern argument,one file argument
=> grep: allow repeated -e and -f

bin/tsort
* The input "a" by itself results in a fatal error for BSD and GNU versions
* Previously this version ignored odd arguments, but that is contrary to the standard [1]
* Also, the standard does not suggest that each line contains only one pair of tokens
* When reading source code of OpenBSD version I discovered the input "a b b c b d d f c e" on one line is treated the same as for pairs on separate lines (GNU tsort behaves the same here)
* Accept multiple pairs per line for better compatibility, and remove the mention of the old limitation in the POD
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/tsort.html
=> tsort: raise error for odd input tokens

bin/ed
* Today I noticed that when starting ed without a file argument, writing a file with "w file.name" didn't print a byte count
* I confirmed that BSD and GNU versions of ed do print a byte count in this case
* When reading the code, the flag $SupressCounts should only be set when running ed in "script" mode (ed -s)
* The code setting the flag for no file argument is not correct (w command will fail unless a filename has either been provided directly as argument, or set earlier with f command)
* Bump version
```
%perl ed
a
this is ok
.
w some.file 
11
q
```
=> ed: w doesn't print byte count

bin/tsort
* When a node refers to itself in a pair it means the node exists but does not depend on anything
* Previously, this input would result in a "cycle" error
* In my test file, allow node 'd' to be added to hash ```%npred``` with predecessor count of zero, so it then appears in list ```@list```
* The inner "foreach" loop does not execute for node 'd' because it has no dependency; it has no need for an entry in hash ```%succ```
```
%perl cat in.tsort2
a b
b
c
d d
%perl tsort.old in.tsort2
a
b
c
tsort.old: cycle detected
%perl tsort in.tsort2 # patched
a
b
c
d
%perl cat in.tsort3
a a
%perl tsort in.tsort3 # output agrees with GNU tsort
a
```
=> tsort: allow independent nodes

bin/ed
* If I search for a pattern with "/hi" or "?bye" I want to repeat the search without re-entering the pattern (it might be much longer than "hi")
* Allow typing a single "/" or "?" to repeat search down or up respectively (this will fail if a previous search was not performed)
* GNU ed also allows repeating a search by typing empty pattern as "//" or "??", but that is not supported here for now
=> ed: basic repeated search

bin/ed
* Basic usage of g command is to show lines matching a pattern
* More advanced use of g command would be to modify the buffer; this needs more work
* test1: g/text not found/p ---> no error is printed (consistent with BSD and GNU version)
* test2: g/include/p ---> print matching lines
* test3: g/include/n ---> prefix matching lines with line number
* test4: g/t/l ---> matching lines are listed in with escapes
=> ed: initial support for global (g) command

bin/cmp
* It is easy to provide extra descriptive output when files differ at EOF, as done by GNU cmp
* Shell scripts running cmp would normally use the -s flag and check the exit code, i.e. the text description shouldn't be depended on for portability
* Also convert $chunk_size global to a constant because it doesn't vary
```
%dd if=/dev/urandom bs=512 count=1 of=rnd
%cp rnd rnd2
%echo >> rnd2
%touch empty
%perl cmp rnd rnd2 # test1: non-empty files, eof on arg1
cmp: EOF on rnd after byte 512, in line 6
%perl cmp rnd2 rnd # test2: non-empty files, eof on arg2
cmp: EOF on rnd after byte 512, in line 6
%perl cmp empty rnd # test3: arg1 empty
cmp: EOF on empty which is empty
%perl cmp rnd empty # test4: arg2 empty
cmp: EOF on empty which is empty
```
=> cmp: helpful EOF messages

bin/ed
* Go with the BSD treatment of -s flag: allow e command to open a new file (replacing the line buffer) without warning if the buffer was modified
* This is more correct because in script mode (-s) ed is not being used interactively
* This difference was discovered when testing OpenBSD version
=> ed: -s silences warning in edEdit()

bin/ed
* In commit 78d54294099cfab729e156e8a0f123939da14179, repeat search was only implemented for "/" and "?"
* Add support for empty patterns specified as "??" and "//" (these may be followed by whitespace, but single "?" and "/" may not)
* test1: "/\n" --> repeat search down
* test2: "/ \n" --> start new search (down) for " "
* test3: "// \n" --> repeat search down
* test4: "?\n" --> repeat search up
* test5: "? \n"--> start new search (up) for " "
* test6: "?? \n --> repeat search up
* Entering //n doesn't seem to work for repeating search then issuing n command (this could be supported later)
=> ed: allow repeated search with // and ??

bin/file
* Non-standard option -f takes a path argument to read a list of paths to check
* Problem1: "file -f 0" is valid but incorrect truth check did not recognise -f
* Problem2: lines read from file are terminated by newlines, and these newlines were incorrectly being added into ARGV as part of the string (resulting in open() failure)
```
%cat 0
comm
ar
%perl file -f 0
comm: executable /usr/bin/perl script text
ar: executable /usr/bin/perl script text
```
=> file: -f option doesn't work properly

bin/ed
* Implement inverted global command 'v' with the same limitations as 'g' command
* Document the 'v' command in pod, and remove old comment suggesting to add it
* Avoid incorrectly printing $Prompt when running 'g' command (found when running P before g)
* Global search should not proceed from the current line (found when testing against GNU ed)
* Bump version
* test1: "v/include/n" --> list lines not matching "include", starting from line 1
* test2: jump to line 5 then repeat test1 --> search items are displayed in the same order as before, irrespective of current line position
=> ed: basic support for inverted global search (v)

bin/ed
* Unhook commands E, e, f, H, h, P, Q and q from the large regex in edParse(); the idea is to remove the large regex entirely
* Commands E, e and f allow zero or one argument; the other commands require no argument
* None of these commands allows an address prefix, e.g. 1,2P is invalid
* When testing against GNU ed I discovered "f FILENAME" should still print the filename when setting it
* Later the remaining commands can be removed from the large regex if calculateLine() function strips address prefix from $_ at start of edParse()
```
%perl ed # empty buffer and no saved filename
P     ---> toggle * prompt
*e a.c   ---> start editing a file
197
*H   --->  toggle auto-help
*123d
?
invalid address  ---> error message displays by itself
*H  ---> disable auto-help
*,d   ---> delete all lines …
```
=> ed: start breaking up edParse()

bin/ed
* Standard ed allows a regex to be placed in front of a command
* Previously CalculateLine() supported this but the function was replaced by getAddr()
* Add a new condition in getAddr() to allow resolving /re/ command prefix to a line number
* Be careful to support repeated search for empty pattern
* test1: /include/n  ---> search for /include/, resolve line number and run n command
* test2: //l ---> repeat search using saved /include/ pattern, then run l command on matching line
* test3: /return/  ---> no command given with pattern still works
* test4: ```/a\/b/p``` --> search pattern includes escaped slash; run p command on matching line
=> ed: re-add support for /re/ address-mode

bin/ed
* ?re? is a valid prefix which searches backward
* Tested against GNU and OpenBSD versions
* test1: ?perl?n ---> search for previous instance of "perl" then run command n
* test2: ??l ---> search for previous instance of saved pattern "perl" then run command l
* test3: ```?\??p``` ---> search backwards for literal "?" then run command p
* test4: ```?\/\/?``` ---> search backward for literal "//" then show result
=> ed: support ?re? address mode

bin/ed
* Delete old code for handling repeated search since getAddr() now supports it
* edParse() must return true for a valid command, so defer to input() (its caller) to distinguish NoMatch and NoSavedPattern errors
* getAddr() may be called twice, and NoMatch/NoSavedPattern error could occur either time
* For "g" command, the NoMatch condition is not an error (no action is performed)
* Fix an issue with parsing 2 addresses: "2,n" is equivalent to "2n", not "2,$n"
* test1: "//l" ---> error: no previous pattern
* test2: ",/main/n" ---> run command n for lines ranging from 1 to the 1st match of /main/
* test3: "?NO LINE MATCHES THIS!!!?" ---> error: no match
* test4: "2,n" ---> just line 2
* test5: ",2n" ---> lines 1 to 2
* test6: ",n" ---> lines 1 to $Max
=> ed: fix no-match showing multiple error prompts

bin/grep
* I noticed that "grep -Fi pattern" was incorrectly listing matching lines in all lowercase
* When reading the code, this issue had already been fixed in closures $cls_fgrep_xiv and $cls_fgrep_xi
* Apply same pattern in closures $cls_fgrep_i and $cls_fgrep_iv (avoid modification of $_ in match function)
* test1: "perl grep -Fin INCLUDE a.c" ---> exercise $cls_fgrep_i (including line numbers)
* test2: "perl grep -Fiv INT a.c" ---> exercise $cls_fgrep_iv
=> grep: search results listed in lowercase

bin/kill
* The pod manual doesn't mention -L
* Follow BSD version and raise an error for -L, which is not standardised [1]
* With this patch kill will exit(1) but it will show signal listing (by default for bad signal spec)
* While here, write siglist() loop in a less noisy way
1. https://pubs.opengroup.org/onlinepubs/009696799/utilities/kill.html
=> kill: reject undocumented -L

bin/ed
* When testing "g" command against BSD version I discovered 1- and 2-address prefix is accepted
* Implement this by looking at ```@adrs``` in edSearchGlobal(); address list has been populated earlier in edParse()
* test1: g/include/p ---> process lines 1 to $Max
* test2: 1g/include/p ---> process only line 1
* test3: 1,2g/include/p ---> process lines 1 to 2
* test4: ,2g/include/p ---> same as test3
=> ed: allow address ranges with g command

bin/patch
* Patch::error() returns $ERROR
* In Patch::print_rejects(), $ERROR is incremented if rejected pieces are found during processing
* No other function updates $ERROR, so Patch::error() indicates if rejects are present
* die() calls are wrapped by an END-block which sets exit code to 1; follow standard and set it to 2 [1]
* Failure to detect a diff in the input is considered an error; call die() to indicate this
* Add EXIT STATUS section to pod as done in other scripts
* test1: "perl patch -x" ---> bad option, exit(2)
* test2: "echo BOGUS-DIFF-123 > bogus.diff && perl patch xargs bogus.diff" ---> no diff found, exit(2)
* test3: "perl patch dirname sort.diff" ---> mismatched diff which can't be applied, exit(1)
* test4: "perl patch a.c correct.diff" ---> diff applies with no failed parts, …
=> patch: standard exit code

bin/kill
* When entering an invalid named signal argument, e.g. -NOTVALID, kill shows an error with a list of valid signals 
* Do the same for invalid numeric signal arguments, e.g. -100000
=> kill: list valid signals for bad -NUMBER

bin/ed
* Rewrite how global command (g) is interpreted: for global mode ```@adrs``` will contain the line addresses to be processed (non-contiguous)
* Now the command can be called once and the ```@inbuf``` kludge can go away
* Support global mode in edPrint() for commands l,n,p
* Support global mode in edDelete() for command d
* When deleting in global mode the addresses are processed backwards so the 1st splice doesn't upset the subsequent array offsets saved in ```@adrs```
* Document in pod that "d" can now be used with v// and g//
* Bump version
* test1: 1,7g/t/d ---> delete lines matching /t/ only between lines 1 and 7
* test2: v/printf/d   ---> delete all lines not matching /printf/
=> ed: allow delete with g// and v//

bin/cut
* Range argument for -b is expressed as "a-b"
* Either a or b can be omitted, but not both
* "a-" means "from a to end"
* "-b" means "from 1 to b"
* Previously "a-" usage was not handled properly
* Found when testing against BSD version
* test1: "echo abcdefg | perl cut -b 2" ---> b
* test2: "echo abcdefg | perl cut -b 2-3" ---> bc
* test3: "echo abcdefg | perl cut -b -3" ---> abc
* test4: "echo abcdefg | perl cut -b 3-" ---> cdefg
=> cut: fix usage of -b address range

bin/mail
* When testing OpenBSD's mail command I viewed a mailbox with 2 items
* Typing "0" and "3" results in the same "invalid message id" error (1 and 2 are valid IDs in this test)
* This version treats 0 and 3 differently, terminating the program for ID 0
* It is inconvenient having to start mail command again, so avoid fatal error
```
%perl mail # patch applied
Loading the mailfile /home/bob/mbox
Mail [0.02 Perl] [linux]
N  1                                    154/ 904 (no subject)
2           nobody  Mon Sep 17 00:00  41/1036 [PATCH] another patch
3           nobody  Mon Sep 17 00:00  32/ 706 re: [PATCH] another patch
4           nobody  Sat Aug 27 23:07 120/3138 [PATCH 1/2] GIT: Try all addr
5           nobody  Sat Aug 27 23:07 107/3764 [PATCH] Fixed two bugs in git
6           nobody  Mon …
```
=> mail: fatal error for message id 0

bin/ed
* The input g/search1/s/search2/replace/ allows search1 to filter the lines to process, then search2 determines the text to replace per line
* Don't return in the condition for g & v commands; this allows the subsequent condition to determine the command to be run globally
* Using rindex() to find a delimiting '/' was incorrect because s/// confuses things with its own '/'
* Adapt some code from getAddr() to find delimiter of search1 regex
* test1: ```g/\//s/$/ NL/```   ---> append the text " NL" to all lines matching literal '/'
* test2: ```v/\//d```   ---> delete all lines not matching literal '/'
=> ed: implement global substitute

bin/du
* Add validation that $blocksize must be a positive integer
* Setting BLOCKSIZE="-0" would result in a division by zero
* Possibly du doesn't need to access any environment variables, but for now keep BLOCKSIZE
=> du: runtime error for bad environment value

bin/ed
* Empty search pattern provided to g and v should be interpreted in the same way as for a basic search with //, i.e. repeat the previous search using saved pattern
* I found this when testing against BSD version
* test1: g//l  ---> error: no previous pattern
* test2: /t    ---> find next /t/ and save search pattern
* test3: g//n  ---> run n command globally for lines matching saved pattern /t/
* test4: v//d ---> run d command for all lines not matching /t/
=> ed: implement repeat search for g// & v//

bin/ed
* Other versions of ed allow numbered output with binary escapes
* "p" is simply print
* "pl"/"lp" == "l" and "pn"/"np" == "n"
* "nl"/"ln" == number the lines and print the line in escaped mode
* To make this work edPrint() needs to selectively allow an argument (technically a "command suffix")
* test: g/rem/ln   ---> edPrint() is called with $mode==$PRINT_BIN and $do_num is set based on $args[0]
=> ed: allow l,n,p to be combined

bin/cut
* handle_b() had been updated with more correct parser for field lists (including sorting fields and ranges)
* Move the list-spec parser into its own function and use it in handle_f() for "cut -f"
* handle_f() was looping over ```@hunk``` multiple times (incorrectly) when list-spec contained a comma
* Output tested against GNU version
* test1: echo 'a:b:c:d:e:f' | perl cut -d ':' -f 3,2,2,1
a:b:c
* test2: echo 'a:b:c:d:e:f' | perl cut -d ':' -f -2
a:b
* test3: echo 'a:b:c:d:e:f' | perl cut -d ':' -f 3
c
* test4: echo 'a:b:c:d:e:f' | perl cut -d ':' -f 3-
c:d:e:f
* test5: printf "a:b:c:d:e:f\nhey\n" | perl cut -d ':' -f 3-
c:d:e:f
hey
* test6: printf "a:b:c:d:e:f\nhey\n" | cut -s -d ':' -f 3-
c:d:e:f
* test7: printf "a:b:c:d:e:f\n" | perl cut  -d ':' -f 100
["\n" printed]
=> cut: consistent field list handling for -f

bin/ed
* Previously typing wq was supported, but recent changes in edParse() broke it
* Command suffix processing goes before check for a space, then optional filename argument
* This time document wq in pod
=> ed: make wq shortcut work again

bin/pr
* Follow semantics of OpenBSD version
* Suppress file header with: pr -h ''
* Don't ignore "pr -h 0" because "0" is a valid header
* Also remove unused param $col from create_col(), which is never called with any params
=> pr: more compatible -h option

bin/ed
* ";" by itself is taken to mean current address to end, i.e. ".,$"
* "A1;A2" expression is the same as "A1,A2"
* ";A2" expression works like ".,A2"
* I tested the following combinations...
,p   ---> all lines
%p   ---> all lines
;p   ---> current line to end
1,p  ---> only line 1
1%p  ---> not supported
1;p  ---> only line 1
1,2p ---> range 1-2
1%2p ---> not supported
1;2p ---> range 1-2
,2p  ---> range 1-2
%2n  ---> range 1-2
;20p ---> range current line to 20 (error if current>20)
=> ed: implement ';' addressing mode

bin/ed
* This version of ed is different to the C versions because it's trivial to run it under the perl debugger, e.g. setting a breakpoint in edParse() or input()
* The debug info produced by running "ed -d" is limited, and other versions of ed don't provide an equivalent option
* Sync usage string + SYNOPSIS
* Add symbolic exit codes as done in other scripts
=> ed: retire non-standard debug flag -d

bin/grep
* When testing against OpenBSD and GNU versions, the meaning of -a is to list the matching lines of a binary file 
* Without -a, binary files should be searched but only a "Match" message is printed
* Change the current meaning of -a to make this version more compatible
* Update pod manual and description in usage()
```
%perl grep BASH /bin/bash
grep: /bin/bash: binary file matches
%echo $?
0
%perl grep BASH /bin/echo
%echo $?
1
%perl grep -a BASH /bin/bash
/usr/share/bashdb/bashdb-main.inccannot start debugger; debugging mode disabledrbash/bin/shI have no name!??host??run_one_command-cENVBASH_ENVHISTFILEcannot set uid to %d: 
...
%echo $?
0
%perl grep -a BASH /bin/echo
%echo $?
1
```
=> grep: search binary files

bin/what
* My Linux system doesn't have a "what" command
* The OpenBSD version prints each match on a separate line with a tab character prefix
* The standards document is clear about ```printf("\t%s\n", id_string)```, so follow that
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/what.html
=> what: compatible output text for match

bin/fold
* For some input files, fold would get stuck in a loop printing "\n when run with -b and -s options
* In this case fold_file_byte() is called instead of fold_file()
* The regular expressions $soft and $hard are expected to modify the length of $_ if they match
* The while-loop controlled by $_ length never terminated if neither regex matched
* Adding a condition to break out of the loop for no-match prevents the infinite loop
```
%perl fold -b -s ed  | head -n 2000 | less
...
00000c80: 676c 6520 6c65 7474 6572 2063 6f6d 6d61  gle letter comma
00000c90: 6e64 2065 6e74 6572 6564 2062 7920 7573  nd entered by us
00000ca0: 6572 0a6d 7920 2463 6f6d 6d61 6e64 7375  er.my $commandsu
00000cb0: 663b 2020 2020 2020 2020 2020 2020 2020  f;              
00000cc0: 2020 2023 2073 696e 676c 6520 6c65 …
```
=> fold: infinite loop for -bs

bin/ed
* For greater compatibility with BSD, either '-' or '^' can be specified to mean CurrentLine - 1
* GNU ed 1.19 doesn't support '^'; I didn't test if v1.20 supports it
* Standards document mentions '^' is considered a historical feature; however POSIX does not prohibit it [1]
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ed.html
=> ed: support '^' address

bin/chgrp
* The "group" argument to chgrp can be either a name or an ID
* When testing against GNU and OpenBSD I found that this version did not accept an ID argument
* Allow numeric ID to be passed to chown()
* Also fix a problem where uid=0 from stat() was treated as stat() failure; it is normal for uid=0 to be root
=> chgrp: accept group ID argument

bin/wump
* Global list ```@P``` is not required; ```@P``` is declared locally within shoot() --- this was found by perlcritic
* Remove unhelpful comments at end of file
* Factor shoot_or_move() prompt function so there's one statement per line, and one return statement
* Maintaining the BASIC code comments is impossible
=> wump: unused variable

bin/grep
* When run on a binary file, grep should search it as a binary file
* Regular grep should not decompress a file (this version was decompressing based on file extension)
* Adopt the -Z flag from OpenBSD which makes grep behave as zgrep [1]
* Sync POD manual
1. http://man.openbsd.org/grep#Z
```
%gzip -9k ar # create ar.gz
%perl grep ar ar.gz # original filename stored in binary
grep: ar.gz: binary file matches
%perl grep perl ar.gz # no match
%perl grep -Z perl ar.gz # match after decompression
#!/usr/bin/perl
License: perl
```
=> grep: don't automatically decompress

bin/ls
* When temporarily enabling warnings.pm I observed a warning in DirEntries(): closedir() attempted on invalid dirhandle $dh
* opendir() was always called even if the file was not a directory
* Delay the opendir() call until we know that we don't want to list a regular file
* opendir() should not happen if running "ls -d", or if the argument to DirEntries() is not a directory
=> ls: avoid invalid closedir()

bin/mail
* For compatibility with OpenBSD mail program, "   q" should be interpreted as "q"
* While here, fix the name of the "visual" command (aka "v") in the pod manual (entering "visal" does nothing and it's invalid on OpenBSD too)
=> mail: trim leading spaces from command input

bin/rmdir
* The old error message is not specific enough to be helpful
* Allow rmdir() to fail instead of performing file tests first
* $! will specifically say whether a file argument does not exist, or is not a directory
=> rmdir: better error reporting

bin/chown
* This is similar to the patch for chgrp command
* Fall back to treating numeric argument as a uid if username resolution failed
* The code surrounding stat() had the same bug as for chgrp, i.e. existing uid=0 was treated as a failed stat()
=> chown: allow numeric UID argument

bin/split
* When splitting input file with -p PATTERN, allow pattern to be '0'
* Probably this is a bad pattern to use, but ignoring -p0 is not correct
```
%printf "aa\n0\nbb\n0\ncc\n" | perl split -p0
%for f in xaa*; do echo "$f:"; cat $f; done
xaaa:
aa
xaab:
0
bb
xaac:
0
cc
```
=> split: allow /0/ pattern split

bin/cal
* When temporarily enabling warnings.pm I noticed two patterns which generated a warning
* In get_year(), regex check was done too late after the variable has been treated as a number
* In print_year()/print_year_jd() the month lists being combined might have a less elements; explicitly treat those as empty string
=> cal: deal with warnings

bin/ed
* Reduce duplicated code by rolling edSearchForward() and edSearchBackward() into one function
* While here, remove a comment about GNU ed setting current line for '=' command ("/pattern/=" command in GNU ed does not set current line)
=> ed: generic search function

bin/grep
* The -1 flag meant to limit searches to one match per file
* The -1 flag is incompatible with GNU and BSD grep because they interpret -1 as -C 1, i.e. show one line of context around each match
* Implement the common way to limit searches by adding -m (maximum match) option
* Allow -m0 because this is supported in the other versions
* test1: perl grep -1 pat file1 file2 ---> no longer supported
* test2: perl grep -m 2 pat file1 file2 ---> two matches per file
=> grep: replace -1 with -m NUM

bin/grep
* Show non-matching context lines after a matching line
* A new match may occur within the context lines being displayed; this resets the context counter unless the match limit (-m value) was already reached
* Display a line of "--" to indicate the end of the context block
* If -A is used with -n, follow line number with '-' instead of ':' to indicate context lines
* When -A is used with -m, terminate the search at the end of the context and not the exact line triggering match limit
```
%perl grep -n -A 8 perl ar # test1: context bleeds into the line8 match
1:#!/usr/bin/perl
2-
3-=begin metadata
4-
5-Name: ar
6-Description: create and maintain library archives
7-Author: dkulp
8:License: perl
9-
10-=end metadata
11-
12-=cut
13-
14-use strict;
15-
16-use POSIX qw(strftime);
--
%perl grep -n …
```
=> grep: implement -A context option

bin/grep
* For -B, context lines before a matching line are saved in a buffer and emptied when a match occurs
* -C can then be added with no extra logic as a shortcut for -A and -B
* The old meaning of -C goes away, but I'm not aware of any other version of grep that had that special count feature
* To test, I modified the file "ar" so it has two consecutive lines matching "this"
```
%perl grep  -n -C 5 this ar
452-on the command line to ``select'' archive files for an operation, only
453-the first file with a matching name will be selected.
454-
455-The normal use of ar is for the creation and maintenance of libraries
456-suitable for use with the loader (see ld(1)) although it is not
457:this is good
458:restricted to this purpose.
459-
460-=head2 OPTIONS
461-
462-I<ar> accepts the following …
```
=> grep: implement -Bn and -Cn

bin/ed
* Mark is a standard feature in ed and it's not very much code to support it
* Resolving a mark that doesn't exist results in Invalid Address error
* 1,2kx ---> mark x as 2
* 1kx ---> mark x as 1
* kx ---> mark x as CurrentLine (default)
* 'x,$n ---> run n command from marked line x to end of buffer
=> ed: basic support for mark (k) command

bin/chmod
* Address the same issue as for previous chgrp commit: 420f8b2a12025bb609e33f0c1741116433263abe
* The argument list could have 3 files, and chmod() is successful for one but the remaining args fail
* It would be nice to introduce a regular usage() function in chmod later
```
%perl chmod 600 /etc/motd wordlist.txt /etc/passwd
chmod: failed to change mode for '/etc/motd': Operation not permitted
chmod: failed to change mode for '/etc/passwd': Operation not permitted
```
=> chmod: list filename in warning if chmod() fails

bin/chmod
* A failed chmod() is not a fatal error; the program will proceed to the next file argument but will exit(1) to indicate an error occurred
* Do the same in modify_file() if a file doesn't exist (this helps exitcode match the GNU version)
* Also introduce a regular usage() function
=> chmod: exit(1) if a file fails

bin/grep
* BSD and GNU versions do not require a space between -e/-f and the option argument
* This version did not raise an error, but option arguments without a space resulted in incorrect behaviour
* Remove -e and -f from getopts() option string because they are handled earlier
* test1: perl grep -e0 -e 1 ar ---> patterns 0 and 1 in file ar
* test2: grep -fwordlist.txt.old -f pat1 xargs ---> patterns from file wordlist.txt.old and pat1, searching against file xargs
=> grep: make space after -e or -f optional

bin/du
* Failure to access one file argument is considered a non-fatal error which deserves an exit(1) at end of program
* Tested against GNU version
```
%perl du -k  a aaaaaaaa
66	a
du: cannot access 'aaaaaaaa': No such file or directory
%echo $?
1
```
=> du: exit code 1 on error

bin/uniq
* Standards document explains uniq has two optional file arguments, input and output [1]
* GNU and BSD versions follow this; do the same and stop treating subsequent file arguments as extra input files
* test1: printf "a\na\nb\nc\nc\n" | perl uniq ---> implicit stdin and stdout
* test2: perl uniq a.c ---> read a.c, write to stdout
* test3: perl uniq a.c b.c ---> read a.b, write to b.c
* test4: perl uniq A B C ---> invalid, too many args
1. https://pubs.opengroup.org/onlinepubs/009696799/utilities/uniq.html
=> uniq: one input file

bin/grep
* On *BSD, there's no difference between grep -r and grep -R, so adding -R in this version allows for greater compatibility
* Also add missing validation: $pattern can be undefined when shifting off ARGV, and it's a fatal error if we get no patterns (found with "perl grep -r")
=> grep: add -R alias for -r

bin/chown
* Previously the usage "chown USER file" was changed to allow numeric user ID for USER
* When testing against GNU version, the usage "chown USER:GROUP file" should handle a group ID or a group name
* test1: perl chown 0:0 file ---> user=root, group=root on my Linux system
* test2: perl chown root:8 ---> also valid, where gid 8 resolves to "mail" here
=> chown: allow numeric group argument

bin/mail
* On Android I have Termux, and vi is installed as /data/data/com.termux/files/usr/bin/vi
* Remove the assumption that vi is installed under /usr/bin
* With this patch, perl will look for vi within $PATH
* Tested on OpenBSD and Termux/Android
* Environment variable $VISUAL still takes precedence if it is set
=> mail: more reliably find vi command

bin/grep
* Testing against old commit 504caa95c6979a507504365047af3dd13d30fac8, "grep -f empty" resulted in exit(1), i.e. no match
* A recent commit introduced a bug where ARGV would be shifted incorrectly if an empty file was passed as argument to -f
* Follow GNU grep and bypass the search in this case because we know there cannot be any matches
```
%touch empty && perl grep -f empty ar
%echo $?
1
```
=> grep: no match for empty pattern file

bin/ed
* Reject filenames starting with '!' for f command (other versions reject this)
* Implement "r !cmd" in edEdit() to read output of a shell command into the editor buffer
* Implement "w !cmd" in edWrite() to pass data from editor buffer to a shell command
* test1: 2r !ifconfig ---> output from ifconfig is added after line 2
* test2: 1,20w !cat -n ---> lines 1-20 from buffer are piped to "cat -n"
=> ed: shell command io

bin/mail
* The message about "strict" in the BUGS section of the manual was a reminder to make this change
* Do mechanically with set/get functions what was being done with AUTOLOAD
* Attribute "status" in object "message" was never used
* Attribute "append" in object "mailbox" was never used
* Many local variables were not declared before use
* No-strict had allowed list-deref of undef in replyCC()
* Bump version
```
%RELAYHOST=localhost perl mail  -f mbox # initial test (connect error is expected)
Loading the mailfile mbox
Mail [0.04 Perl] [linux]
N  1                                      0/ 808 (no subject)
2           nobody  Mon Sep 17 00:00   0/1036 [PATCH] another patch
3           nobody  Mon Sep 17 00:00   0/ 706 re: [PATCH] another patch
4           nobody  Sat Aug 27 23:07   0/3138 …
```
=> mail: add strict

bin/grep
* Checking length of $pattern is unreliable because it is valid for a pattern to have zero-length (meaning match-all)
* I found this when testing the -f option but the logic applies to other usages of grep
```
%md5sum a.c
c9fd7ff4cb5b01981a2a362f82f44c89  a.c
%perl grep -F '' a.c | md5sum 
c9fd7ff4cb5b01981a2a362f82f44c89  -
%printf "\n" > pat0 && perl grep -f pat0 a.c | md5sum
c9fd7ff4cb5b01981a2a362f82f44c89  -
%perl grep -e '' a.c | md5sum 
c9fd7ff4cb5b01981a2a362f82f44c89  -
```
=> grep: fix logic for empty patterns

bin/chmod
* In "chmod -R -L" case, check readlink() return value before use
* If readlink() failed (which shouldn't happen), set exit code for failure
* Reduce readlink() calls from 2 to 1 per file argument to "chmod -R -L"
```
%ls -l what whatlnk
-rwxr-xr-x 1 pi pi 3123 Nov 12 07:18 what
lrwxrwxrwx 1 pi pi    4 Nov 21 12:28 whatlnk -> what
%perl chmod -R -L 400 whatlnk
%ls -l what whatlnk
-r-------- 1 pi pi 3123 Nov 12 07:18 what
lrwxrwxrwx 1 pi pi    4 Nov 21 12:28 whatlnk -> what
```
=> chmod: check for readlink() failure

bin/ed
* Factor functions such as edWrite() to return E_* error value if something went wrong, or false if everything is ok
* This makes things more consistent because previously some functions returned true for success, but some didn't
* No intended functional change
=> ed: return error from command functions

bin/ed
* Argument parsing within edMove() was a bit broken
* edMove() implements the "t" and "m" commands
* I noticed that bogus values for $args[0] were being accepted, e.g. n > maxline()
* The argument is supposed to be any valid address, not just an address specified as a number
* getAddr() already contains the functionality we want, so call it
Tests:
1,2m/main/ ---> append selected lines after regex match
1,2m/mainxxxxxx/ ---> nomatch error
1,2m// ---> use saved pattern for search (fails if no pattern was saved yet)
1,2m. ---> append lines after current address (explicit)
1,2m ---> append lines after current address (default)
1,2m$ ---> append lines after last line
1,2m'x ---> append lines after marked line x (fails if nothing was marked for x yet)
24,25m0 --> move selected lines to start of …
=> ed: m command accepts address argument

bin/ed
* When adding getAddr() call to edMove() I noticed getAddr() doesn't raise error for n>maxline case
* This logic was only in input() before, but it seems more correct for getAddr() to check the maxline limit
* Also add missing check in edMove() for stray characters leftover after calling getAddr(); the argument to m should be a single address so anything remaining is invalid input
* test: 1,2m.A ---> "A" suffix invalid after "."
=> ed: getAddr() vs maxline()

bin/mail
* Declare VERSION_MESSAGE() as done in other scripts which use getopts()
* It is not necessary to print a splash message when the program starts; displaying the mailbox is enough
* Printing os in version message is not required (English.pm was only used for $OSNAME which disappears in this patch)
* The -v option is for toggling debug information, and it doesn't change
=> mail: add --version

bin/ed
Rename 2 globals for consistency
* $EXTENDED_MESSAGES looked like a constant but is in fact toggled in edHelp()
* $SupressCounts becomes $Scripted because scripts calling ed non-interactively often run "ed -s"; name taken from BSD ed [1]
1. http://cvsweb.netbsd.org/bsdweb.cgi/src/bin/ed/main.c?annotate=1.30.2.2
=> ed: clarify global var names

bin/fold
* When running fold without -b flag, adj_col() is used---called through fold_file()
* "fold -b" is a different algorithm and does not use adj_col()
* Remove the $Byte_Only check in adj_col() because this can never happen
* Also make the usage() function more standard by not taking a parameter
=> fold: remove assert in adj_col()

bin/expr
* When testing OpenBSD expr, +n and -n numbers are allowed, so permit them here
* I didn't test NetBSD version, but since it calls strtoll() I suspect it also permits +n and -n [1]
* Test: ```perl expr 2 \* \( -2 + +43 \)``` ---> 82
http://cvsweb.netbsd.org/bsdweb.cgi/src/bin/expr/expr.y?annotate=1.46
=> expr: allow unary plus

bin/install
* I might want to install something but make it temporarily not accessible --- "install -m 0 file dir"
* Numeric file mode 0 should be passed to chmod() but it was being ignored
* Problem1: modify_file() assumes $mode is not zero
* Problem2: install_files() assumes $opt{m} is not zero
* Apply same logic in install_dirs() because that seems wrong too
* In install_files(), calculating the symbolic file mode is not required in the "non-unix" case, where modify_file() would never be called (I noticed this when comparing install_dirs())
=> install: -m0 option is valid

bin/hangman
* If you reach the end of a game and see the PLAY AGAIN prompt, eof will cause the program to terminate
* Do the same if eof occurs after the GUESS A LETTER prompt; the NetBSD version handles this in getguess() [1]
* test: echo sword > wordlist.txt  && echo hi | perl hangman # now terminates 
1. http://cvsweb.netbsd.org/bsdweb.cgi/src/games/hangman/getguess.c?annotate=1.10
=> hangman: consistently handle eof

bin/install
* When using symbolic permissions with '=', the resulting file permissions weren't right; here's what I found...
* mod() should be passed the original file to stat(), but it was being passed the new target file after File::Copy::copy() created it
* Base permissions for "absolute" symbolic permissions (i.e. those set with '=') are zero, so it is not correct to stat() the original file in this case
* The statement clearing bits in ```%perms``` for operator '=' in loop should only clear bits for $who the current iteration looks at
```
%perl install -m u=rwx,g=rx,o=x comm a/comm # -m 751
%perl install -m u=rwx,g=r comm a/comm # -m 740
%perl install -m 'a=' comm a/comm # -m 0
```
=> install: fix absolute symbolic permissions

bin/chmod
* Sync mod() changes with bin/install
* chmod would get some of the following symbolic permissions wrong...
```
perl chmod a= A               (0000/----------)
perl chmod a=rwx A            (0777/-rwxrwxrwx)
perl chmod u=rw A             (0600/-rw-------)
perl chmod u=rwx,g=w A        (0720/-rwx-w----)
perl chmod u=rx,g=r,o=r A     (0544/-r-xr--r--)
```
=> chmod: symbolic file permissions

bin/id
* Avoid calling die() for better control of exit code
* The pod manual stated the exit code would be 1, but for the NoSuchUser case it wasn't
=> id: exit 1 on failure

bin/ed
* The usage "f abc/" is technically invalid because it would point to a directory
* Subsequent "e" or "w" commands fail because ed does not operate on directories
* GNU ed 1.20 added validation to prevent this usage; add it here because it would flag bad user input slightly earlier
=> ed: disallow trailing '/' when setting filename

bin/units
* BSD version allows FILE argument to -f option with and without a space
* Remove --file option because it is not a standard thing (DragonFlyBSD, NetBSD & OpenBSD don't have it)
* Previously the regex for -f option would allow bare '-' but now that is treated as an invalid option
* Also allow '--' to terminate options (found when testing against OpenBSD)
=> units: allow -fFILE

bin/hexdump
* Remove -u which does not exist in OpenBSD or util-linux version
* Add a version number to the script
=> hexdump: retire -u option

bin/glob
* globtest() wasn't called and this kind of test probably belongs in a separate harness script
```
%for glb in 'x*' 'y*'; do echo -n 'A: '; echo $(perl glob "$glb"); echo -n 'B: '; echo $glb; echo; done
A: x.bc x.pl xaaa xaab xaac xargs xx xxx xxyy
B: xaaa xaab xaac xargs x.bc x.pl xx xxx xxyy
A: yes yo2 yoooo
B: yes yo2 yoooo
```
=> glob: unused function

bin/ed
* Extending from commit 5f9377d8b67fbbb8dfbd745566bf3a9ea3299309, we know that filenames '.' and '..' are reserved for directories so make these names also raise an error in edFilename()
* The filename '...' is not reserved
=> ed: reject filename of '.' or '..'

bin/hexdump
* Default output format switches to two-byte hex to match other versions, with canonical hex+ascii as -C option
* Add -b, -d, -o and -x format options as supported on OpenBSD
* Switch default output to filter duplicate lines, with -v option to disable this filtering
* Sync usage string and pod manual
=> hexdump: add more formats

bin/hexdump
* Move repeated code for the -v option up a level, from the individual formatter functions into dofile()
* The saved string $prev can't be declared in dofile() because dofile() will be called again for the first line of the next file (hexdump sees them as one joined file)
=> hexdump: common duplicate line check

bin/od
* perlcritic issued a warning that the variable $len in zeropad() was aliasing a global variable
* I found that $len doesn't need to be a global
* dump_file() and do_skip() save the read() return value into $len
* Beyond checking for a failed read, the value of $len was not needed
=> od: remove global $len

bin/od
* The -v flag works the same as for hexdump command, displaying all lines including duplicated input
* diffdata() compares the current line with previous line; if the -v flag is given there's no need to call it
* Save $lastline if we're not in verbose mode and we saw a difference in the data
* $ml becomes true when we saw a duplicate; this prevents '*' from being printed multiple times
=> od: factor dump_line()

bin/bc
* When running "bc -l", the return values for a(), c() and s() didn't seem right
* Instead of parsing these functions as bc code, I propose defining these as builtin perl functions (this is slightly easier to work with)
* Import Math::Trig for the benefit of atan()
* When running in bignum mode, s() function could hang; adapt a workaround of converting temporary argument to LittleNum so it can be passed to atan() etc [1]
* The mathlib functions e(), j() and l() are still defined as bc code but could be converted to builtin later
1. https://raw.githubusercontent.com/caldwell/pc/master/pc
=> bc: convert trig functions to builtin

bin/glob
* When enabling debug environment variable, print debug output to STDERR
* Currently the debug output interferes with the regular items printed to STDOUT
```
%export DEBUG_FASTGLOB=1
%for f in $( perl glob 'x*' ); do echo "F=$f"; done
regexp is x.*
component re is qr(\Ax.*\Z)
F=x.bc
F=x.pl
F=xaaa
F=xaab
F=xaac
F=xargs
F=xx
F=xxx
F=xxyy
```
=> glob: normal vs debug output

bin/tail
* tail -f flag changes how all the file arguments are handled, i.e. tail_f() function is called
* When passing directory arguments to tail -f, ```@dirlist``` contains all the directory args
* get_existing_files() is called for each directory
* Switch get_existing_files() to use catfile() to join directory name with filenames from readdir()---this removes the assumption that the OS uses '/' as a directory separator
=> tail: portable -f DIR

bin/mkdir
* Doing a sync of function mod() from bin/chmod wasn't enough
* Call mod() without a file argument because symbolic permissions should assume a default value of 0777
* Now the mod() function diverges slightly from bin/chmod since $mode initialises to '777', not '000'
* The 0755 permission applies when no -m option is given, but 0777 is used as base permission when constructing a symbolic permission (which is calculated relative to a base permission)
* I tested some mkdir usages against OpenBSD...
* test1: mkdir d ---> permissions of 0755
* test2: mkdir -m a= d ---> no permissions (symbolic)
* test3: mkdir -m 0 d ---> no permissions (numeric)
* test4: mkdir -m u=rwx,g=rx ---> permissions of 0757 (o=7 because the default 0777 permission applies)
* test5: mkdir -m u=rwx,g=rx,o= ---> …
=> mkdir: compatible permissions

bin/unshar
* Instead of ignoring unknown options, show the user which options are expected
* User might type -e option, expecting it to be there because GNU sharutils has it
=> unshar: print usage string

bin/glob
* When temporarily enabling warnings.pm, glob prints a warning: FastGlob::explode_glob() called too early to check prototype
* Remove the prototypes to silence the warning
* I didn't notice any other warnings when testing some glob inputs
=> glob: remove function prototypes

bin/hexdump
* Avoid fatal error for directory arguments
* Print a warning for a directory, then proceed to next argument
* Use case tested: hexdump -C . .. file.txt
=> hexdump: warn for directories

bin/ed
* When running an ed script the exit code is important
* If any command in the script fails, edWarn() will be called and $Error will be set; this should translate to a failure exit code
* Tested against GNU version  (both tests show successful commands after the failed command)
```
#test1: q command after invalid address error
470
*H
*100p
?
invalid address
*10p
/* this? */
*q
%echo $?
1
#test2: wq command after invalid address error
470
*H
*100p
?
invalid address
*1,2wq new.txt
39
%echo $?
1
```
=> ed: standard exit code

bin/tail
* When removing function prototypes I noticed two issues causing a fatal error thanks to strict.pm...
* The first 2 args of tail_f() are supposed to be array-ref
* The first 2 args of get_existing_files() are supposed to be array-ref
* With this patch, "perl tail -f regular.txt" doesn't die, and follows changes to the file as expected
* I guess with the old prototypes the parameters were being coerced, but that makes the code harder to audit
* Move one statement so it appears after "use strict"
=> tail: fix function params

bin/bc
* When previously expanding the number of builtin functions, I didn't notice that bi_sqrt() would incorrectly call sqrt(undef) if I type sqrt() at bc prompt
* Other versions of bc raise an error for this, and it's a good idea to flag bad function usage
* This patch adds min-args check to all the builtin functions; all take a single arg except j() which takes two
* When I pass too many args to c() I already see an error
=> bc: minarg checks for builtin functions

bin/fmt
* I was annoyed with the old fmt algorithm because a word gets incorrectly chopped in the middle
* Take a hint about parsing from NetBSD fmt.c source which splits input into word/whitespace_suffix pairs
* Take another hint about paragraphing from GNU version output
* We know the paragraph is finished when the indentation level of current word differs from the previous, or if we see two newlines in a row
```
%ifconfig | head -n 16 | perl fmt -w 52
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500 
ether dc:a6:32:e1:12:27  txqueuelen 1000  
(Ethernet) RX packets 0  bytes 0 (0.0 B) 
RX errors 0  dropped 0  overruns 0  frame 0 
TX packets 0  bytes 0 (0.0 B) 
TX errors 0  dropped 0 overruns 0  carrier 0  
collisions 0 
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536 
inet 127.0.0.1  netmask …
```
=> fmt: stop breaking up words

bin/glob
* A tilde can optionally be followed by a username
* If a provided username is not found, treat the input as no-match instead of raising an error
* This is consistent with Linux/bash, OpenBSD/ksh and the perl builtin glob() function
* If '~' appears without a username, it is substituted for the current user's home directory
* Remove some '&' sigils from &xzy() function calls---glob() now gets called with fully qualified name
```
%echo ~mail/a # valid user
/var/mail/a
%echo ~mayel/a # not found
~mayel/a
%echo ~/a
/home/pi/a
```
=> glob: don't raise error for unknown user with '~'

bin/bc
* De-duplicate: Mathlib functions are already documented under REFERENCES so the pod comment can be removed
* De-duplicate: Command options are already documented under DESCRIPTION
* Typos: "assignent", "assigment", "generats"
=> bc: pod update

bin/ed
* The undo command (u) was listed in a TODO comment
* There's only 1 level of undo, i.e undo will undo itself
* This implementation which assumes /tmp has enough space to store a copy of the buffer
* Write a new undo buffer if a modification was detected
* According to other versions, the current line pointer should be updated too, but I want to handle this later
* Remove some ancient comments; perl coolness *is* a guiding principle
* Document undo in POD
=> ed: add undo feature

bin/ed
* GNU and OpenBSD versions restore line number at same time as restoring editor buffer in undo operation
* This is needed because $CurrentLineNum might not point to a valid address anymore
* For example, run "$a" command to append lines to end of buffer (currentLine becomes new maxLine), then run "u" to undo the append (buffer shrinks, maxLine reverts)
=> ed: update current line in undo

bin/mail
* If mail command is invoked with arguments it assumes those are addresses to send mail to, but running "mail -f mbox" is not compatible
* Raise an error and print usage string, as done in OpenBSD version
* Also use catfile() when constructing a default value for mailbox path
=> mail: -f usage forbids extra args

bin/patch
* Test case: perl patch orig.c .
* Original file to patch is a regular file, patchfile argument is a directory
* Previously patch would exit(0) for this case, but doing this fails to notify the user that anything went wrong
* Tested against GNU version
=> patch: patchfile argument may not be a directory

bin/cp
* No *cwd() functions are used in bin/cp
=> cp: unused import

bin/diff
* $diff_type is either "ED" or "REVERSE_ED" for output_ed_diff()
* For REVERSE_ED type, range is two numbers separated by a space, and action is printed before the range, e.g. "d3 30" instead of regular "3,30d"
* Check the value of $diff_type only once
=> diff: simpler output_ed_diff()

bin/tail
* GNU version terminates "tail -f" instance on ctrl-c
* Allowing ctrl-c to terminate program will do what the user expects
* Steal the existing SIGQUIT handler for the purpose of showing file report
* Update pod manual; only SIGQUIT needs to be mentioned now
=> tail: less confusing signals for -f flag

bin/touch
* Truth check for option -t argument prevented validation in parse_time() from running
* "touch -t 0" isn't valid because a timespec requires >1 character
* Style: remove "next" statement on utime() failure because there is no subsequent code to skip
=> touch: -t0 is invalid

bin/which
* As done in other scripts, join filename to base directory with catfile() because it abstracts some OS details
* Now the global $file_sep can be removed
* I didn't test this on Mac OSX or old MacOS, but I expect catfile() won't do any harm for OSX case
=> which: retire dir-separator variable

bin/pr
* A typo in the options handling code prevented $roundrobin from being set
* This patch allows the round-robin logic to be verified (I haven't investigated the output for -a yet)
=> pr: -a flag not recognised

bin/expr
* The old expression parser didn't work for some basic expressions I tested
* It was a bit confusing to debug the old code because everything happened in the one evaluate() function
* Replace the code with a parser based on the OpenBSD version
* Different operator priorities are delegated to different functions so overall this is a little clearer
* Add COPYRIGHT and AUTHOR sections in pod
```
%perl expr \( 1 \+ 1 \) \* 200
400
%perl expr "true" '&' ''
0
%perl expr 0 '|' 'true'
true
%perl expr 2 '*' 3 '+' 4
10
%perl expr 2 '+' 3 '*' 4
14
%perl expr "hotel" \: "ho"
2
%perl expr "hotel" \: "tel" # no match: regex is implicitly tied to start of string
0
```
=> expr: improved parser

bin/dirname
* Spell checker found a typo in the dirname manual
* The sentence containing the typo is not very useful because it talks about the author of the original manual; I'd prefer to remove it than correct the typo
=> dirname: pod typo

bin/lock
* When testing lock with a 1 minute timeout, my terminal text was invisible after lock times out and exits
* In the alarm handler, be careful to enable echo before the program finishes
=> lock: re-enable term echo

bin/ed
* When testing ed I found getAddr() was missing the code to handle +n and -n addresses relative to currentLine
* This is useful for constructing ranges
* For the tests I 1st jump to line 12 by typing "12"
* test1: -10,.nl    ---> list lines 2-12
* test2: .,+10nl  ---> list lines 12-22
=> ed: +n and -n relative addresses

bin/what
* Directory arguments are treated as a file that doesn't contain any matches
* Add explicit directory handling code to avoid reading a line from a directory, which would always fail
* Tested against OpenBSD
```
%perl what .. /bin/bash not-exist
..:
/bin/bash:
Bash version 5.1.4(1) release GNU
Unable to open 'not-exist': No such file or directory
%echo $?  # bash contained a match
0
```
=> what: bypass readline for directory argument

bin/paste
* Each iteration of the input loop initially checks if any input files still have data to read
* Leave inner file check loop early if 1st file is still ok (no need to check 2nd file)
* I confirmed that the same output is produced as for an older commit; my test used 2 input files of different length
=> paste: shortcut loop

bin/mkdir
* Improve code clarity by directly processing numeric file mode, instead of converting mode to a string and then back to a number
* The warning printed when chmod() failed incorrectly stated that stat() had failed
=> mkdir: reduce chmod() code

bin/touch
* Interpret options -r and -t as mutually exclusive
* The standards document provides a usage string which clarifies this [1]
* Previously if -r and -t were used together, one would be silently ignored
* Ignoring one option is confusing because it's unclear to the user which time value was actually used
* Style change: quote some hash keys to satisfy vim syntax highlighting ("m}" was seen as the start of a regex)
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/touch.html
=> touch: options -r and -t are incompatible

bin/grep
* When running "grep -f patfile file", ```@patterns``` list is populated from patfile
* Setting the value of $pattern to the final pattern in patfile is not needed
* Regression test: ```printf "this\nthat\n" > patfile && perl grep -n -f patfile ar```
=> grep: parse_args() tweak

bin/primes
* If run with 2 arguments, primes are displayed for a range from Start to End
* Normally an error was raised if End was smaller than Start, but the value of 0 was resulting in a default value unexpectedly
* Convert maximum to a constant so it could be changed easier to 64 bits (no dynamic size calculation is being done but at least the user can patch the one constant)
* Original test: perl primes 10 0
=> primes: raise error for start>end

bin/diff
* The number of parameters for Hunk::output_ed_diff() doesn't vary, i.e. $diff_type always follows after $fileref2
* Remove comment which adds more confusion than clarity
* Stack trace for diff -f
```
. = Hunk::output_ed_diff(ref(Hunk), ref(ARRAY), ref(ARRAY), 'REVERSE_ED') called from file 'diff' line 340
. = Hunk::output_diff(ref(Hunk), ref(ARRAY), ref(ARRAY), 'REVERSE_ED') called from file 'diff' line 185
```
* Stack trace for diff -e
```
. = Hunk::output_ed_diff(ref(Hunk), ref(ARRAY), ref(ARRAY), 'ED') called from file 'diff' line 190
```
=> diff: fix output_ed_diff() param declaration

bin/clear
* The OSPEED option being passed to Tgetent() is not required for clearing the screen
* Win32 perl might not have a working Term::Cap, so move the Tgetent() call into the eval just in case
* Tested on Linux and OpenBSD
=> clear: handling OSPEED is not needed

bin/fish
* Reduce code that needs to be maintained by using the shuffle() function from List::Util
* Small declarations change: explicitly import getopts() function
=> fish: retire fisher_yates_shuffle()

bin/grep
* I discovered that GNU grep 3.6 on my Linux system completely ignores GREP_OPTIONS
* I did a little reading and the feature had been removed from GNU grep (probably for security reasons)
* Original BSD grep and current OpenBSD grep don't have GREP_OPTIONS, so remove it (it's not a standard thing anyway)
=> grep: retire GREP_OPTIONS

bin/paste
* The input loop was written as a forever loop with an eof check at the top of loop body
* Convert the eof check to a function so the loop can be written as a "while"
* Also add --version as done in other scripts
* Regression test: perl paste /etc/motd /etc/motd
=> paste: factor loop

bin/expand
* ARGV is a list of files, which could be empty if stdin default is used
* Using a direct copy of ARGV provides no benefit
* The usage() function was previously converted to not take any params
=> expand: garbage collect a global

bin/mkdir
* Previously if running "mkdir -p" and the 1st part of an argument is not a directory, the program would incorrectly call mkdir() on the intermediate paths under it
* If I have a regular file 0, "mkdir -p 0/1/2" would show 3 errors because of mkdir("0/1") and mkdir("0/1/2")
* Restructure the program so ARGV can remain as a list of directories (now we don't need the explanation comment for the old confusing code)
* For -p flag, split directory into parts, calling a create_dir() function for each part
* split_dir() handles the case where the 1st part is not a directory, and drops the sub-directory parts
```
%touch 0
%perl mkdir -p 0/1/2 00 aa/bb/cc # only one error for 0/1/2 argument
mkdir: cannot create directory '0': File exists
%find 00 aa # everything was created except for 0/...
00
aa …
```
=> mkdir: suppress multiple errors for non-directory argument

bin/mkfifo
* Avoid calculating the default mode in the case where a numeric mode is supplied to -m (get_mode() just returns oct($opt_m) here
* Defer default mode calculation to a function which is used for 1) no -m option and 2) symbolic permission passed to -m
* Passing a value to umask() is not necessary because we only want to get the current value, and the mkfifo() call uses an explicit mode param
=> mkfifo: remove a global variable

bin/ed
* The initial implementation of relative addresses was too limited
* GNU and OpenBSD ed allow repeated +n, mixed +n and --++, as well as basing address from dot, dollar or a marked address
````
For tests, current address was set to 10.
3+3=    6 (+n pattern applied to literal 3)
3++=    5 (++ applied to literal)
++1=    invalid: ambiguous
+=      current + 1
.+=     current + 1
+1=     current + 1
.+1=    current + 1
.+3++=  current + 5: ++ follows +n
$---=   end - 3
$-3=    end - 3
$-3+3=  end (repeated +n)
'x-5,'x+5nl      list 5 lines of context around marked line x
```
=> ed: better relative addresses

bin/tac
* When processing multiple file arguments, and one file fails to open, exit(1) after processing all arguments to indicate something went wrong
* Found when testing against GNU tac
```
%echo \\0/ > exist && perl tac . .. notexist exist 
tac: '.' is a directory
tac: '..' is a directory
tac: failed to open 'notexist': No such file or directory
\0/
%echo $?
1
```
=> tac: exit(1) on error

bin/patch
* This version of patch first attempts to process an ed diff by running an external ed command, then falls back to processing the ed commands directly
* I noticed the external ed code was always failing but I didn't debug it until now
* Problem1: SIGCHLD happens normally when ed exits but it was being treated as an error (removing signal handlers fixes it)
* Problem2: write command sent to ed was not terminated by a newline, so ed would never run the command
* Problem3: after writing to o_file, the offset of filehandle $out was at byte 26, so the test line comparison wasn't correct
* With this patch I can process a simple ed diff on Linux without the code reaching PLAN_J
```
%cat ab.diff # change a.c into b.c
9,14d
%cp a.c acopy.c
%perl patch -e acopy.c ab.diff
Hmm...  Looks like an ed …
```
=> patch: fix external ed invocation

bin/uniq
When I run pod2text on uniq I see "compar- isons" printed on the same line. Allow the pod formatter to break lines where it sees fit, instead of manually hyphenating words.
=> uniq: pod fix

bin/tsort
* Standards document does not require that a '-' argument is interpreted as stdin [1]
* Follow BSD semantics and treat '-' as a regular file argument (tested against OpenBSD)
* Previous special meaning of '-' was not documented in the pod manual; add explicit text to explain when stdin is used 
1. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/tsort.html
=> tsort: '-' argument is not special

bin/unexpand
* When specifying multiple tabstops separated by commas, spaces are not allowed after the comma
* Remove spaces after comma from usage string to avoid confusion
* Also remove redundant copy of ARGV as done in expand commit d2196f96f69d5cb1b1c0774c6d56c73d9773bf19
=> unexpand: tweak usage string

bin/date
* Extra format string arguments are ambiguous and should result in an error
* select_format() is meant to select only one format; the use of grep() as a filter prevented it from catching invalid arguments
* Arguments which are not a valid format string should result in an error
* Found when testing against GNU date
* test1: perl date    # default in select_format()
* test2: perl date yo+%a   # not a valid date format
* test3: perl date +%a +%a    # too many formats
* test4: perl date +%a%a   # still works
=> date: catch invalid date arguments

bin/perlpowertools
* Add base64, bcd, seq, unlink and whoami to tools list
* In -l/-V modes, print output to stdout instead of stderr for easier use with a pager
* In -l/-V modes, exit(0) because there is no error
* Style: wrap long line of code
```
%perl perlpowertools -l 2> COMMANDS
%cmds=`grep '^bin' ../MANIFEST | sed -e 's/bin.//'`
%for c in $cmds; do grep -q $c COMMANDS || echo $c; done;
base64
bcd
seq
unlink
whoami
```
=> perlpowertools: more missing commands

bin/fmt
* In fmt_line(), the ```@out``` list describes one line of text
* Each word token keeps a record of trailing spaces after the word (i.e. "suffix" number in the code)
* Trailing space should be ignored for the final word on the line because it gets terminated by a newline
=> fmt: avoid space before newline

bin/rmdir
* In -p mode, split a directory argument with File::Spec (based on a recent change to mkdir)
* The final element of the split is ignored because that directory has already been handled by the unconditional remove()
* The '/' directory will not be removed if an absolute path is given on u***nix
* test1: perl rmdir -p A/B/C # relative path
* test2: perl rmdir -p /a/b/c # absolute path
=> rmdir: replace dirname() loop

bin/expr
* Similar to recent commit for uniq: 4d22ee8cc8e9b843b4365c1dd096c482841bda06
* Breaking up words like "re-\nturn" gets in the way of the pod formatter
```
--- pod0	2025-01-07 12:33:58.825372933 +0800
+++ pod1	2025-01-07 12:35:15.441604917 +0800
@@ -24,8 +24,8 @@
expr1 {=, >, >=, <, <=, !=} expr2
Returns the results of integer comparison if both arguments are
-        integers; otherwise, returns the results of string comparison us-
-        ing the locale-specific collation sequence. The result of each
+        integers; otherwise, returns the results of string comparison using
+        the locale-specific collation sequence. The result of each
comparison is 1 if the specified relation is true, or 0 if the
relation is false.
@@ -34,8 +34,8 @@
arguments.
expr1 {*, /, %} expr2
- …
```
=> expr: remove manual word breaks in pod

bin/rm
* is_recursive() is already smart enough to check both -R and -r, so manually setting ```$opts{R}``` is not required
* As a regression test I removed some subdirectories, first using -r, then -R
=> rm: simplify process_options()

bin/rm
* Previously chmod() was being passed a string as the first argument, which didn't look right
* I studied the OpenBSD version and it doesn't do any chmod() so remove it here too
* For non-interactive mode (neither -i nor -f), print a special prompt if a file is non-writable
* For interactive mode, print a normal prompt for every file
* For force mode, do not check if a file is writable or print a prompt
* To test this I created a new file and set the permissions to 0 with chmod before "rm x", "rm -i x" and "rm -f x"
=> rm: chmod not needed

bin/diff
* Initialise $x[$i] to new listref [0] in one statement, instead of assigning list element 0 separately
* Calling standard max() function avoids temporary variables when compared items are different
* Write loops in idiomatic form with ranges
* This was intended as a readability change, but I observed that when generating diffs on a large text file the performance is slightly improved
```
%wc -l bc bc.new 
2761 bc
2768 bc.new
5529 total
%time perl diff.old -u bc bc.new > /dev/null
real	0m11.003s
...
real	0m10.845s
...
real	0m10.965s
%time perl diff.new -u bc bc.new > /dev/null
real	0m9.470s
...
real	0m9.546s
...
real	0m9.329s
```
=> diff: simplify LCS_matrix()

bin/ed
* Yesterday when editing a file I discovered the escape sequence "\n" was expanded to a newline when used in a substitution command
* This has the unintended result of updating one or more elements of the lines-list to contain multiple newline characters
* GNU and OpenBSD versions treat "\n" as a regular "n"; follow this for compatibility, and to avoid the problem of line x containing many lines
```
%perl ed.old -p 'ed>' a.c
623
ed>1
ed>s/h/\nH\nI\n\nJ\n/
ed>p
#include <stdio.
H
I
J
>
ed>Q
%perl ed.new -p 'ed>' a.c
623
ed>1
ed>s/h/\nH\nI\n\nJ\n/
ed>p
#include <stdio.nHnInnJn>
ed>Q
```
=> ed: avoid literal newline in s///

bin/wc
* The byte count reported by wc was different depending on whether the -w option is set (-w is set by default)
* The the code for $opt_w was modifying the line string to calculate a word count before the code for the other options is able to inspect the line
* This patch makes the code $opt_w modify its own copy of the line
```
%stat aaa.c # stat shows the correct size too
File: aaa.c
Size: 470       	Blocks: 8          IO Block: 4096   regular file
Device: b302h/45826d	Inode: 1034312     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/      pi)   Gid: ( 1000/      pi)
Access: 2024-11-18 12:56:23.329998345 +0800
Modify: 2024-11-18 12:56:23.329998345 +0800
Change: 2024-11-18 12:56:23.329998345 +0800
Birth: 2024-11-18 12:56:23.329998345 +0800
%perl wc  aaa.c # -w enabled by default
30 …
```
=> wc: inconsistent byte counts

bin/ed
* I hadn't tested this scenario before
* First I start ed with a file a.c
* The command "e !ifconfig" then replaces the buffer with the output of ifconfig
* Listing current filename with "f" command after this should still show "a.c" (this is how GNU and OpenBSD versions behave)
* The directory check should not happen for "e !..." case
=> ed: e! should not set filename

bin/ed
* edEdit() implements r and e, but r doesn't technically change the file being edited; it only adds more content to the file's buffer
* r command was updating $RememberedFilename, which is undesirable
* edEdit() is too complicated and I'd like to split it soon into 2 functions: edEdit() for e and edRead() for r (currently edRead() is a helper function calling edEdit())
* test1: open a one.c file, "r" a two.s, then verify with "f" command that the editor file is still one.c  
* test1: open a one.c file, "r !ifconfig" to include command output in buffer, then verify with "f" command as before
=> ed: r command should not update saved filename

bin/ed
* Avoid saving address 0 as a "marked address"
* When edMark() was first written I didn't pick up that this usage was not allowed in other versions of ed
* test1: 1kx --> save address 1 as mark "k", valid if the buffer is not empty
* test2: 0ky --> save address 0, invalid
* test3: kz --> save current address as mark "z", valid if the buffer is not empty
=> ed: 0k is not OK

bin/ed
* Edit (e) command has a forceful alternative (E), but read (r) command doesn't (since r doesn't destroy the buffer)
* edEdit() continues to handle e and E ($QuestionsMode param determines the mode)
* r and e commands both use the saved filename if no argument is provided
* Command arguments starting with '!' now call function init_pipe(), which rejects NUL and provides an argument list to pipe form of open()
* Also add helper functions open_file_ro() and readin_lines() for common code
* r command never updates $RememberedFilename; e command updates it if a file argument was provided
* test1: "e !this" --> bad command, show error, buffer unchanged
* test2: "r !this" --> same as test1
* test3: "e !ls -l" --> buffer replaced with ls output if buffer is clean
* test4: "E !echo E" --> buffer …
=> ed: factor r command out of edEdit()

bin/ed
* Extend the filename validation from the f command to the commands e and r, which also take a filename argument
* Now the code can fail slightly earlier, before open_file_ro() is called
=> ed: consistent filename validation

bin/ed
* I found that the "w !CMD" case had the same problem as "r !CMD"; avoid updating $RememberedFilename when writing lines from buffer to an external command thru a pipe
* Now init_pipe() takes an extra WriteFlag argument so edWrite() can use it too
* For consistency add illegal_file() check in edWrite() before output file is opened
* Also add quotewords() in edPipe() to allow system() to be passed an argument list
* test1: ```1,2w !rev``` --> pipe buffer lines 1-2 into rev command
* test2: ```$w ..``` --> illegal_file() == TRUE
* test3: ```!cc secret.c``` --> build secret project file
=> ed: w! command should not update saved filename

bin/ed
* When writing a file, w command takes an optional filename argument
* If no filename argument is provided, the "current" filename is used
* If a filename argument is provided, write to that file but don't update the current filename
* Found when testing against GNU and OpenBSD versions
* NB: OpenBSD version calls get_filename() with Save param set to false
```
%perl ed -p 'PROMPT...' # f command still shows original a.s after write to b.s
PROMPT...e a.s
839
PROMPT...f
a.s
PROMPT...w b.s
839
PROMPT...f
a.s
PROMPT...q
```
=> ed: w command should not update current filename

bin/od
* od is expected to support a -t option for specifying output formats that don't exist as a single letter option
* 2- and 4-byte hex output is possible without -t, but "-t x1" is the normal way to request 1-byte hex
* Other format specifiers can be added to -t later, but for now add x1, x2 and x4
* Update pod and usage string
=> od: support 1-byte hex format

bin/od
* Add other integer format options (u1,u2,u4,d1,d2,d4,o1,o2,o4), as well as the aliases for options -a and -c
* 8-byte integer formats could be added in future (these are supported by GNU version)
* Make more of an effort to align output for -a and -c modes
=> od: support more output formats with -t

bin/od
* If perl doesn't have 64bit ints, show a warning and exit
* On my armv7 linux system the provided perl does have 64bit int enabled, but I built another perl without it
* Tested against GNU version
=> od: add 64bit integer formats

bin/od
* Support arguments "-t f4" and "-t f8", which are already exposed as options -f and -F respectively
* In future, od can support multiple formats at once, e.g. "-t f4f8", but for now only one format is allowed
=> od: make float formats accessible with -t

bin/ed
* In BSD ed, the -s flag is for running an ed script
* Modified buffers don't prevent the editor from quitting or editing a new file in this mode
* GNU ed doesn't seem to follow this, but to me the GNU interpretation seems inconsistent with the meaning of -s
=> ed: honour -s flag for w & e commands

bin/ed
* I found a case where ed allowed unsaved changes to be lost
* The default behaviour of "w" command is to write all lines from the editor buffer
* In the case of 1w or 1,2w command, only the selected lines are written and there may be unsaved changes on other lines, so don't unset the "dirty" flag
* The flag should be unmodified also in the case of "w !cat", where all buffer lines are written to a pipe
* This patch makes ed consistent with BSD and GNU versions
```
%perl ed -p 'edmond>' a.s # desired behaviour
839
edmond>10d 
edmond>1w tmp.txt
13
edmond>q
?
edmond>h
buffer modified
edmond>Q
```
=> ed: buffer is dirty unless all lines were written

bin/moo
* In debugging I discovered the numbers 8182 and 4594 were being treated as valid
* The unix version of moo selects a number where each digit occurs only once in the number [1]
* A guess containing non-unique digits is not a valid guess [2]
* Add a function to check for duplicate digits in guess
* Rewrite secret number generator with shuffle() to guarantee unique digits
1. http://squoze.net/UNIX/v6man/man6/moo.pdf
2. https://github.com/hansklav/MOO
=> moo: distinct-digits rule was not followed

bin/ed
* The code was more complicated than it needed to be
* Copy & delete operations can always be done in the same order; first copy, then delete
* Delete happens for "m" command but not for "t" command (edMove() handles both)
* If lines were copied before the start address, the address of the lines to be delete was increased by the number of lines copied
* test1: 17,18m5 --> after copy, original lines to delete are now at 19,20
* test2: 17,18m29 --> no address adjustment needed before deleting original lines
=> ed: simplify edMove()

bin/maze
* The size of the maze is counted in whole numbers; fractions don't maze sense
* get_number() is used for input validation
* Make get_number() reject the input if the number contains non-digits
* Numbers don't allow a '+' prefix as in some commands
* If EOF was seen when prompting for a number, terminate the program
* test1: ```perl maze 11 11``` --> valid, no prompt
* test2: ```perl maze 12.34 12.6666666666666666666``` --> invalid, will prompt for both width & height
=> maze: reject fractional width/height

bin/sum
* sha224 was missing (provided by perl in Digest::SHA)
* Take advantage of other Digest algorithms which may already be installed from CPAN (but don't require them to be installed)
* Add SHA3 functions as well as JH, Whirlpool, Haval256, BLAKE, MD2 and MD4
* List optional algorithms in usage string and POD (don't attempt to detect which are installed prior to use)
* NB: Digest::MD6 fails to build and I sent an email to the maintainer (for now don't include MD6)
* In future the different algorithm functions could be merged into a common function since they mostly use the Digest.pm API
=> sum: add missing sha224 algorithm

bin/od
* GNU and OpenBSD versions support either -h or -x for 2-byte hex, and -H/-X for 4-byte hex
* This version had -X, -x and -H but not -h
=> od: add -h alias for -x

bin/od
* GNU and OpenBSD versions support -d for 2-byte unsigned decimal and -D for 4-byte unsigned decimal
* This versions was missing -D; it's a shortcut option for -t u4
* The OpenBSD manual incorrectly states that -D is an octal format[1]
* The OpenBSD source confirms the format is unsigned decimal[2]
1. http://man.openbsd.org/od
2. https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/hexdump/odsyntax.c?annotate=1.28 (L127)
=> od: add -D option

bin/ed
* The substitution s/\z/NEW/ produced the unwanted outcome of $lines[$x] containing two lines of text
* Address this by not including trailing newlines in the editor buffer anymore
* Introduce helper function get_terminated_line() which adds the newline
* Now s/\z/NEW/ is interpreted the same as s/$/NEW/, i.e. append NEW to end of line
* Bump version number in case of regressions
* Removing the newlines from the editor buffer also reduces memory usage, but that is not the main intent of this patch
Test...
1. Null command
```
*1
```
2. List command w/lineno
```
*1,2ln
1	#include <stdio.h>$
2	#include <stdlib.h>$
```
3. Print command
```
*1p
```
4. Join command
```
*1,2j    
*1
#include <stdio.h>#include <stdlib.h>
```
5. Transpose (copy) command
``` …
```
=> ed: save space in editor buffer

bin/diff
* GNU and OpenBSD versions support the -s flag, which is similar to -q
* -q shows a "files differ" messages instead of showing the diff
* -s explicitly tells the user when the files are the same, instead of silently exiting
* Improve how -q is documented; it doesn't print anything for identical files
* -q and -s are not mutually exclusive
* While here, remove manual assignments of $opt_u and $opt_c which are not needed (the subsequent code refers to $Context_Lines and not these variables)
```
%perl diff -qs a.c a.c
Files a.c and a.c are identical
%perl diff -qs a.c a.s
Files a.c and a.s differ
```
=> diff: add -s option

bin/patch
* Improve error messages if open() fails
* INFILE was listed instead of the original file path
* OUTFILE was listed instead of the path provided to -o, e.g. if I specify an invalid argument
* Style: switch filehandles to my-variables
* Style: add more quotes for hash keys
```
%perl diff env.c env2.c | perl tee env.diff
61d60
< 	setprogname(*argv);
79d77
< 		case '?':
%perl patch -o /G/G env.c env.diff 
Hmm...  Looks like a normal diff to me...
Patching file env.c using Plan B...
Couldn't open OUTFILE: No such file or directory
Skipping patch...
% chmod 0 env.c
%perl patch -o NEW_ENV env.c env.diff
Hmm...  Looks like a normal diff to me...
Patching file env.c using Plan B...
Couldn't open INFILE: Permission denied
Skipping patch...
```
=> patch: add paths to error messages

bin/patch
* The Getopt library makes the original order of options invisible, i.e. we can't tell if -e comes before or after -c
* By default, patch attempts to guess the type of the input diff
* Options -c, -e, -n & -u direct the program to look for a certain diff format
* Specifying -c and -e results in undefined behaviour in this version so raise an error
* In GNU patch, the order of -c and -e matters, i.e. -e will win if it appears after -c
* type_conflict() function will print the long-option names of the conflicting diff types
```
%perl patch -C  -c -e  env.c env.diff  
patch: incompatible input type specifiers: --context --ed
```
=> patch: raise error for incompatible format options

bin/patch
* I noticed a runtime error within Patch::Ed::apply() where the throw function can't be resolved
* This error didn't happen when I switch back to historical commit 8a1ef6abe04b811ec9040bd4810e39cd73ca0945
* The Patch::import() function had been removed, and this was forcibly putting throw into the caller's namespace
* None of the other subclasses of Patch call throw(), only Patch::Ed does
* The old import() approach was not the Right Thing so I don't want to revert to it
* Make throw() an oo method instead of a simple function; this allows perl to resolve it from the parent class
* Delete an incorrect comment that origfile comes from -o option (-o is output and origfile is input)
```
%perl patch -u a.c patch.ed
Not a unified diff!
Skipping patch...
Undefined subroutine &Patch::Ed::throw …
```
=> patch: throw() regression

bin/patch
* The original options hash from the Patch object is blessed again as Patch::Context (or other subclass)
* The option attributes are now available in $self->{$x} (e.g. $self->{output}), and $self->{options} was not being accessed
* The comment about $self->{o_pos} indicates it's also dead code, and I don't see any references to it
* As a regression test I processed a "normal" diff with "perl patch -n a.file a.diff"
=> patch: tidy object data

bin/patch
* If EOF is seen, process hunk items seen so far, then terminate
* I was debugging why a "short hunk ignored" error occurred for the last hunk in a 2-hunk diff
* undef was being matched against valid-diff-line regex, but undef means there are no more lines in the diff to process
=> patch: don't reject final hunk in context diff

bin/ed
* Avoid special meaning of \Z and \z escapes when substituting text
* The special meaning of \n was already prevented in this way
* Add a missing call to get_terminated_line() in edSubstitute() that was found when testing this (the result of the s command is conditionally printed)
* It is still possible to bind a substitution to the end of a line using ```s/$/text/```
* Tested against GNU ed
=> ed: compatible \Z and \z in substitute

bin/morse
* Sometimes letter case was being folded and sometimes it was not
* When debugging, txt2mors() handled the folding but txt2word() was missing this logic; both of these functions lookup values in %chartab
```
%perl  morse aia
dit daw 
dit dit 
dit daw 
%perl  morse AIA
%perl  morse -s aia
.-
..
.-
%perl  morse -s AIA
.-
..
.-
```
=> morse: fold case bug

bin/moo
* The maximum number of distinct digits is 10
* This version of moo takes an optional size argument
* It is more correct to show an error if the requested size is invalid
* Based on commit f3248c817c65b13363fbc27f5c10c11b7201475e in bin/fish, add entropy thanks to hash keys being "unordered"
=> moo: raise error for size>10

bin/chgrp
* In modify_file(), delete a -e file check immediately before stat()ing the file
* Allow stat() to fail; it will cover the case where the file argument doesn't exist
```
%perl chgrp root a/b/c/d
chgrp: failed to stat 'a/b/c/d': No such file or directory
```
=> chgrp: redundant file check

bin/join
* Simplify code to make it clearer to the reader that get_arg() has only one function parameter, i.e. $arg
* Update loops using do-until-not pattern instead of regular do-while; found by perlcritic
```
%perl cat names # regression test
1 BoB
2 Budii
3 B-LITE
10 BLINK
%perl cat prices
1 $500
2 $30
3 50c
6 $2
%perl join names prices
1 BoB $500
2 Budii $30
3 B-LITE 50c
```
=> join: confusing declarations

bin/patch
* A normal diff can contain (a)dd, (c)hange and (d)elete commands
* For the Add command, a single target address is expected to be prefixed before "a"
* Diff utils output data in form of XaY,Z and not X,YaZ (so in practice the error condition should not happen)
* GNU diffutils manual described and Add command as "LaR", where L is a single line number and R is a range (e.g. 3,4) [1]
* Make this version of patch reject malformed Add commands
* Print the offending input data and line number
* Calling $patch->reject() is needed for setting the correct exit code
* When exiting on failure, avoid printing "done" message after preceding error messages
* I created an invalid input file manually to test this
1. https://www.gnu.org/software/diffutils/manual/html_node/Detailed-Normal.html
```
%cat …
```
=> patch: improve validation of normal diffs

bin/patch
* In a Normal diff the commands c and d operate on a line number range written as x,y
* The range 2,1 is not valid
* Reject a diff if a backwards range is seen to avoid incorrectly processing a file, then reporting "successful patch"
* diff tools would not output diffs with incorrect ranges like this; the new validation is to protect against mangled input
* I found this when testing against the GNU version
```
%patch m del.diff # GNU
patching file m
patch: **** malformed patch at line 1: 10,6d5
%perl patch m del.diff 
Hmm...  Looks like a normal diff to me...
Patching file m using Plan A...
Malformed input at line 1: 10,6d5
1 out of 1 hunks ignored--saving rejects to m.rej
```
=> patch: improve validation of normal diffs (2)

bin/patch
* When patching a file with -D option (aka --ifdef), "-Did" and "-D id" usages are accepted
* I found that an empty string argument is sometimes ignored, and sometimes raises an error
* The OpenBSD version raises an error if the argument to -D is not a valid identifier, i.e. starts with alpha followed by alphanumeric & underscore
* Add validation in this version; as a benefit the invalid empty string usage is rejected
* test1: ```perl patch -D''```   ---> already caught by Getopt::Long
* test2: ```perl patch -D '' file```   ---> now errors; previously ignored
* test3: ```perl patch -DValid_id0 file```  ---> ifdef name accepted as before
* test4: ```perl patch -D 'd/e;f~ine#' file``` ---> now errors; previously accepted
=> patch: -D argument validation

bin/rm
* When attempting to remove a file that doesn't exist, rm shows a prompt about the file being read-only
* If I then confirm by typing "y", I see the unlink() error which explains the file wasn't found
* Bypass the prompt by adding an -e file check; the "-w FILE" is false if FILE doesn't exist
```
%perl ls not-exist
ls: can't access 'not-exist': No such file or directory
%perl rm not-exist
not-exist: Read-only ? y
rm: cannot remove 'not-exist': No such file or directory
%perl rm -f not-exist
%echo $?
0
```
=> rm: unexpected confirmation prompt

bin/grep
* A directory might have 1000s of entries and sorting would make ```grep -r``` invocation slower (there is no standard option to toggle sort)
* Be consistent with OpenBSD and GNU versions by processing directory entries in the order they appear
* As part of verification, I compared output of ```grep -r``` on OpenBSD (filenames not sorted) with ```ls -1a``` (filenames sorted)
* Clarification: ```@list``` variable is only for setting up argument list for recursive matchfile() call. Declare it within if-block scope to avoid potential of old entries appearing between loop iterations.
```
%pwd
/home/x/PerlPowerTools
%# GNU filename matches are unsorted
%grep -r perl bin | cut -d ':' -f 1  | uniq | head -n 15
bin/uniq
bin/cal
bin/expand
bin/basename
bin/primes
bin/ls
bin/uname
bin/kill
bin/diff …
```
=> grep -r should not sort directory entries

bin/fortune
* Mention -v version number option in the usage string and POD manual
* Possibly the POD manual was copied from the NetBSD version, which doesn't have the -v option
* As done for other scripts, remove manual word breaks in POD which don't render nicely under pod2text
* Correct typos: "initial", "implementation"
=> fortune: document the -v flag

bin/ls
* Global variables ```%Attributes```, ```$Attributes``` and ```@Dirs``` were aliased within subs; found by perlcritic
* Move declarations of some globals into the logical main-block; these don't have to be global
* Globals ```$Arg```, ```$Attributes``` and ```@DirEntries``` are unused so they disappear
* Regression test: ```cd ~/PerlPowerTools/bin && perl ls -1R .. | md5sum```
=> ls: reduce the number of globals

bin/ls
* The column widths for "ls -R" didn't always look right
* List() is called for each directory/subdirectory
* Global variable $Maxlen is increased by 1 unconditionally, despite the value being saved from the previous call
* When I tested "perl ls -R .." I observed $Maxlen values from 21-59, incrementing by 1 for each directory
* The entries for the subdirectories are printed with too much space
* When I compare the output of GNU ls, the column widths are calculated for each directory listed
* Fix this by making $Maxlen a non-global; it is only used in List() and the value between calls should not be saved
* Extra: remove unused variable $BlockSize
```
%# BEFORE: maxlen of ../bin takes value from previous .. then adds 1
%perl ls -R ..
maxlen[21]
..:
CNAME                 LICENSE-BSD2 …
```
=> ls: incorrect column widths in -R mode

bin/uniq
* The uniq command expects a number argument to options -s and -f
* Make $opt declaration clearer; it is not a parameter of get_numeric_arg()
* Update validation to raise error for empty string (not a number)
* Zero is allowed for -s and -f option arguments, so get_numeric_arg() allows it
* Bump version
```
%perl uniq -f '' file
uniq: invalid number of fields to skip: `'
%perl uniq -s '' file
uniq: invalid number of bytes to skip: `'
```
=> uniq: get_numeric_arg() versus empty string

bin/fortune
* This version of fortune can be passed a file argument, which will be used as the fortune file
* In find_path(), if the direct path check fails a loop is entered where the file argument is appended to each search directory
* When the file argument is an absolute path, entering this loop is incorrect because the absolute path will be prefixed with the search directory path
* fortune's debug (-d) option makes the file search easy to see
* While here, use catfile() to join relative paths with the search directory
```
%perl fortune -d /dev/null # BEFORE: 2nd is_fortune_file() call shouldn't happen
opts are:
d == 1
Building file list. Containers are Percent specified and Percent unspecified
@ARGV (1 arguments):
/dev/null
trying to add item /dev/null to Percent unspecified …
```
=> fortune: bad assumption in find_path()

bin/fortune
* The "ins" suffixes are ins.c, ins.ftn and ins.pas---one of these was written with a comma [1]
* Allow --version to work the same as -v, instead of printing an ugly getopt message
1. https://bitsavers.trailing-edge.com/pdf/apollo/000792-A01_Domain_Pascal_Language_Reference_Dec90.pdf (page 189)
=> fortune: file extension blacklist correction

bin/cmp
* Skip numbers (optional arguments 3 & 4) can be specified in decimal or hex
* When testing on OpenBSD and Linux, "0X" hex prefix is supported, so add it to this version too
* I didn't test on NetBSD, but the NetBSD version calls the C strotoll() function, which is documented to accept "0X" [1] [2]
* Tweak POD manual
1. https://cvsweb.netbsd.org/bsdweb.cgi/src/usr.bin/cmp/cmp.c?annotate=1.21  line128
2. https://man.netbsd.org/strtoll.3
```
%ifconfig > F1
%cp F1 F2
%perl cmp F1 F2
%perl cmp F1 F2 0x1 0X1 # same skip, different prefix, same day
%perl cmp F1 F2 0x1 0X2
F1 F2 differ: char 1, line 1
```
=> cmp: 0X and 0x are valid hex prefix

bin/patch
* Make more of an effort to reject patches where line addresses are not valid
* Reading over the ed command parser in Patch::Ed::apply(), the regex assignment was not always correct
* test1: invalid command "19,0d" was incorrectly interpreted as (valid) "19,19d" thanks to the '||' operator
* test2: "19,18d" command was accepted, but the range is backwards
* test3: "0,19d" command was accepted, but address 0 is not allowed for "d"
* test4: "0,19c" command was accepted, but address 0 is not allowed for "c"
* I tested this by skipping to PLAN_J, using a diff with an update on line1 (ed command 0a is valid and means append after line 0)
* Modifying elements of the diff input, I could trigger the new validation errors
```
%perl diff -e env env2 | perl tee env.diff # original test input
19,20d …
```
=> patch: improve validation of ed diffs

bin/random
Variable $warnings does not vary so delete it.
```
%# regress1
%printf "a\nb\nc\n" | perl random 2
a
%# regress2 (exit code of zero is correct)
%for i in `perl seq 50`; do perl random -e 100; echo -n "$? "; done; echo;
74 47 57 8 58 80 23 86 60 68 89 60 8 5 51 31 39 99 66 89 9 67 96 30 48 78 48 20 39 18 96 92 12 92 3 75 38 19 57 55 0 49 25 82 43 64 56 87 25 96 
```
=> random: small tidy

bin/chown
* If the 1st argument (user) of chown is an empty string, splitting the string results in an empty list
* Terminate the program before calling getpwnam()
```
%perl -Mwarnings -Mdiagnostics chown '' file # before patch
Use of uninitialized value $owner in getpwnam at chown line 56 (#1)
(W uninitialized) An undefined value was used as if it were already
defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
To suppress this warning assign a defined value to your variables.
To help you figure out what was undefined, perl will try to tell you
the name of the variable (if any) that was undefined.  In some cases
it cannot do this, so it also tells you what operation you used the
undefined value in.  Note, however, that perl optimizes your program
and the operation displayed in …
```
=> chown: avoid getpwnam(undef)

bin/ls
* Test case: "perl ls spell ar ar ."
* The argument list is split into files and directories
* File arguments are listed first in multi-column output, followed by each directory argument
* Previously List() was called once per file argument; this was incorrect because List() is unable to format the arguments together in columns
* Fix this by preparing a sorted file list and attribute hash (containing stat() data), then calling List() once
* DirEntries() has to be called once per file, then the stat data returned is merged into a single hash
* Bump version
```
%perl  ls spell ar ar .
ar     ar     spell                                                                                                           
.:
YES.diff        clear           fish            ls.diffe        ppt …
```
=> ls: list file arguments in columns

bin/cmp
* The POD manual stated that octal values were supported for options skip1 and skip2, but it didn't work
* Previously cmp used eval() to convert user input into a number; I suspect the octal support was broken when the eval() code was removed
* Octal is supported by NetBSD's cmp
```
%cp ar ar2
%strace perl cmp ar ar2 0X4f 0117 2> trace
%fgrep '79,' trace
lseek(4, 79, SEEK_SET)                  = 79
lseek(5, 79, SEEK_SET)                  = 79
```
=> cmp: restore octal skip values

bin/ls
* When testing ls today I discovered the error: Can't use an undefined value as a HASH reference at ls line 525.
* Test case: ```perl ls xxx ar a.x pig```  ...where files xxx and a.x don't exist
* I broke this in the previous commit around where DirEntries() is called for ```@Files``` list
* Add the correct return value guard
* DirEntries() prints a warning and returns an empty list if stat() fails on its file argument
* Avoid listing filenames where stat() failed by storing good arguments in ```@okfiles``` list
```
%perl ls  xxx ar a.x pig # with change applied
ls: can't access 'xxx': No such file or directory
ls: can't access 'a.x': No such file or directory
ar   pig
```
=> ls: runtime error for non-existent file argument

bin/grep
* In pod SYNOPSIS, -i was listed twice and -Z wasn't listed
* Usage string was missing -Z too
* Sort single letter options, including getopts() call; this makes it easier to see what is happening
* No intended functional change
=> grep: documentation update

bin/chgrp
* Similar to commit 471e64b3e0ec3a1fd9c85ecec085d97fabe47417 for bin/chown
* Fail early if the 1st (group) argument is an empty string to avoid unnecessary getgrnam('') call
* style: forward declaration of modify_file() is not needed if the method is called with parens
* style: move default exit() statement above the subroutine declarations, as done in other scripts
=> chgrp: fail early for empty string

bin/tar
* Add missing getopts() return value check
* This version of tar didn't have a usage string, so add one
* Don't list -c in usage string for now because archive creation isn't implemented
* Unconditionally use Compress::Zlib because it is a core library
```
%perl tar -x -f yo -L
Unknown option: L
usage: tar {-tx} [-mvZz] [-f archive] [file ...]
```
=> tar: fail early for bad options

bin/chmod
* The supported options are -R/-L/-H/-P, and grouping of options is allowed (e.g. -LP)
* When adding an unexpected option letter to a group, the error message was misleading
*  ```perl chmod -Rp``` reported "invalid option -- pR", but R is a valid option
* Fix this by validation the option letters after the option string has been split into a single letters
```
%perl chmod -Rp 0 0 0 0 0 0 0 0 0 0
chmod: invalid option -- 'p'
usage: chmod [-R [-H | -L | -P]] mode file...
```
=> chmod: show which option is wrong

bin/tac
* If I type a bad option I want to see the correct options, not the program version
* As done in other scripts using getopts(), support --version option by adding a VERSION_MESSAGE() function
=> tac: don't print version number in usage string

bin/install
* Passing an empty string as a mode was being accepted and interpreted as -m0
* Empty string is not a valid mode specifier so catch it early
* I found this when testing against GNU and OpenBSD versions
=> install: -m MODE validation

bin/patch
* I generated a Context diff with 2 hunks
* I manually swapped the 2 numbers at the top of hunk1, from "1,4" to "4,1" (the line number range for the hunk)
* GNU patch correctly rejected the invalid diff, but this version crashed with an ARRAY error
* Add validation to reject a backwards range (based on code previously added for Normal diffs)
```
%cat diff.ctx 
*** id	Wed Mar  5 09:16:33 2025
--- id2	Wed Mar  5 09:14:36 2025
***************
*** 4,1 ****
- #!/usr/bin/perl
=begin metadata
--- 1,3 ----
***************
*** 12,24 ****
=cut
- #
- # An implementation of the 'id' utility in Perl.  Written for the Perl Power
- # Tools (PPT) project by Theo Van Dinter (felicity@kluge.net).
- #
- # $Id: id,v 1.2 2004/08/05 14:17:43 cwest Exp $
- # - 
use strict;
use File::Basename qw(basename); --- …
```
=> patch: crash for invalid context diff input

bin/mail
* I exported a mailbox with 24 items in mbox format
* The maximum valid message id is 24, but a very long number is interpreted as 24
* Another long message id is rejected, so this made me scratch my head
* perl debugger shows that the invalid message number errors for 0, 25 and 1111111111 are from L842 in main::msg_print()
* mailbox::messagex() takes the very long message id and returns a valid message instead of undef
* mailbox::messagex() has a guard for negative array index, but does not guard against index past end of array
* Adding an index guard fixes the problem on my system
* This was found when testing against the OpenBSD version
```
%perl mail -f mbox0.txt 
Loading the mailfile mbox0.txt
1    MAILER-DAEMON  Wed Feb 05 11:12   0/5310 Re: patch-2.7.6.200-be8b on H
2 …
```
=> mail: invalid message number accepted

bin/ed
* When the editor starts there is an implicit call to edEdit(), which will either load a named file or start the editor with an empty buffer
* edEdit() is also the handler for the commands E and e
* Starting ed with an empty string file argument is not valid
* Starting ed with a filename ending in '/' is not valid
* edEdit() returns an error string; write a little function to handle the error
* Special case: when starting ed with a non-existent file, a print a warning but not the '?' prompt (this is not a serious error for initial edEdit() because there is no editor buffer yet)
```
%perl ed -p 'ED>' ''
?
ED>h
invalid filename
ED>q
%
%perl ed -p 'ED>' newfile.cxx
newfile.cxx: No such file or directory
ED>h
cannot open file
ED>q
```
=> ed: initial edEdit() errors were lost

bin/install
* Include options -o and -g in the empty-string validation previously added for option -m
* Generally uid 0 means "root user" on unix, and -o 0 could be given to explicitly install files as this user
* The call to chown() was bypassed because of truth check
```
%perl mkdir d0 # after patch, as non-root user
%perl install -o0 file d0
install: chown 0.1000 d0/file: Operation not permitted
%perl install -g0 ar d0
install: chown 1000.0 d0/ar: Operation not permitted
```
=> install: -o0 and -g0 ignored

bin/date
* I was tracking why the Perl date command separated Mar and 14 with 2 spaces instead of one
* The default strftime() format string is "%a %b %e %T %Z %Y"
* The Linux manual for strftime() says %e is the same as %d, except that a leading zero is replaced with a leading space
* So day 1 would be "01" and " 1", but day 10 would have no leading space or zero
* Formatting the day number with "%2d" is good enough for %e specifier; previously day 14 was formatted as " 14" in setup_specifiers()
```
%perl date # with patch
Fri Mar 14 09:11:30 AWST 2025
%date # GNU
Fri Mar 14 09:11:31 AM AWST 2025
```
=> date: too much whitespace for %e format

bin/cal
* When running cal with no arguments the month number is determined from localtime(), which returns 0 for Jan
* Function fmt_month() needs 1 for Jan, so adjust the value passed in
* Patch tested against /usr/bin/cal on ubuntu (from package bsdmainutils)
* test1: ```perl cal 0 2025``` ---> invalid month
* test2: ```perl cal``` ---> now shows current month (5)
* test3: ```perl cal 5 2025```  ---> same output as test2
=> cal: correct current month value
